### ISSUE TITLE
Build error after upgrade to 1.3.1 in Next.js

### ISSUE THREAD

**Issue by nghieptiki** [react-hook-form/resolvers#100]
Hi guys,

I have an SSR app working on Node environments, after upgrade to 1.3.1 and build error:

>[2020-12-31T02:56:35.428Z] #16 90.33 > Build error occurred
>[2020-12-31T02:56:35.428Z] #16 90.34 /app/node_modules/@hookform/resolvers/dist/yup.js:2
>[2020-12-31T02:56:35.428Z] #16 90.34 import { transformToNestObject, } from 'react-hook-form';
>[2020-12-31T02:56:35.428Z] #16 90.34 ^^^^^^
>[2020-12-31T02:56:35.428Z] #16 90.34 
>[2020-12-31T02:56:35.428Z] #16 90.34 SyntaxError: Cannot use import statement outside a module
>[2020-12-31T02:56:35.428Z] #16 90.34     at wrapSafe (node:internal/modules/cjs/loader:1024:16)
>[2020-12-31T02:56:35.428Z] #16 90.34     at Module._compile (node:internal/modules/cjs/loader:1072:27)

I think the problem related to https://github.com/react-hook-form/resolvers/pull/95 PR.

**Comment by joshmanders** [comment]
Getting the same thing. Downgrading to `1.2.0` fixes it.

**Comment by jorisre** [comment]
Thanks for reporting.
I'm working on resolvers's V2 which will have a better module supports.

As a workaround,  you can use 1.3.0

**Comment by Rykuno** [comment]
> Thanks for reporting.
> I'm working on resolvers's V2 which will have a better module supports.
> 
> As a workaround, you can use 1.3.0

Bumping down to 1.3.0 does not solve for me. Thanks for your hard work, looking forward to V2 with module support. While this is currently putting a hold on validation we have been overall loving react-hook-form. 
```
{
   "@hookform/resolvers": "^1.3.0",
    "react-hook-form": "^6.14.0",
    "next": "^10.0.4",
}
```

**Comment by msheakoski** [comment]
@Rykuno You need to use `"1.3.0"`, not `"^1.3.0"`. Using the ^ means greater than or equal to 1.3.0 but less than 2.0.0. You can read more about it here: https://docs.npmjs.com/cli/v7/using-npm/semver#caret-ranges-123-025-004

**Comment by Rykuno** [comment]
> @Rykuno You need to use `"1.3.0"`, not `"^1.3.0"`. Using the ^ means greater than or equal to 1.3.0 but less than 2.0.0. Because of this, you still end up installing 1.3.1 or whatever the latest release is that satisfies the version constraint.
> 
> You can read more about it here: https://docs.npmjs.com/cli/v7/using-npm/semver#caret-ranges-123-025-004

Doh. I caught this in a PR this afternoon and came to correct what you just mentioned haha! Wish I read this last night.

**Comment by jorisre** [comment]
Thanks everyone for reporting and for provide informations to help us.

I'll close this issue because it's related to https://github.com/react-hook-form/resolvers/issues/71.

We published a v2 beta which solve this issue, more info here: https://github.com/react-hook-form/resolvers/issues/71#issuecomment-754623998

**Comment by jorisre** [comment]
👋🏻 
You can try the last version [v1.3.6](https://github.com/react-hook-form/resolvers/releases/tag/v1.3.6). The issue should be solved
