### ISSUE TITLE
Reason for removing jsons-schema resolver?

### ISSUE THREAD

**Issue by sramam** [react-hook-form/resolvers#112]
I see the feature was [merged](https://github.com/react-hook-form/resolvers/commit/ce3525a8ca6a70af7bfbacb93ecbe34c0af65864), but [reverted](https://github.com/react-hook-form/resolvers/commit/ce73c6e35386d7cb928526ab4d6f7972b1ddc909) in short order. 

Can't seem to find a reason for this. 
Would appreciate an insight into what happened?

**Comment by bluebill1049** [comment]
We had difficulty getting it to work at the time from memory, the package itself is quite old and hard to get it working with our build, I would recommend building a custom resolver at your own app.

**Comment by sramam** [comment]
thanks for the quick turnaround. will do.

**Comment by bluebill1049** [comment]
thanks for understanding.
