### ISSUE TITLE
RHF hookform resolvers throwing error in terminal 

### ISSUE THREAD

**Issue by gauravkrp** [react-hook-form/resolvers#113]
**Describe the bug**
RHF throws error in terminal - 
````
c:\dev\edugyanam\admin\node_modules\@hookform\resolvers\dist\yup.js:2
import { transformToNestObject } from 'react-hook-form';
^^^^^^

SyntaxError: Cannot use import statement outside a module
````
My RHF code - 
````
const yupSchema = Yup.object().shape({
......
  });

  const { register, handleSubmit, watch, setValue, errors, setError, clearErrors, control, formState } = useForm<UserLoginData>({
    resolver: yupResolver(yupSchema),
    mode: 'onSubmit',
    reValidateMode: 'onChange',
  });
  const { isDirty, touched, submitCount, isSubmitted } = formState;

  const onSubmit = async (data: any, e: any) => { ...
  ````

**Expected behavior**
It should have been compiled without errors.
It was working fine before as well, started throwing errors after updating my npm packages.

**CodeSandbox Demo**
https://codesandbox.io/s/nifty-grass-k6r3z?file=/pages/index.tsx

**Screenshots**
![image](https://user-images.githubusercontent.com/12250556/104443390-5dbfde00-55bc-11eb-93cb-2675626425cc.png)

**Environments:**
- Using Next.js 10.0.5 (latest)
- Using RHF 6.14.1 (latest)
- @hookform/resolvers version: 1.3.2
- Running on Node.js 15.5.x

**Comment by bluebill1049** [comment]
can you reproduce this in a codesandbox?

**Comment by gauravkrp** [comment]
> can you reproduce this in a codesandbox?

Yup Bill, here you go - https://codesandbox.io/s/nifty-grass-k6r3z?file=/pages/index.tsx

**Comment by sokardys** [comment]
Minimal sample, only importing libs: https://codesandbox.io/s/react-hook-form-wbhjt

**Comment by gauravkrp** [comment]
@bluebill1049 
#100 
https://github.com/react-hook-form/react-hook-form/issues/3816

**Comment by jorisre** [comment]
Thanks @gauravkrp 

Same as https://github.com/react-hook-form/resolvers/issues/100.

For more info: https://github.com/react-hook-form/resolvers/issues/71#issuecomment-754623998
