### ISSUE TITLE
Validation via resolvers does not work with dependent fields (yup, vest)

### ISSUE THREAD

**Issue by v1adko** [react-hook-form/resolvers#120]
RHK version: **6.14.12**
Resolvers version: **1.3.3**
Codesandbox:  [https://codesandbox.io/s/epic-goldberg-pllwj](https://codesandbox.io/s/epic-goldberg-pllwj)

```js
// My usage
useForm({
  defaultValues: { hasMoney: false, amount: 0 },
  mode: "onChange",
  resolver: vestResolver(validationSuite) || yupResolver(formSchema)
});
```

Schemas that depend on field values does not return correct errors object in `errors` or `formState.errors` or I'm missing something in configuration.

```js 
// Yup
const formSchema = object().shape({
  hasMoney: boolean().required(),
  amount: number().when('hasMoney', {
    is: true,
    then: number().required().min(1),
    otherwise: number().notRequired().optional()
  })
});
```

```js
// vest
const validationSuite = vest.create((data = {}) => {
  test('hasMoney', "Has money is required", () => {
    enforce(data[HAS_MONEY]).isBoolean();
  });

  if (data.hasMoney === true) {
    test('amount', "Amount is a number", () => {
      enforce(data.amount).isNumber();
    });

    test('amount, "Amount is required", () => {
      enforce(data.amount).isNotEmpty();
    });

    test('amount', "Amount is more than 0", () => {
      enforce(data.amount).gte(1);
    });
  }
});
```

I believe the issue is somewhere in the resolvers or core package since validation of the same form data directly is causing the expected errors.

**Comment by jorisre** [comment]
Hi @v1adko 
To be sure, when I toggle `Has money` to `yes`, `formState` doesn't contain the Yup error `ValidationError: amount must be greater than or equal to 1`, right ? _(same for Vest)_

I believe this behavior is normal, below the explanation _(@bluebill1049 will correct me if I'm wrong)_
`amount` field doesn't have an error because it value never change _(with mode `onChange`)_. You can't said the field is wrong if you haven't fill it.

Here your codesandbox, I updated the `amount` field and added the error message: https://codesandbox.io/s/long-cdn-98qw1?file=/src/FormWithYup.js
You'll get the error for `amount` field only if you submit the form and fill the field

Hope it helps :)

**Comment by v1adko** [comment]
Yes, you're right, that's the behaviour I expected to get.
So re-validate triggers for just the field that's being interacted with, not the whole set of values in the form? 
That would mean that dependent fields wouldn't work in any of the validation libs.

The only way I was able to achieve the behaviour I needed was to keep the "onChange" mode and call `trigger` directly in the onChange of the radio inputs.
Would love if there was a better API to subscribe to value changes (Controller-level onChange?) and not just watch them.
Hopefully [the new watch api](https://github.com/react-hook-form/react-hook-form/issues/497#issuecomment-768597301) will support form slices too.

**Comment by jorisre** [comment]
> That would mean that dependent fields wouldn't work in any of the validation libs.
It works until the field is filled depending on the form mode. 
As you said, you can use the `trigger` API to validate the field, I don't know any other way to do this. Maybe @bluebill1049 have a better idea.

**Comment by bluebill1049** [comment]
For depend on the field, you will have to use `trigger`, hook form is optimized for single field error.

**Comment by v1adko** [comment]
Cool, thank you, guys. Maybe this limitation should be mentioned somewhere in the docs since the behaviour of the validation library differs if used within react-hook-form resolvers?

**Comment by bluebill1049** [comment]
sounds good will do 👍
