### ISSUE TITLE
V7 Resolver context is not being passed to Joi validation

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/resolvers#121]
**Describe the bug**
If the joi validation library is used and the user passes in some custom context, then the context is not passed into joi. It is just displayed as null.

**To Reproduce**
Observe that when I call `scehma.validate` manually with context, I get the values. When I pass the context via `useForm`, I get null.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-svn2f?file=/src/index.js

**Comment by jorisre** [comment]
@wdfinch 👋🏻  Fixed in [v1.3.4](https://github.com/react-hook-form/resolvers/releases/tag/v1.3.4)

**Comment by wdfinch** [comment]
Thanks! So I was able to get this working using the code above. Does this mean I could just do something like 

```
resolver: joiResolver(schema)
cotext: {someContextValue: 'test'}
```

and it would automatically pass in the context now?

**Comment by jorisre** [comment]
> Thanks! So I was able to get this working using the code above. Does this mean I could just do something like
> 
> 
> ```
> resolver: joiResolver(schema)
> cotext: {someContextValue: 'test'}
> ```
> 
> and it would automatically pass in the context now?

Yes ! :)

**Comment by wdfinch** [comment]
Awesome! @bluebill1049 rather than `context`, would you be open to the idea of changing this to `options`? The reason being is for my use case I also want to change some of the default options passed to `joi` (mainly `abortEarly = false` so I can display all the errors at once). 

I believe I would still have to use the messier code above to do this right? In most of these validation libraries context is an option, if we just used options, then the user could add in the context and any customization all in the same object. What do you guys think? Am I missing something here?

**Comment by jorisre** [comment]
To be sure, you want to use `abortEarly = false`, right ? 
It's already the case for the resolver: https://github.com/react-hook-form/resolvers/blob/master/src/joi.ts#L53

You can use all Joi options you want:

```ts
useForm({
  context: { yourContext: 'value' },
  resolver: joiResolver(schema, { abortEarly: false, ...joiOptions }) // You can pass all Joi options except `context` which should be passed to `useForm` directly
})
```

**Comment by wdfinch** [comment]
Oh, nice. I didn't know there was a way to pass in options without having to use the longer syntax. Thanks so much! I think that handles all my issues here.
