### ISSUE TITLE
Cannot resolve symbol 'yupResolver' 

### ISSUE THREAD

**Issue by victsant** [react-hook-form/resolvers#133]
I am getting this error using the following 

`import { yupResolver } from '@hookform/resolvers/yup';`

yup: 0.32.8
@types/yup: 0.29.11
react-hook-form: 6.14.2
@hookform/resolvers: 1.3.4

**Comment by jorisre** [comment]
Hi @victsant 

Thanks for reporting.  Can you please provide a codesanbox with your problem ?

**Comment by victsant** [comment]
@jorisre it working now after doing a fresh install will reopen if it occurs again. Thanks!
