### ISSUE TITLE
Build error with next and @hookform/resolvers@2.0.0-beta.8 or later

### ISSUE THREAD

**Issue by hixus** [react-hook-form/resolvers#138]
Tried to update hook-form and hookform/resolvers. Latest version of hook-form itself seems to be ok but hookform/resolvers from 2.0.0-beta.8 cause build error:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - ./node_modules/@hookform/resolvers/dist/resolvers.module.js
Attempted import error: 'set' is not exported from 'react-hook-form' (imported as 'r').
```

2.0.0-beta.7 is last version that does not cause the error.

**Comment by jorisre** [comment]
Hi @hixus

Do you use the v7 of react-hook-form ? Starting at [v2.0.0-beta.7](https://github.com/react-hook-form/resolvers/releases/tag/v2.0.0-beta.7), @hookform/resolvers require the v7 of react-hook-form.

Thanks for reporting, can you provide a full example reproduction ?

**Comment by hixus** [comment]
Ok, thank you. Didn't notice the v7 requirement so had only latest v6 of hook-form itself.
