### ISSUE TITLE
react_hook_form_1.transformToNestObject is not a function with rc1 but not with beta15

### ISSUE THREAD

**Issue by terebentina** [react-hook-form/resolvers#139]
When validation fails I get this error with resolvers 2.0.0-rc.1 but not with 2.0.0-beta15
CSB: https://codesandbox.io/s/yup-resolver-jxqtb?file=/src/App.js
Click submit without filling the field which is marked as required and you'll get the error.
Switch the resolvers to the latest beta and the error is gone.

**Comment by jorisre** [comment]
Hi @terebentina 
`2.0.0-rc.1` is an old version before the beta was released. To get it works you have to use the beta: `@hookform/resolvers@beta`

**Comment by terebentina** [comment]
Oh, got it, thanks! For some reason I thought rc.1 was the latest

**Comment by BigWhale** [comment]
> Oh, got it, thanks! For some reason I thought rc.1 was the latest

Happened to me too. It would make sense to remove the rc1 release. If rc2 hits there will be even more confusion.
