### ISSUE TITLE
Jest cannot parse the modules when testing

### ISSUE THREAD

**Issue by biem97** [react-hook-form/resolvers#140]
![image](https://user-images.githubusercontent.com/35174855/111090445-bdbffb80-84fd-11eb-95e6-c9771349ddc6.png)

I just started using react-hook-forms as well as the resolvers. I ran into this problem when I do unit tests with @testing-library and jest. I can fix this by modifying the yup.js file in the dist folder.

`import { transformToNestObject } from 'react-hook-form'; ` ---> `const { transformToNestObject } = require('react-hook-form');`

`export const yupResolver ...` ------> `module.exports = { yupResolver };`

I'm not sure whether I'm missing something on the config or it's just a small bug.

**Comment by jorisre** [comment]
Hi 👋🏻 

A possible solution: https://github.com/react-hook-form/resolvers/issues/97#issuecomment-754733737

**Comment by biem97** [comment]
Thank you @jorisre.
