### ISSUE TITLE
[Zod] TypeScript wrong export for zodResolver

### ISSUE THREAD

**Issue by balzdur** [react-hook-form/resolvers#154]
**Describe the bug**
> This bug concerns compatibility issues with next versions of `zod` (still in beta)

The typing of `schemaOptions` is no longer exported form the same file.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-hir90

**Expected behavior**
I manage to retrieve the correct typing from the `zod` library. For now, I make use of `patch-package` to correct the problem.

```patch
diff --git a/node_modules/@hookform/resolvers/zod/dist/types.d.ts b/node_modules/@hookform/resolvers/zod/dist/types.d.ts
index 217661e..7e145cf 100644
--- a/node_modules/@hookform/resolvers/zod/dist/types.d.ts
+++ b/node_modules/@hookform/resolvers/zod/dist/types.d.ts
@@ -1,6 +1,6 @@
 import { FieldValues, ResolverResult, UnpackNestedValue, ResolverOptions } from 'react-hook-form';
 import * as z from 'zod';
-import type { ParseParams } from 'zod/lib/src/parser';
-export declare type Resolver = <T extends z.ZodSchema<any, any>>(schema: T, schemaOptions?: ParseParams, factoryOptions?: {
+import type { ParseParamsNoData } from 'zod/lib/helpers/parseUtil';
+export declare type Resolver = <T extends z.ZodSchema<any, any>>(schema: T, schemaOptions?: Partial<ParseParamsNoData>, factoryOptions?: {
     mode?: 'async' | 'sync';
 }) => <TFieldValues extends FieldValues, TContext>(values: UnpackNestedValue<TFieldValues>, context: TContext | undefined, options: ResolverOptions<TFieldValues>) => Promise<ResolverResult<TFieldValues>>;
 ```

**Screenshots**
No type safety on `schemaOptions`
![image](https://user-images.githubusercontent.com/40292402/114543585-adfd1980-9c59-11eb-8a0a-063a602b4bf2.png)

**Comment by jorisre** [comment]
Hi @balzdur 
Thanks for reporting, which version of zod do you use ?

**Comment by balzdur** [comment]
` v3.0.0-alpha.33 ` you should visualize the "lack" of error in the CodeSandbox (with all the other packages version)

**Comment by jorisre** [comment]
We currently support zod v2, that's you get the error. 
`zod/lib/helpers/parseUtil` does not exist in v2
