### ISSUE TITLE
Superstruct v0.10 doesn't work

### ISSUE THREAD

**Issue by federico-moretti** [react-hook-form/resolvers#16]
Superstruct resolver doesn't work with the version 6.0.0, I tried the Yup resolver and it's working fine.

Steps to reproduce:
- Click submit
- It shows no errors and submit the values

https://codesandbox.io/s/currying-fire-um7b5

PS: thank you for the amazing library and hard work.

**Comment by bluebill1049** [comment]
We will support the old version for now then until more users want us to support that latest version.

**Comment by pix2D** [comment]
Would love support for the latest version. 👀

**Comment by bluebill1049** [comment]
> Would love support for the latest version. 👀

send us a PR plz :)

**Comment by jgeschwendt** [comment]
I've played around with writing a resolver for the 0.10.x version but won't completely work until this issue gets fixed. 

https://github.com/ianstormtaylor/superstruct/issues/394

**Comment by bluebill1049** [comment]
oh, thanks a lot @jgeschwendt 🙏

**Comment by InSuperposition** [comment]
There is a PR open for the issue @jgeschwendt mentioned, hopefully, it will be merged soon.

https://github.com/ianstormtaylor/superstruct/pull/440

**Comment by bluebill1049** [comment]
@InSuperposition the PR has been sitting there for months...

**Comment by zenflow** [comment]
@bluebill1049 It just got merged 🚀

**Comment by bluebill1049** [comment]
oh wow! that's awesome, please send us a PR if you got time, otherwise, I will have a look at it over the weekend.  exciting, superstruct is going to be working as well 👍

**Comment by zenflow** [comment]
@bluebill1049 Awesome! I probably won't be first to making the PR though since I'm not familiar with how react-hook-form works & I haven't even used it yet lol.. But it looks awesome and I'm excited to try it next time I need a form library. Thanks for maintaining it 🤗

**Comment by bluebill1049** [comment]
No worries @zenflow actually we probably can close this issue right? as long as the user starts to using `0.11`?

**Comment by zenflow** [comment]
@bluebill1049 No I don't think we can close this yet. I saw a lot of changes in that project recently, including renaming some of the module exports. Probably those changes still need to be integrated here. A stable v1.0 release should come soon though https://github.com/ianstormtaylor/superstruct/issues/491#issuecomment-731302690

**Comment by bluebill1049** [comment]
> @bluebill1049 No I don't think we can close this yet. I saw a lot of changes in that project recently, including renaming some of the module exports. Probably those changes still need to be integrated here. A stable v1.0 release should come soon though [ianstormtaylor/superstruct#491 (comment)](https://github.com/ianstormtaylor/superstruct/issues/491#issuecomment-731302690)

Thanks for the update. Will keep an eye on the V1 then.

**Comment by jorisre** [comment]
@federico-moretti @pix2D & @InSuperposition Superstruct v0.10 supported ! You can update to the latest version of `@hookfom/resolvers` :) .
