### ISSUE TITLE
Question: Support for Computed Types strongly-typed validation library for TypeScript?

### ISSUE THREAD

**Issue by YanaRGeorgieva** [react-hook-form/resolvers#161]
Hello, 
Are you planning on writing a resolver for [Computed types](https://github.com/neuledge/computed-types)? At least to me and my coworkers, it has been invaluable to our work and we would be happy if you did! In the past, we have patched one of your version of the Zod resolver. Now with the new updates, we see that those types of solutions are only temporary and a more general one is needed.
Best regards!

**Comment by jorisre** [comment]
Hi @YanaRGeorgieva 👋🏻 

What's your needs about Zod resolver ?

I've been playing with computed-types today and I created the resolver, feel free to review! 
https://github.com/react-hook-form/resolvers/pull/162

**Comment by YanaRGeorgieva** [comment]
Hello,
Thank you very much!!! :) We will review it and give it a go. 
About the Zod resolver what I meant to say is that we used an older version of it so to create a temporary resolver for Computed-types.

**Comment by jorisre** [comment]
@YanaRGeorgieva I close your issue because the computed-types resolver is released: https://github.com/react-hook-form/resolvers/releases/tag/v2.5.0
