### ISSUE TITLE
Yup Custom Validation (addMethod)  Bug

### ISSUE THREAD

**Issue by sanzhardanybayev** [react-hook-form/resolvers#163]
**Describe the bug**
Code breaks when adding custom validation logic via **addMethod** function.  

Code returns :
**vendors-node_modules_apollo_client_index_js-node_modules_hookform_resolvers_yup_dist_yup_modu-7f163c.js:9521 Uncaught (in promise) TypeError: Cannot read property 'reduce' of undefined** message. 

**To Reproduce**
Just add custom validation to yup 
```
yup.addMethod(yup.object, 'localeEqual', function (errorMessage) {
    return this.test('locale-equal', errorMessage, function (value) {
        const {path, createError} = this
        return value.kz.length === value.ru.length || createError({path, message: errorMessage})
    })
})
```

**CodeSandbox**
[https://codesandbox.io/s/yup-custom-validation-error-41x1n?file=/src/App.js](https://codesandbox.io/s/yup-custom-validation-error-41x1n?file=/src/App.js)

**Comment by jorisre** [comment]
@sanzhardanybayev Please provide a codesandbox with your issue

**Comment by sanzhardanybayev** [comment]
@jorisre If you remove **34 line**, then this error disappears. This basically means that  **yupValidator** doesn't have a custom method defined via **yup.addMethord**.

**Comment by sanzhardanybayev** [comment]
@jorisre thanks a lot for the help. Much appreciated!

**Comment by sanzhardanybayev** [comment]
@jorisre your support is awesome. So fast. Not so many contributors resolve issues like that this fast. Btw I love your library!

**Comment by jorisre** [comment]
Thanks so much, @sanzhardanybayev  that's awesome to hear!
