### ISSUE TITLE
Yup resolver { stripUnknown: true } schemaOption no longer working

### ISSUE THREAD

**Issue by vanyadymousky** [react-hook-form/resolvers#170]
Hello! My first issue here. First of all thanks for amazing library, it's a real time and life saver tool!
So I've decided to update from resolvers v2.0.0-rc.1 and react-hook-form v6.x to both latest. 

**Describe the bug**
Using stripUnknown via yupResolver no longer working: empty data all the time, no validation working

Using resolvers v2.5.1 and react hook form v7.6.9

**To Reproduce**
Use yupResolver(schema, { stripUnknown: true })

**Codesandbox link (Required)**
https://codesandbox.io/s/brave-ellis-gunj5?file=/src/App.tsx

**Expected behavior**
- no data should be submitted until validation passes
- validation should work correctly
- after validation errors are fixed all data (defined in schema, unknown stripped, obviously) should be submitted correctly

**Screenshots**
![Screenshot 2021-05-28 at 6 39 08 PM](https://user-images.githubusercontent.com/922747/120008793-ff801e80-bfe3-11eb-956a-76dc91f1e1ca.png)

**Desktop (please complete the following information):**

- OS: Mac OS BigSur 11.3 (20E232) (Intel)
- Chrome
- Version 90.0.4430.212 (Official Build) (x86_64)

**Additional context**
Was working fine on react-hook-form v6.x and resolvers v2.0.0-rc.1

**Comment by vanyadymousky** [comment]
Please LMK if I should submit this to react-hook-form repo!

**Comment by jorisre** [comment]
Hi @vanyadymousky 
Thank you for reporting the issue. I've opened a PR to fix it.
Feel free to review it #172

**Comment by jorisre** [comment]
@vanyadymousky Should be fixed in the last version [v2.5.2](https://github.com/react-hook-form/resolvers/releases/tag/v2.5.2)
