### ISSUE TITLE
array field infers strange errors object

### ISSUE THREAD

**Issue by kerosan** [react-hook-form/resolvers#178]
Hi =)
![image](https://user-images.githubusercontent.com/10149363/122047028-51001a00-cde8-11eb-947f-912dd29f9864.png)

this kind of zod schema dont work as expected
```

const schema = z.object({
  title: z
    .string()
    .regex(/^[A-Za-z0-9_]+$/, "wrong pattern")
    .nonempty("Required"),

  someArray: z.array(z.string().nonempty()).min(1)
});

```

   * 1. fill title input
   * 2. press submit
   * 3. fill array input
   * 4. press submit
   * 5. clear array input
   * in console errors changes shape of field someArray from Object to Array
 

https://codesandbox.io/s/gifted-hopper-k4ndp?file=/src/App.tsx

**Comment by bluebill1049** [comment]
hmmm, I don't think we are supporting Zod 3 just yet.

**Comment by kerosan** [comment]
> hmmm, I don't think we are supporting Zod 3 just yet.

same result with version 1.11.11 as on my current project

![image](https://user-images.githubusercontent.com/10149363/122219672-54fb6d00-ceb8-11eb-924b-c2c250f2c71d.png)

**Comment by kerosan** [comment]
if replace `zod` with `yup` then sameArray error works as expected 
https://codesandbox.io/s/eloquent-hellman-qi2iw?file=/src/App.tsx
![image](https://user-images.githubusercontent.com/10149363/122220946-7f015f00-ceb9-11eb-8d76-25a53635b451.png)

pls help 🥲

**Comment by jorisre** [comment]
Hi @kerosan I'll have a look tonight :)

**Comment by jorisre** [comment]
@kerosan sorry for the late reply, I found the problem.

You've to update the `onChange`:
```tsx
onChange={(e) => {
  onChange(e.target.value ? [e.target.value] : []);
}}
```

Because `e.target.value` is `""` when you clear the input and zod validate the following value: `[""]`.

@bluebill1049 Is that normal we can't do the following: `onChange(undefined)`, seems not working with `undefined` 🤔 

Hope it solves your issue :)

**Comment by bluebill1049** [comment]
we don't support `undefined` for the input value.

**Comment by kerosan** [comment]
Thank you very much ✨✨✨
