### ISSUE TITLE
yup test method gets executed, but errors don't get populated

### ISSUE THREAD

**Issue by tsalotaibi** [react-hook-form/resolvers#180]
please find the sandbox below

https://codesandbox.io/s/react-hook-form-yup-fh7v7?file=/src/App.js

the view consists of : 
- name field
- trigger button
- errors

on each input in "name1" field, the test method ➡️ "name1" gets executed and formState errors gets updated.
However, on the test method named ➡️ "form validation", it gets executed, but errors are not updated, unless trigger() is used.

I would like to use test method "form validation" on each field change.

**Comment by jorisre** [comment]
Hi @tsalotaibi 
Please, for your next issue, follow the issue template 🙏🏻  thank you

It doesn't work because your test method `form validation` does not return a `path` so we cannot link the error to a field.

You can solve that by using `createError` of Yup and fill the `path`.

```ts
.test({
    name: "form validation",
    test: (parent, { createError }) => {
      if (parent.name1?.indexOf("hook") >= 0) {
        return createError({ path: "name1", message: "Uhoh!! there is an error!" });
      }
      return true;
    }
  })
```

👉🏻    https://codesandbox.io/s/react-hook-form-yup-forked-k1itv

**Comment by tsalotaibi** [comment]
> Hi @tsalotaibi
> Please, for your next issue, follow the issue template 🙏🏻 thank you

Thank you so much for your support, it's my first github issue, so I apologize, I'll look into template next time. 

> It doesn't work because your test method `form validation` does not return a `path` so we cannot link the error to a field.
> 
> You can solve that by using `createError` of Yup and fill the `path`.
> 
> ```ts
> .test({
>     name: "form validation",
>     test: (parent, { createError }) => {
>       if (parent.name1?.indexOf("hook") >= 0) {
>         return createError({ path: "name1", message: "Uhoh!! there is an error!" });
>       }
>       return true;
>     }
>   })
> ```
> 
> 👉🏻 https://codesandbox.io/s/react-hook-form-yup-forked-k1itv

I can confirm your way is what I was looking for, using createError(). I wasn't aware of it, thanks a bunch! I'm so happy

**Comment by tsalotaibi** [comment]
if there is any better way you can recommend would be much appreciated, 
what I'm trying to achieve for my form with multiple fields, is to check if there is at least 1 field filled to submit.

**Comment by jorisre** [comment]
You can do it by checking fields with `parent`?

**Comment by tsalotaibi** [comment]
> You can do it by checking fields with `parent`?

I apologize for the delay on the response. 

for example, if I have 3 fields that I want to apply validation to. 
and that validation is "at least one field is filled" so that the form can be submitted
it seems to me if I use createError with path <fieldName> this error will not be shown unless the field linked in path is touched.

is it possible to create an error that's not linked to a specific field. or a hidden field for example. and what's the best way to approach it using yup schema. thank you for your support ♥

please find the link below

https://codesandbox.io/s/react-hook-form-yup-forked-7f8w2?file=/src/App.js

**Comment by jorisre** [comment]
Sorry for the late response. Unfortunately, I don't know how you can achieve that.
All errors are linked to a field

**Comment by tsalotaibi** [comment]
> Sorry for the late response. Unfortunately, I don't know how you can achieve that.
> All errors are linked to a field

no problem, thank you for your support.

**Comment by Ribosom** [comment]
Wouldn't following code be a valid workarround? Or has this bad side effects?

```
const [generalError, setGeneralError] = useState();

...

.test("oneChecked", null, (value) => {
      if (value?.checked1 || value?.checked2 || value?.checked3) {
        setGeneralError(null);
        return true;
      }
      // This is a workarround since React Form Hook can link error message only to fields, there are no general errors
      setGeneralError({ message: "At least one module must be enabled" });
      return false;
    });
```

And generalError could then be used to show the error.

**Comment by vishnu3152** [comment]
Hi @jorisre,

I am having a similar issue where the test() function is working fine as expected but the error message is not getting populated in the errors object. I am using YUP 0.30.0 version. deadline is a field which uses Custom component FormikDeadline. 

 deadline: Yup.object().test({
      name: "Invalid days",
      test: function(obj) {
        return obj?.days && (obj.days < 0 || obj.days > 999)
          ? this.createError({
              path: "deadline",
              message: translate(
                `${LOCALE_FILES.CASE_ERRORS}:duration_validation`,
              ),
            })
          : true;
      },
    }),
