### ISSUE TITLE
shouldUseNativeValidation does not work properly with schema resolvers

### ISSUE THREAD

**Issue by ecklf** [react-hook-form/resolvers#182]
**Describe the bug**
Form keeps staying in error state even though it is being changed into a valid state (cannot submit form).
I can confirm this issue for both yup and superstruct so I assume it will cause problems for all resolvers.

**To Reproduce**

1. Use the official schema validation example https://react-hook-form.com/get-started#SchemaValidation
2. Enable shouldUseNativeValidation

**Codesandbox link (Required)**
https://codesandbox.io/s/rhf-bug-hs2ux?file=/src/App.tsx

**Expected behavior**
Native validation message dismisses and form is submittable

**Screenshots**

https://user-images.githubusercontent.com/8146736/124942046-8f65af00-e00b-11eb-9858-b4350df2e031.mov

**Desktop (please complete the following information):**

- OS: macOS 11.4
- Browser Chrome
- Version 91.0.4472.114

**Comment by bluebill1049** [comment]
hey, @jorisre did some quick investigation, I think this problem occurred at the resolver not invoke `setCustomValidty(true);` to clear the error. Could you please take a look at it when you got a chance?

**Comment by jorisre** [comment]
Thanks for reporting the issue. Should be fixed in https://github.com/react-hook-form/resolvers/pull/183

**Comment by ecklf** [comment]
@jorisre I'll test this tomorrow and report back. Thanks in advance for the quick fix.

**Comment by ecklf** [comment]
Tested and working for me 👍🏻
