### ISSUE TITLE
Have error when use with zod resolver

### ISSUE THREAD

**Issue by aspirisen** [react-hook-form/resolvers#186]
**Describe the bug**
I have react-hook-form v6 because of IE support. However, I have an error when i try to add Zod resolver. Is it a bug or i should use special combination of Zod and "@hookform/resolvers/zod" versions?

**To Reproduce**

1. Go to sandbox example
2. Type something in inputs
3. Click submit

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-q3z7p?file=/src/App.js:98-123

**Expected behavior**
Zod should work with react-hook-form

**Screenshots**
![image](https://user-images.githubusercontent.com/3620639/126396230-051b0587-8f22-4eb1-bed7-698a64661a0a.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser chrome
- Version 91

**Comment by bluebill1049** [comment]
That's V7.

**Comment by aspirisen** [comment]
@bluebill1049 does it mean that i can use zod only with react-hook-form v7 ?

**Comment by bluebill1049** [comment]
try reoslver v1.
