### ISSUE TITLE
Using a resolver for one of the validation libraries requires installation of other validation libraries.

### ISSUE THREAD

**Issue by avin-kavish** [react-hook-form/resolvers#20]
I am trying to use yup resolver and it is telling me that package superstruct is missing.

**Comment by bluebill1049** [comment]
which version? and screenshot?

**Comment by avin-kavish** [comment]
`"@hookform/resolvers": "0.0.5"`

I just copied the yup resolver code and bypassed it for now, will post a screenshot when I can. It's happening with CRA + Typescript.

The error is basically the types for `superstruct` cannot be found. Once I installed 'superstruct', there was another error about generic parameters not being passed to superstruct type.

Basically, this type requires at least one generic parameter,

https://github.com/ianstormtaylor/superstruct/blob/01bdd37aef3357ff6296bf1827737ee11719e4b5/src/struct.ts#L9

But here there is none,

https://github.com/react-hook-form/resolvers/blob/ff82c5f442ee0b3a80da989ca36bf984b9d10404/src/superstruct.ts#L46

Will get back to you with screenshots.

**Comment by bluebill1049** [comment]
Do you have any solution in mind?

**Comment by qventura** [comment]
Why not having one package per resolver? 

As far as I can tell, this (https://github.com/react-hook-form/resolvers/blob/master/src/yup.ts) has no dependency to other module form the package.

This is actually how I fixed it in our project, just by extracting the content of `yup.ts` in one of our module.

**Comment by bluebill1049** [comment]
I am seeking some evidence for this issue first before making any adjustments or changes.

**Comment by avin-kavish** [comment]
This is a minimal reproduction: https://github.com/avin-kavish/cra-ts-hook-form-resolver-issue

![image](https://user-images.githubusercontent.com/48435155/86987245-34f50100-c1b3-11ea-995b-54006726b582.png)

**Comment by bluebill1049** [comment]
Thanks @avin-kavish we can definitely try that.

**Comment by bluebill1049** [comment]
I just tried your repo, if you have installed the dependency it's working as expected. 

<img width="549" alt="Screen Shot 2020-07-09 at 5 14 31 pm" src="https://user-images.githubusercontent.com/10513364/87008824-a8286280-c207-11ea-886d-4094363abd20.png">

**Comment by bluebill1049** [comment]
Is this still an issue?

**Comment by dev-araisan** [comment]
I have same issue in yupResolver (v0.0.6).
And I do not want to include other type definition packages.

https://github.com/react-hook-form/resolvers/issues/20#issuecomment-655845379

This solution is lgtm.

**Comment by avin-kavish** [comment]
Will try to open a PR in the next couple of days.

**Comment by bluebill1049** [comment]
> Will try to open a PR in the next couple of days.

That would be awesome! thanks @avin-kavish

**Comment by gcourtemanche** [comment]
importing directly from the dist folder is a good workaround for now:
`import { yupResolver } from '@hookform/resolvers/dist/yup';`

**Comment by davidepalazzo** [comment]
I solved this issue by adding `superstruct` version `0.8.3` to my dependencies.

```yarn add superstruct@0.8.3```

**Comment by bluebill1049** [comment]
> I solved this issue by adding `superstruct` version `0.8.3` to my dependencies.
> 
> `yarn add superstruct@0.8.3`

Thanks, but that's pretty bad... we probably need a better solution for this. any help is appreciated.

**Comment by 10may** [comment]
This a stop-gap method but it works. 
1. Manually comment out all the code that's generating an error.
    
    >(In my case, in `index.d.ts`, I commented out the export for Joi and Superstruct. Similarly, comment out the `joi.d.ts` and `superstruct.d.ts` files)
2. Install [Package-Patch](https://www.npmjs.com/package/patch-package) and generate a patch.
3. Add the patch to the `post-install` script in `package.json`.

That's all, now every time you run `npm i` the patch will be applied automatically, and when there's a new update for the Resolver it will notify you to check if the patch is still needed.

**Comment by bluebill1049** [comment]
> This a stop-gap method but it works.
> 
> 1. Manually comment out all the code that's generating an error.
>    > (In my case, in `index.d.ts`, I commented out the export for Joi and Superstruct. Similarly, comment out the `joi.d.ts` and `superstruct.d.ts` files)
> 2. Install [Package-Patch](https://www.npmjs.com/package/patch-package) and generate a patch.
> 3. Add the patch to the `post-install` script in `package.json`.
> 
> That's all, now every time you run `npm i` the patch will be applied automatically, and when there's a new update for the Resolver it will notify you to check if the patch is still needed.

Thanks for sharing the solution, wondering if there is some way we can prevent this in the lib level.

**Comment by davidepalazzo** [comment]
It looks like `superstruct` in the dev dependencies needs upgrading. Their latest version (`0.10.12`) defines the [Struct class](https://github.com/ianstormtaylor/superstruct/blob/68bdf2dc3a5b2bf4d1bcf12f2a1db98b5035ec21/src/struct.ts#L9) differently from `0.8.3`. That's what is causing the issue in the first place.

**Comment by bluebill1049** [comment]
> It looks like `superstruct` in the dev dependencies needs upgrading. Their latest version (`0.10.12`) defines the [Struct class](https://github.com/ianstormtaylor/superstruct/blob/68bdf2dc3a5b2bf4d1bcf12f2a1db98b5035ec21/src/struct.ts#L9) differently from `0.8.3`. That's what is causing the issue in the first place.

sadness.... https://github.com/react-hook-form/resolvers/issues/16

**Comment by julienfouilhe** [comment]
I was wondering why I didn't have the same problem and while I still don't get why it doesn't break at runtime (maybe webpack tree shaking?) I think it doesn't break the build because I have skipLibCheck set to true in my tsconfig.json (😢 ).

This is going to become a real problem as you keep supporting more libraries.

This package could maybe use Node 14 [`exports`](https://nodejs.org/api/esm.html#esm_subpath_exports) option? It won't fix the issue for users using previous versions, but it should allow to `import { yupResolver } from '@hookform/resolvers/yup'` for everyone running tsc with Node >14

For other versions of Node, one quick fix right now is to do `import ( yupResolver ) from '@hookform/resolvers/dist/yup';`

**Comment by bluebill1049** [comment]
> I was wondering why I didn't have the same problem and while I still don't get why it doesn't break at runtime (maybe webpack tree shaking?) I think it doesn't break the build because I have skipLibCheck set to true in my tsconfig.json (😢 ).
> 
> This is going to become a real problem as you keep supporting more libraries.
> 
> This package could maybe use Node 14 [`exports`](https://nodejs.org/api/esm.html#esm_subpath_exports) option? It won't fix the issue for users using previous versions, but it should allow to `import { yupResolver } from '@hookform/resolvers/yup'` for everyone running tsc with Node >14
> 
> For other versions of Node, one quick fix right now is to do `import ( yupResolver ) from '@hookform/resolvers/dist/yup';`

yea, thanks @julienfouilhe. This one gives me a headache and nightmares right now. hope to find a solution soon. 😖

**Comment by jorisre** [comment]
After playing with rollup config and TS I got the result below : 
![Capture d’écran 2020-09-16 à 18 31 47](https://user-images.githubusercontent.com/7545547/93366133-034f8480-f84b-11ea-86e0-34df91f7459b.png)

No more error :)
This is still in work in progress, needs to test more umd bundle.

**Comment by bluebill1049** [comment]
oh wow, @jorisre you are a legend!

**Comment by clairefro** [comment]
I'm having same error - just using yup but it wants me to add superstruct and joi too 
![image](https://user-images.githubusercontent.com/9841162/93556341-631e5c00-f92d-11ea-8476-3c536a33c37f.png)

I'm using `"@hookform/resolvers": "^0.1.1",`

**Comment by clairefro** [comment]
> I was wondering why I didn't have the same problem and while I still don't get why it doesn't break at runtime (maybe webpack tree shaking?) I think it doesn't break the build because I have skipLibCheck set to true in my tsconfig.json ( ).
> 
> This is going to become a real problem as you keep supporting more libraries.
> 
> This package could maybe use Node 14 [`exports`](https://nodejs.org/api/esm.html#esm_subpath_exports) option? It won't fix the issue for users using previous versions, but it should allow to `import { yupResolver } from '@hookform/resolvers/yup'` for everyone running tsc with Node >14
> 
> For other versions of Node, one quick fix right now is to do `import ( yupResolver ) from '@hookform/resolvers/dist/yup';`

I tried this but get error: 
```
Uncaught Error: Cannot find module '@hookform/resolvers/dist/yup'
    at webpackMissingModule
```

**Comment by bluebill1049** [comment]
hey @jorisre any luck with this fix you were trying. really appreciate your effort here, I think if there is no good solution I may going to try to turn this repo into a mono repo and have each separate packages... it's annoying but i guess there is no other better solution unless if you have some luck with the build.

**Comment by jorisre** [comment]
@bluebill1049 👋🏻 
The new rollup config solve this issue, but I need more time to test all bundle _(umd, cjs(ie11)...)_ but I was slowed down by the issue with ajv.
I think, it will be good tomorrow :)

**Comment by bluebill1049** [comment]
> @bluebill1049 👋🏻
> The new rollup config solve this issue, but I need more time to test all bundle _(umd, cjs(ie11)...)_ but I was slowed down by the issue with ajv.
> I think, it will be good tomorrow :)

oh wow, that's awesome. let's move Avj out the equation for now. I will mostly like to revert that commit until we have a good fix for it.

**Comment by bluebill1049** [comment]
❤️ @jorisre is the hero! please share some appreciation towards his hard work and here is a beta: `@hookform/resolvers@0.2.0-beta.9` and help us to test. ❤️

**Comment by jorisre** [comment]
Thanks @bluebill1049  :)

I've added some examples in a comment https://github.com/react-hook-form/resolvers/pull/60#issuecomment-695337354

**Comment by jorisre** [comment]
For TS users, as a workaround, you can set `skipLibCheck: true` in your `tsconfig.json`

**Comment by qventura** [comment]
Was coming here to mention that `skipLibCheck: true` was the culprit for us :D

Glad you found a proper solution. 👏 @jorisre 

(But also, `skipLibCheck: true` divided our build time by 4... -_-)

**Comment by bluebill1049** [comment]
@qventura i think this issue is resolved by the latest update from @jorisre.
