### ISSUE TITLE
No tree shaking

### ISSUE THREAD

**Issue by avin-kavish** [react-hook-form/resolvers#21]
Won't this cause the whole library to be imported?

https://github.com/react-hook-form/resolvers/blob/ff82c5f442ee0b3a80da989ca36bf984b9d10404/src/yup.ts#L2

**Comment by bluebill1049** [comment]
good pick up! send us a PR please.

**Comment by bluebill1049** [comment]
worth to mention, we only use it for `Type` as well

**Comment by bluebill1049** [comment]
i think this one is duplicated as the other unless you think otherwise. happy to re-open if so.
