### ISSUE TITLE
Import error: 'appendErrors'

### ISSUE THREAD

**Issue by Bobj2018** [react-hook-form/resolvers#22]
I seem to have this issue come up and I have no idea what is causing it. 
```
./node_modules/@hookform/resolvers/dist/index.esm.js
Attempted import error: 'appendErrors' is not exported from 'react-hook-form'.
```

**Comment by bluebill1049** [comment]
which version of react hook form you are using?

**Comment by Bobj2018** [comment]
> which version of react hook form you are using?

4.9.8

**Comment by bluebill1049** [comment]
oh u dont need this package at all. v4 is building with schema validation, this is for v6.

**Comment by premputtegowda** [comment]
I have the same issue for   "react-hook-form": "^6.0.8",
