### ISSUE TITLE
yupResolver raise Types of parameters 'options' and 'options' are incompatible at react-hook-form 7.15.0

### ISSUE THREAD

**Issue by heavenshell** [react-hook-form/resolvers#234]
Hello.

**Describe the bug**

I updated react-hook-form 7.15.0, yupResolver raise following type error messages.

```
Type '<TFieldValues extends Record<string, any>, TContext>(values: UnpackNestedValue<TFieldValues>, context: TContext | undefined, options: ResolverOptions<TFieldValues>) => Promise<...>' is not assignable to type 'Resolver<FormType, object>'.
  Types of parameters 'options' and 'options' are incompatible.
```

Same code with react-hook-form 7.14.2 works fine(no type error).

versions
- react: 17.0.2
- react-hook-form: 7.15.0
- @hookform/resolvers: 2.8.0
- dayjs: 1.10.6
- yup: 0.32.9
- typescript: 4.3.5

**To Reproduce**

1. Go to https://codesandbox.io/s/sad-wilson-rvpvv?file=/src/App.tsx
2. move mouse cursor to line 22 and hover `resolver`
3. Error message popup.

**Codesandbox link (Required)**

https://codesandbox.io/s/sad-wilson-rvpvv?file=/src/App.tsx:456-464

**Expected behavior**

No type error raised, or I want to know how to avoid type error
(react-hook-form 7.14.2 works fine)

**Screenshots**

<img width="816" alt="スクリーンショット 2021-09-07 22 26 31" src="https://user-images.githubusercontent.com/56591/132352670-a527a59d-6840-4c9d-93a8-1e4d0aa21208.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 92.0.4515.159（Official Build） （x86_64）

**Additional context**

None

Thank you!

**Comment by asalahjawava** [comment]
I have the same exact issue but with joiResolver. Suddenly after updating to the latest versions I got that type error. Any updates regarding that issue?

**Comment by heavenshell** [comment]
@jorisre Thank you for fixing, but unfortunately still raise type error in my app....

https://codesandbox.io/s/hardcore-darwin-qusu6?file=/src/App.tsx
<img width="907" alt="スクリーンショット 2021-09-19 13 26 19" src="https://user-images.githubusercontent.com/56591/133915482-3869a6b6-69c6-4328-b116-4d71716c6983.png">

I Updated to 
@hookform 2.8.1 and react-hook-form 7.15.3

@asalahjawava
Does your application works fine?

**Comment by jorisre** [comment]
Thank you @heavenshell for reporting the issue. I'll open a PR.

**Comment by jorisre** [comment]
@heavenshell You can remove `<FormType>` from the `useForm<FormType>`. Types are inferred from the schema.

**Comment by rares-lupascu** [comment]
same issue here ... tried calling useForm without field definitions but this generated an issue with the defaultValues key
![image](https://user-images.githubusercontent.com/3641866/133927724-8f74719c-377d-41e2-8666-04e3100fd0cc.png)

**Comment by jorisre** [comment]
Can you share a codesanbox please ?

**Comment by rares-lupascu** [comment]
https://codesandbox.io/s/dawn-butterfly-klfoq?file=/src/App.tsx

**Comment by rares-lupascu** [comment]
it is because i use yup.object().shape() instead of yup.object()

**Comment by jorisre** [comment]
> it is because i use yup.object().shape() instead of yup.object()

Using `object()` instead of `object().shape()` fix your issue ?

**Comment by rares-lupascu** [comment]
it is like a chain of errors ... after switching to object() ... I get inline errors on the <Controller />
if I have nullable fields ... I will get this error:
![image](https://user-images.githubusercontent.com/3641866/133929244-e6abfc84-8cc0-4417-a993-e05da9a09627.png)

this because In schema the field is nullable

**Comment by toytonic** [comment]
Hi there, in my case the error shows up on the `resolver` option. When I remove the generic form `useForm`, the error disappears from resolver but new errors appear using `<Controller />`. Will try to debug further...

<img width="987" alt="Bildschirmfoto 2021-09-20 um 15 17 32" src="https://user-images.githubusercontent.com/248213/134009791-84581203-f644-45c0-8f5f-de30afdef2bd.png">

**Comment by Mihai-github** [comment]
Hi,
   My current setup is:

"@hookform/resolvers": "^2.8.1",
"react-hook-form": "7.15.4",
"yup": "^0.32.9",
"@types/yup": "^0.29.13"

-----------------------------------------------------------------------------------------------------------------------------

They are the latest versions that are atm available and how I solved the above error is by using the yupResolver with the next generic type yupResolver<yup.AnyObjectSchema>. An example could be the following:

export type TModelRegisterFormInputs = {
    email: string;
    password: string;
    passwordConfirmation: string;
    role: Roles;
    callback?: any;
};

const schema = yup.object().shape({
    email: yup.string().required(),
    password: yup
        .string()
        .required()
        .min(4, 'Password is too short - should be 8 chars minimum.')
        .matches(/[a-zA-Z]/, 'Password can only contain Latin letters.'),
    passwordConfirmation: yup
        .string()
        .required()
        .oneOf([yup.ref('password'), null], 'Passwords must match'),
});

const {
        handleSubmit,
        formState: {errors},
        control,
    } = useForm<TModelRegisterFormInputs>({
        resolver: yupResolver<yup.AnyObjectSchema>(schema),
    });

-----------------------------------------------------------------------------------------------------------------------------

You can also add the defaultValues and I would recommend you to do that. 

Hope it helps you :)

**Comment by Manubi** [comment]
Hi,
I ran into kind of the same problem with the latest packages... 

I am not that familiar with typescript to debug it myself... I feel like moving in circles. 
Can anyone please give a hand. thanks! ❤️ 
![CleanShot 2021-09-23 at 16 48 48@2x](https://user-images.githubusercontent.com/20935138/134529908-76cbedd4-b0fd-4e12-ab57-7068264fbfa7.png)
<img width="784" alt="CleanShot 2021-09-23 at 16 51 05@2x" src="https://user-images.githubusercontent.com/20935138/134530324-87e1163e-4e38-4e8a-a360-938b4857a3b0.png">

![CleanShot 2021-09-23 at 16 49 43@2x](https://user-images.githubusercontent.com/20935138/134530065-aab04c0f-432b-4a44-b38d-d050c2470e6f.png)
<img width="1164" alt="CleanShot 2021-09-23 at 16 50 05@2x" src="https://user-images.githubusercontent.com/20935138/134530136-a6c02701-2704-421b-8e39-b6da2a88b2a2.png">

**Comment by k-maekawa** [comment]
hello there. I ran into the same type error with `@hookform/resolvers: 2.8.1`.
My setup and error is below.

```
"react": "17.0.2",
"typescript": "^4.4.3",
"react-hook-form": "^7.15.4",
"@hookform/resolvers": "^2.8.1",
"yup": "^0.32.9"
```


```
12:54:52.034 | Type error: Type '(values: unknown, context: object, options: ResolverOptions<AssertsShape<Assign<ObjectShape, { email: RequiredStringSchema<string, Record<string, any>>; }>>>) => Promise<...>' is not assignable to type 'Resolver<{ email: string; }, object>'.
-- | --
12:54:52.034 | Types of parameters 'options' and 'options' are incompatible.
12:54:52.034 | Type 'ResolverOptions<{ email: string; }>' is not assignable to type 'ResolverOptions<AssertsShape<Assign<ObjectShape, { email: RequiredStringSchema<string, Record<string, any>>; }>>>'.
12:54:52.034 | Type '{ email: string; }' is not assignable to type 'AssertsShape<Assign<ObjectShape, { email: RequiredStringSchema<string, Record<string, any>>; }>>'.
12:54:52.034 | Property 'email' is incompatible with index signature.
12:54:52.034 | Type 'string' is not assignable to type 'never'.

```

**Comment by athammer** [comment]
Hi, I'm assuming you have enough to go on right now but also wanted to report this also seems to be an issue with Zod.

```
Type '(values: unknown, context: object | undefined, options: ResolverOptions<{ username: string; email: string; password: string; passwordConfirmation: string; }>) => Promise<ResolverResult<{ username: string; email: string; password: string; passwordConfirmation: string; }>>' is not assignable to type 'Resolver<FieldValues, object>'.
  Types of parameters 'options' and 'options' are incompatible.
    Type 'ResolverOptions<FieldValues>' is not assignable to type 'ResolverOptions<{ username: string; email: string; password: string; passwordConfirmation: string; }>'.
      Types of property 'names' are incompatible.
        Type 'string[] | undefined' is not assignable to type '("username" | "email" | "password" | "passwordConfirmation")[] | undefined'.
          Type 'string[]' is not assignable to type '("username" | "email" | "password" | "passwordConfirmation")[]'.
            Type 'string' is not assignable to type '"username" | "email" | "password" | "passwordConfirmation"'.
```
Versions are...
"@hookform/resolvers": "2.8.1",
"react-hook-form": "7.15.0",

Downgrading both packages fixed this.

**Comment by bluebill1049** [comment]
@k-maekawa & @athammer can you share code in a codesandbox?

**Comment by huynd0902** [comment]
Hi. I still get the same error when use react-hook-form(7.16.0) and @hookform/resolvers(2.8.1). Do we have any way to workaround? Please see my codesanbox https://codesandbox.io/s/crazy-knuth-ylcsp?file=/src/App.tsx

**Comment by bluebill1049** [comment]
@huynd0902 ```
const schema = yup.object({
  firstName: yup.string().required()
}).required();
```

**Comment by huynd0902** [comment]
@bluebill1049 So this is a official fix for this issue? Because the previous version I do not need to do this. But yesterday when I checked the docs. It say something like you show above.

**Comment by bluebill1049** [comment]
no, we are considering to revert back `2.8.1`.

**Comment by huynd0902** [comment]
Hopefully, You will fix this issue soon because I really love this library. Thank you.

**Comment by bluebill1049** [comment]
7.16.0 solve the original issue above. the other issue is related to 2.8.1 https://github.com/react-hook-form/resolvers/issues/245

**Comment by Lemaro86** [comment]
Types of parameters 'options' and 'options' are incompatible if you use a few selected elements of array in select.
in "react-hook-form": "7.17.1", and  "@hookform/resolvers": "2.8.1",
