### ISSUE TITLE
Add a Superstruct custom error message handler

### ISSUE THREAD

**Issue by sammkj** [react-hook-form/resolvers#243]
**Is your feature request related to a problem? Please describe.**
Current Superstruct resolver does not allow us to control the error message shown to to end users.

**Describe the solution you'd like**
I propose to add a custom error handler like such:

```js
superstructResolver(schema, errorHandler, resolverOptions)
```

**Describe alternatives you've considered**
None

**Additional context**
None

I can send in a PR if you're okay with this.

**Comment by bluebill1049** [comment]
Don't think it's an feature related to resolver, this is probably what you are looking for: https://github.com/react-hook-form/react-hook-form/discussions/6472

**Comment by sammkj** [comment]
That sounds like a better plan than adding a error handler in the resolver.

**Comment by bluebill1049** [comment]
I will close this issue and let's keep an eye on the RFC. 🙏
