### ISSUE TITLE
[Bug]: Document issue

### ISSUE THREAD

**Issue by iamchathu** [react-hook-form/resolvers#245]
### Version Number

7.15.4

### Codesandbox/Expo snack

https://codesandbox.io/s/sweet-dream-58m9v

### Steps to reproduce

0. Code was copied from the [documentation.](https://react-hook-form.com/get-started#SchemaValidation) 
1. Run `tsc`
2. Or in VSCode in the line it shows the error.

### Expected behaviour

Without any issue.

### Relevant log output

```shell
Type error: Type '(values: unknown, context: object, options: ResolverOptions<AssertsShape<Assign<ObjectShape, { firstName: RequiredStringSchema<string, Record<string, any>>; age: RequiredNumberSchema<number, Record<...>>; }>>>) => Promise<...>' is not assignable to type 'Resolver<IFormInputs, object>'.
  Types of parameters 'options' and 'options' are incompatible.
    Type 'ResolverOptions<IFormInputs>' is not assignable to type 'ResolverOptions<AssertsShape<Assign<ObjectShape, { firstName: RequiredStringSchema<string, Record<string, any>>; age: RequiredNumberSchema<number, Record<string, any>>; }>>>'.
      Type 'IFormInputs' is not assignable to type 'AssertsShape<Assign<ObjectShape, { firstName: RequiredStringSchema<string, Record<string, any>>; age: RequiredNumberSchema<number, Record<string, any>>; }>>'.
        Index signature for type 'string' is missing in type 'IFormInputs'.

  53 |     formState: { errors },
  54 |   } = useForm<IFormInputs>({
> 55 |     resolver: yupResolver(schema),
     |     ^
  56 |   });
  57 |   const onSubmit = (data: IFormInputs) => console.log(data);
  58 | 
error Command failed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
@jorisre i think there is an issue with the latest patch, perhaps we want to revert the resolver change.

**Comment by bluebill1049** [comment]
> Got the same error today. Suspected the "**@hookform/resolvers**" library.
> 
> As a quick fix to rollback the "**@hookform/resolvers**" version from v2.8.1 to v2.8.0
> 
> Here are the comparisons of the updated version. [v2.8.0...v2.8.1](https://github.com/react-hook-form/resolvers/compare/v2.8.0...v2.8.1)

thanks @AlexeyDrobot

**Comment by bluebill1049** [comment]
@julienfouilhe would you be able to take a look at this one, i think it's introduced by the last PR.

**Comment by julienfouilhe** [comment]
I think that a first problem was releasing this change as a patch. It should have at least been a minor. 

I may have been at fault for not stressing the importance of the changes of my PR, but now the yup resolver correctly infers the FieldValues from the schema using `yup.InferType`.

Which means the type passed to `useForm` needs to match the type inferred from the schema.

But the type inferred from:
```typescript
yup.object().shape({
  firstName: yup.string().required(),
  age: yup.number().positive().integer().required(),
})
```

Resolves to:
```typescript
type IFormInputs = {
    [x: string]: never;
    firstName: string;
    age: number;
}
```

And it does not match the custom `IFormInputs` in your example. 

While:
```typescript
yup.object({
  firstName: yup.string().required(),
  age: yup.number().positive().integer().required(),
})
```

Resolves to the correct type:
```typescript
type IFormInputs = {
    firstName: string;
    age: number;
}
```

This just shows that yup typings are far from ideal.

Examples should be updated to show this.

**Comment by bluebill1049** [comment]
Thanks @julienfouilhe no one's fault here :) I do appreciate your contribution and help. we are all trying to make this works for everyone. 

Take a look at this codesandobx: https://codesandbox.io/s/react-hook-form-validationschema-v7-ts-eb41q?file=/src/index.tsx the issue is probably more obvious, switching from 2.8.1 to 2.8.0

**Comment by julienfouilhe** [comment]
@bluebill1049 In this example, changing the schema to:

```typescript
const SignupSchema = yup
  .object({
    firstName: yup.string().required(),
    lastName: yup.string().defined(),
    age: yup.number().required().positive().integer(),
    website: yup.string().url().defined()
  })
  .required();
```

Works. Which actually fixes potential problems since not using `defined` or `required` means `undefined` is a valid value.

Also now you don't have to pass the type to useForm as it should be correctly inferred from the schema.

So using the following code is enough and will show problems with the schema.

```typescript
useForm({
  resolver: yupResolver(SignupSchema)
});
``` 

It sure is stricter, but definitely safer!

**Comment by bluebill1049** [comment]
Thanks @julienfouilhe I do think this is a breaking change to existing users, maybe we roll it back for now and work out something to ease the breaking part. Let me know your thoughts as well @jorisre

**Comment by julienfouilhe** [comment]
@bluebill1049 It might break a lot of projects yes. I had to fix a bunch of yup schemas in my projects myself.

Yes we can revert, but 2.8.0 is not compatible with the latest react-hook-form.

**Comment by bluebill1049** [comment]
thanks for understanding @julienfouilhe could you share a codesandbox with the latest react-hook-form issue with resolver?

**Comment by bluebill1049** [comment]
related issue: https://github.com/react-hook-form/resolvers/issues/234

**Comment by iamchathu** [comment]
Better to update documentation to reflect this would be seems good.

**Comment by bluebill1049** [comment]
The doc is fine, I think we will have to revert and work out a better solution.

**Comment by iamchathu** [comment]
What will be the future way of setting yup schema?

```ts
const SignupSchema = yup
  .object({
    firstName: yup.string().required(),
    lastName: yup.string().defined(),
    age: yup.number().required().positive().integer(),
    website: yup.string().url().defined()
  })
  .required();
```

or 

```ts
const SignupSchema = yup
  .object().shape({
    firstName: yup.string().required(),
    lastName: yup.string().defined(),
    age: yup.number().required().positive().integer(),
    website: yup.string().url().defined()
  });
```

**Comment by bluebill1049** [comment]
they both should work, resolver shouldn't dictate schema syntax.

**Comment by julienfouilhe** [comment]
Why though @bluebill1049? Isn't that what it's for? Checking the syntax? If the schema accepts undefined values, shouldn't you see this in the type of field values, so that you can handle the undefined case, or change your schema accordingly?

**Comment by bluebill1049** [comment]
@julienfouilhe what do you mean by `undefined`?

```
const SignupSchema = yup
  .object().shape({
    firstName: yup.string().required(),
    lastName: yup.string().defined(),
    age: yup.number().required().positive().integer(),
    website: yup.string().url().defined()
  });
```

this schema should fail with `undefined` right at run time? Do you mean the schema determined that the value type still allowed `undefined` or `object`? It's a bit confusing to me because the schema will do a run-time check against an object. If that's not the case I am happy to update the doc, but if this gets me I worried it would confuse other devs as well.

**Comment by julienfouilhe** [comment]
Yes yup is extremely confusing. If you don't use required or defined then it will not return an error if the value is undefined.

With 2.8.1, you know that it can be undefined and need to handle that (by changing your either your schema, or your custom field values type if you have one, or the code that uses the form values). If you don't then you'll have a typescript error.

With 2.8.0, you can set your own type that is in no way related to the schema that will perform checks at runtime. For instance you can pass a yup schema that will check that your form has a string field, and then use a FieldValues type that says the field is a number. The resolver will fail at runtime when you could have had typescript errors. Hence why I think it's better with 2.8.1

**Comment by bluebill1049** [comment]
thanks for the explanation @julienfouilhe i will update the doc to reflect that first and we can go from there.

**Comment by julienfouilhe** [comment]
Last clarification. This used to pass:

```typescript
const form = useForm<{ field: number }>({
  resolver: yupResolver(yup.object({ field: yup.string() })),
  defaultValue: { field: 1 }
})
```

While with 2.8.1 it will show an error showing that the schema is incompatible with the manually specified type. If you do 

```typescript
const form = useForm({
  resolver: yupResolver(yup.object({ field: yup.string() })),
  defaultValue: { field: 1 }
})
```

It will also show an since the schema is incompatible with the default values! 🎉

**Comment by vtrphan** [comment]
so what's the solution? rolling back to 2.8.0 and wait for a fix, or what do i have to change?

**Comment by bluebill1049** [comment]
follow the updated doc for now: https://react-hook-form.com/get-started#SchemaValidation @vtrphan

**Comment by julienfouilhe** [comment]
@bluebill1049 Just a thought, but maybe we can export both a strictly typed resolver and a less strict resolver? They would be the same code, the non strictly typed version could just be typecasted to "any" just like before.

**Comment by wroughtec** [comment]
Seems to cause an issue when using `when`:
https://codesandbox.io/s/when-validation-4dux1?file=/src/index.tsx

ie remove shape you get `Cyclic dependency, node was:"max"`

**Comment by bluebill1049** [comment]
@wroughtec adding the `.required()` fix the issue as well.

```
const SignupSchema = Yup.object().shape(
  {
    min: Yup.number()
      .min(0)
      .max(20)
      .when("max", {
        is: (val) => val,
        then: Yup.number().required().max(Yup.ref("max"))
      }),
    max: Yup.number()
      .min(0)
      .max(20)
      .when("min", {
        is: (val) => val,
        then: Yup.number().required().min(Yup.ref("min"))
      })
  },
  [["min", "max"]]
).required();
```

**Comment by wroughtec** [comment]
great think safer to go down that route then :)

**Comment by MylesWardell** [comment]
Similar issue with Joi resolver. Does anybody know a stable version I can revert to? 
![image](https://user-images.githubusercontent.com/55673046/136132176-6306b627-3290-448c-92d0-9cf47f98fc31.png)

**Comment by bluebill1049** [comment]
can you share a codesandbox @MylesWardell

**Comment by MylesWardell** [comment]
@bluebill1049 First time writing a sandbox for a bug 
https://codesandbox.io/s/joi-resolver-bug-k5885

I noticed while trying to mimic my work environement that if you dont call joiResolver through a function everything works as intended. Only through a function does it fail. Thoughts?

**Comment by jorisre** [comment]
Hey Guys,

Sorry for the delay, the last version of resolvers should fix that issue. If you've a different error, please open a new issue.

**Comment by bluebill1049** [comment]
> @bluebill1049 Just a thought, but maybe we can export both a strictly typed resolver and a less strict resolver? They would be the same code, the non strictly typed version could just be typecasted to "any" just like before.

We will revert this feature for now, and make it a potential break change for v3. Thanks very much for your contribution by the way.

**Comment by Toavina23** [comment]
Hello I am facing this issue again when passing a the control object from useForm as a prop to the Controller component.
Here is the error: 
 "Type 'Control<FormValues, any>' is not assignable to type 'Control<FieldValues, any>'.  
The types of '_options.resolver' are incompatible between these types.

**Comment by indiejoseph** [comment]
Also getting type error:
```
Type 'Control<{ email: string; }, any>' is not assignable to type 'Control<FieldValues, any>'.
  The types of '_options.resolver' are incompatible between these types.
    Type 'Resolver<{ email: string; }, any> | undefined' is not assignable to type 'Resolver<FieldValues, any> | undefined'.
      Type 'Resolver<{ email: string; }, any>' is not assignable to type 'Resolver<FieldValues, any>'.
```

**Comment by indiejoseph** [comment]
just found out I forgot to assign the `name` prop into <Controller />, @Toavina23 see is it your case.

**Comment by Toavina23** [comment]
Yep, I also forgot it and already solved mine,
but I still have no Idea about how does this error related to the name prop being forgotten

**Comment by Under-Warz** [comment]
hi, same problem here with version 3.1.1, I have to set all my fields optional in order to go through the error :\

**Comment by cruzluna** [comment]
I had a similar issue. The fix was to make the array of string required, ie: 
```typescript
  tags: array().of(string().required()).required(),
  links: array().of(string().required()).required(),
```

**Comment by Nilegfx** [comment]
this issue forced me to change from yup to zod in my new project. the issue still exist in @hookform/resolvers@3.3.2

**Comment by cruzluna** [comment]
> this issue forced me to change from yup to zod in my new project. the issue still exist in @hookform/resolvers@3.3.2

What is your schema that is producing the error?

**Comment by robert-ovens** [comment]
This problem appears to only occur when when the type definition of the contains a required field.

```typescript
interface Person {
  firstName: string;
  lastName?: string;
}
const person: Person = {
  firstName: "Sally",
  lastName: "Person",
};

const schema = yup
  .object<Person>({
    firstName: yup.string().required(),
    lastName: yup.string().required(),

  })
  .required();

const form = useForm<Person>({
  defaultValues: person,
  resolver: yupResolver(schema),
});
```

Revising the Person interface to 
```typescript
interface Person {
  firstName?: string;
  lastName?: string;
}
```
and the compile error disappears. 

This is not a suitable workaround in my case, as I am consuming a generated type definition. Removing the type argument to `UseForm` also solves the issue. It borks if you provide nothing, but supplying `any` appears to be sufficient.

```typescript
const form = useForm<any>({
  defaultValues: person,
  resolver: yupResolver(schema),
});
```

**Comment by cruzluna** [comment]
@robert-ovens you marked last name as required in the schema but optional in the interface. These are conflicting.
