### ISSUE TITLE
yupResolver raise `Types of parameters 'options' and 'options' are incompatible` 7.17.4

### ISSUE THREAD

**Issue by heavenshell** [react-hook-form/resolvers#258]
**Describe the bug**

Hello, Thank you for fixed #234, but I Update to `react-hook-form v7.14.4`,
unfortunately raised `Types of parameters 'options' and 'options' are incompatible`.

v7.17.1 is OK(not raise type error)
v7.17.2~v.17.4 is raise type error

versions
- react: 17.0.2
- react-hook-form: 7.17.4
- @hookform/resolvers: 2.8.2
- dayjs: 1.10.7
- yup: 0.32.11
- typescript: 4.3.5

**To Reproduce**

Here is codesandbox example(My application is more complex...)
https://codesandbox.io/s/hardcore-darwin-qusu6?file=/src/App.tsx

1. Go to https://codesandbox.io/s/hardcore-darwin-qusu6?file=/src/App.tsx
2. Click on `src/App.tsx`
3. Scroll down to line 30 and hover cursol to `resolver`

```
(property) resolver?: Resolver<FormType, object> | undefined
Type '<TFieldValues extends Record<string, any>, TContext>(values: UnpackNestedValue<TFieldValues>, context: TContext | undefined, options: ResolverOptions<TFieldValues>) => Promise<...>' is not assignable to type 'Resolver<FormType, object>'.
  Types of parameters 'options' and 'options' are incompatible.
    Type 'ResolverOptions<FormType>' is not assignable to type 'ResolverOptions<{ name: string; dateRange: [{ clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; format: {}; ... 12 more ...; locale: {}; }, { ...; }]; }>'.
      Type '[{ clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; format: {}; diff: {}; valueOf: {}; unix: {}; ... 9 more ...; locale: {}; }, { ...; }]' is not assignable to type '[Dayjs, Dayjs]'.
        Type '{ clone: {}; isValid: {}; year: {}; month: {}; date: {}; day: {}; hour: {}; minute: {}; second: {}; millisecond: {}; set: {}; get: {}; add: {}; subtract: {}; startOf: {}; endOf: {}; format: {}; diff: {}; valueOf: {}; unix: {}; ... 9 more ...; locale: {}; }' is not assignable to type 'Dayjs'.
          Types of property 'clone' are incompatible.
            Type '{}' is not assignable to type '() => Dayjs'.
              Type '{}' provides no match for the signature '(): Dayjs'.ts(2322)
```

**Codesandbox link (Required)**
https://codesandbox.io/s/hardcore-darwin-qusu6?file=/src/App.tsx:771-779

**Expected behavior**

No type error or I want to know how to fix.

**Screenshots**

<img width="696" alt="スクリーンショット 2021-10-15 19 03 23" src="https://user-images.githubusercontent.com/56591/137470535-14de8645-3eda-46bf-b831-9adde1ac01ec.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 94.0.4606.81(Official Build) (x86_64)

**Additional context**

CI also raised error
https://github.com/react-hook-form/resolvers/pull/256/checks?check_run_id=3868189758#step:5:13

Thank you!

**Comment by jorisre** [comment]
Hi,
It's a design limitation, we recommend to pass simpler object than a Dayjs or moment object. Can you pass a date string or timestamp number instead ?

I also recommend to use `yup.object({})` instead of `yup.object().shape({})`

**Comment by heavenshell** [comment]
Thank you for replay and sorry for late response.

> It's a design limitation

Ok, I understand.
But please write `design limitation` to document.
Only primitive type(such as string, number) can use?

> Can you pass a date string or timestamp number instead ?

Maybe I can. I'll try.

**Comment by bluebill1049** [comment]
It was marked as a design limitation in the main repo as well: https://github.com/react-hook-form/react-hook-form/issues/6523

**Comment by akomm** [comment]
So basically a feature update BC break. Thanks, I'm going to rewrite all my code so it works with the resolver. Going to remove all my branded types. :+1:
