### ISSUE TITLE
Question: How to do multiple checks for password validation with Yup and RFH?

### ISSUE THREAD

**Issue by sngreg** [react-hook-form/resolvers#26]
I am wondering if there is a way with yup and yupResolver with RHF to do something similar to this:

https://codesandbox.io/s/eager-bush-dfl5t

Basically using this code when a user starts typing into the password field you get separated booleans for each validation criteria which allows you to build an interactive component such as:

<img width="397" alt="Screen Shot 2020-07-13 at 7 40 26 PM" src="https://user-images.githubusercontent.com/6288003/87364121-c3b1a700-c540-11ea-9ee5-9cf8d86c89a4.png">

Code that I have been playing around with:

```
....
import { yupResolver } from '@hookform/resolvers';

const passwordSchema = yup.object().shape({
  password: yup
    .string()
    .required()
    .min(8)
    .matches(RegExp('(.*[a-z].*)'), 'Lowercase')
    .matches(RegExp('(.*[A-Z].*)'), 'Uppercase')
    .matches(RegExp('(.*\\d.*)'), 'Number')
    .matches(RegExp('[!@#$%^&*(),.?":{}|<>]'), 'Special'),
});

  const { register, handleSubmit, errors, formState, getValues } = useForm({
    resolver: yupResolver(
      passwordSchema
    ),
    criteriaMode: 'all',
    reValidateMode: 'onChange',
    mode: 'onChange',
  });
....
```

Which results in:

<img width="579" alt="Screen Shot 2020-07-13 at 7 47 39 PM" src="https://user-images.githubusercontent.com/6288003/87364478-c2cd4500-c541-11ea-94d7-836389a70ca8.png">

I was hoping to have types returned like the coding sample so I can flag the realtime critera.

Any help or things in yup would be super helpful.

Thanks!

**Comment by bluebill1049** [comment]
we do actually support `validateAllFieldCriteria` https://github.com/react-hook-form/resolvers/blob/master/src/yup.ts otherwise it would be a bug if it's not working.

**Comment by sngreg** [comment]
Thanks @bluebill1049  for the quick reply. Going to try that quickly now to see if that is what I am looking for. Will post here and close out if it works :)

**Comment by sngreg** [comment]
I am pretty new to RFH and Yup looking at the types, I am not seeing `validateAllFieldCriteria`

```
// Not Correct
 resolver: yupResolver(
      passwordSchema,
      { validateAllFieldCriteria: true }
    ),```

This is what it is expecting:

```export declare const yupResolver: <TFieldValues extends Record<string, any>>(schema: Yup.ObjectSchema, options?: Yup.ValidateOptions) => Resolver<TFieldValues, object>;```

```
export interface ValidateOptions {
    /**
     * Only validate the input, and skip and coercion or transformation. Default - false
     */
    strict?: boolean;
    /**
     * Return from validation methods on the first error rather than after all validations run. Default - true
     */
    abortEarly?: boolean;
    /**
     * Remove unspecified keys from objects. Default - false
     */
    stripUnknown?: boolean;
    /**
     * When false validations will not descend into nested schema (relevant for objects or arrays). Default - true
     */
    recursive?: boolean;
    /**
     * Any context needed for validating schema conditions (see: when())
     */
    context?: object;
}
```

I will do some more digging / googling, but just wanted. to let you know what I was trying.

**Comment by Mathius17** [comment]
Hey @sngreg! I think if you add `abortEarly` to the options when declaring the resolver it might solve your problem. It is `true` by default.

```
resolver: yupResolver(passwordSchema, { abortEarly: true })
```

I haven't actually tested it but it seems like the solution to me.

**Comment by sngreg** [comment]
@Mathius17  - Thanks for the suggestion. I did set it to false and am experiencing the same result above, where the password errors will trigger, but only shows one of each "type" so for reference: I have 4 different .matches regex but it only fires the first one.

<img width="579" alt="Screen Shot 2020-07-13 at 7 47 39 PM" src="https://user-images.githubusercontent.com/6288003/87423832-f2fbfe80-c5a8-11ea-8dcf-7c33067b9ec8.png">

**Comment by Vandell63** [comment]
Hi @sngreg  so yes for the `validate all criteria` it is the `criteriaMode` need to be 'all'. 
If you abortEarly to true you will only get the first error Property in your schema
If you abortEarly to false you will get all yup errors from every properties.
So your question is more about many errors for only one props, and after investigate it yup only send you back the first error you got from your schema, and if it successfull, it will take the next one ( the next yup validation of the same property ) .
And so yup don't this feature that give you all props errors in an array. 
Infortunetly -> https://github.com/formik/formik/issues/243 there is no change today for this :/.

**Comment by sngreg** [comment]
Thanks @Vandell63  - I was afraid this might be the case after all the digging I was doing. I appreciate everyone jumping into this discussion.

**Comment by Vandell63** [comment]
You welcome, i think you can close it, and as soon as yup want to add this feature, i'm pretty sure that @bluebill1049  will be already on :) .

**Comment by sngreg** [comment]
@Vandell63  @bluebill1049  - Thank you again for the really quick responses. 

Vandell63 - I opened an issue on yup (https://github.com/jquense/yup/issues/975) which it looks like this is not a problem in yup. Here is a very quick sample that shows ALL the errors when we call yup.validate. 

https://codesandbox.io/s/nice-brown-61nzg

Notice in the console:

```
Error - password is a required field,password must be at least 8 characters,Lowercase,Uppercase,Number,Special ```

I believe this something with how RHF or the resolver handles these errors and makes the object to return

Thoughts?

**Comment by Vandell63** [comment]
@sngreg  Im so sorry to lead you to the bad way. Effectively yup return an array of all errors ( log on codesandbox an Error class lead me to a weird log  ). 
I continue investigate into the yup resolver code. 
I already started this -> https://codesandbox.io/s/yup-resolver-with-errors-array-pvph7?file=/src/resolver.js

**Comment by sngreg** [comment]
@Vandell63  no worries at all! Glad we are able to narrow this down. Thanks for starting that, i have narrowed it down to the `parseErrorSchema` method. It looks like that is where the "BUG" or "FEATURE REQUEST" would be. It is grouping and only saving one of each "type" in the "types" node. 

EX:

Parse Inner Reduce ----  
PATH: password MESSAGE: password is a required field TYPE: required
PATH: password MESSAGE: password must be at least 8 characters TYPE: min
PATH: password MESSAGE: Lowercase TYPE: matches
PATH: password MESSAGE: Uppercase TYPE: matches
PATH: password MESSAGE: Number TYPE: matches
PATH: password MESSAGE: Special TYPE: matches

This is the start of the inner.reduce, but after what the function returns is:

<img width="579" alt="Screen Shot 2020-07-13 at 7 47 39 PM" src="https://user-images.githubusercontent.com/6288003/87481486-692a5080-c5fd-11ea-9188-a68271d50788.png">

Which only has one of the "Matches" TYPES

**Comment by sngreg** [comment]
I believe this is where the error is happening, it only appends the latest error of a type:

https://github.com/react-hook-form/resolvers/blob/master/src/yup.ts#L15

Looking at what this does https://github.com/react-hook-form/react-hook-form/blob/173e0c1740108d23101681d79000708c5a2b7778/src/logic/appendErrors.ts#L21

It overwrites the type `match` with the latest error in the array. 

I tested this out adding a random number to type in the resolver and it. "solved" the issue.

I am not sure the best approach to where a permeant should live, is appendError in RFH functioning as intended (not to duplicate types) or is this something we should fix in the resolver?

Thoughts?

**Comment by bluebill1049** [comment]
thanks for the invitation @sngreg i haven't got time to look too deep on this one, do you have any fix in mind since you already traveled this deep into the code.

**Comment by sngreg** [comment]
Thanks Bill! I don’t have a fix in mind. I know why it is broken but not sure how or where to fix. I know it is the appendError in RHF code. 

One thought if we are fixing in resolvers can we build a unique list before appending them, or build our own error list.

**Comment by Vandell63** [comment]
@sngreg  Yes this is the case for the `appendError`, it replace the previous one every time. In my code sandbox link you can see in the resolver file that i have remove the `appendError` to return the first error if `validateAllCriteria` is set to `firstError`. And now i will work on the `all` from validate all criteria to show you instead a list of error with the same shape of the `firstError`.
```
[path]: validateAllFieldCriteria
                  ? // RETURN AN ARRAY OF MESSAGE AND TYPE INSTEAD if it is TRUE
                    [...(previous[path] || []), { message, type }]
                  : { ...previous[path], message, type }
```
So if you switch to `all` you will get the error list directly. But i have to investigate the goal of the function `transformToNestObject` to make it working properly you got it ?

**Comment by bluebill1049** [comment]
Thanks, @Vandell63 for all the support and investigation. I am really appreciated it here.

**Comment by Vandell63** [comment]
@bluebill1049  is totally normal, you are really active and we all like this. And i have to switch from formik to this library ( performance reason ). And no way for me i stay here.
I need to know how `react-hook-form` handle the yup resolver behind because instead Object error he will get an array of error so it should impact the `react-hook-form` behind. I continue

**Comment by Vandell63** [comment]
@bluebill1049 & @sngreg  I got a working example of @sngreg needs on 
- https://codesandbox.io/s/yup-resolver-with-errors-array-pvph7?file=/src/index.js
Switch from "all" or "firstError" gave you one or many errors. Must be documented.
@bluebill1049  I don't know if it follow the mindset of what you call the `criteriaMode` ?
The changes: 
- Remove the transformToNestObject function
- Remove the appendErrors
- Refactor the appendErrors to be : 
```
                [path]: validateAllFieldCriteria
                  ? [...(previous[path] || []), { message, type }]
                  : { ...previous[path], message, type }
```
Et voilà. But im pretty sure that it will work for this issue. I don't know how it could impact into the `react-hook-form` library. To be tested.

**Comment by bluebill1049** [comment]
yes i think we can remove: transformToNestObject. can you create a PR and let's do some further testing and see if this impact other stuff or not.

**Comment by Vandell63** [comment]
@bluebill1049 same here i will give a try :)

**Comment by sngreg** [comment]
@Vandell63  - Thank you so much, taking a look now to see what you made and trying it out in my application.

**Comment by sngreg** [comment]
@bluebill1049 @Vandell63  This is exactly what I needed. Things are looking good in my application, but I think the way we have this now will introduce a breaking change for people that have coded for the old type:

Now all the fields in the schema return an array of errors (GREAT!) but prior to this change their was the top level error exposed and then an object called types to. see the "partial / broken" list

BEFORE:
<img width="579" alt="Screen Shot 2020-07-13 at 7 47 39 PM" src="https://user-images.githubusercontent.com/6288003/87546239-3a50c080-c677-11ea-97d7-f345427c5756.png">

AFTER:
<img width="772" alt="Screen Shot 2020-07-15 at 8 41 47 AM" src="https://user-images.githubusercontent.com/6288003/87546250-3de44780-c677-11ea-91b8-84309f52eb31.png">

So if anyone is display label / field messages for their form it will break because `errors.lastName.message` now has to be `errors.lastName[0].message`

One thought to enhance this change and not introduce it as a breaking change would be an object like this

`{
  email:
    message: 'Email  is Required'
    type: 'min'
    errors: [
      {
        message: 'Email is Required'
        type: 'min'
      },
      {
        message: 'Email is not valid format'
        type: ''
      }
    ]
}`

**Comment by bluebill1049** [comment]
Thanks guys. I think we need to keep the same object shape, otherwise, it's a breaking change not just the resolve but he core as well: 
![image](https://user-images.githubusercontent.com/10513364/87547058-e33a0280-c6ed-11ea-8a3c-a2882b202c5a.png)

**Comment by sngreg** [comment]
@bluebill1049 - So with the thoughts of keeping the object the same, I agree.

We run into issues using the type as the key in `types` object. Do you think we can keep the object the same and then add on just an `errors` array or would your thought be to make the keys unique in the `types` key / value pair like this:

matches-1: 'Special'
matches-2: ' Number'
...

**Comment by Vandell63** [comment]
Hey after a diving session into react hook form i didnt find any deps with the props `types` from the resolver into the `core` so it could be used easily. It was not documented and maybe could be a soft breaking change for any user which used the types props in errors ( i don't think many of them ).
I have updated the code -> https://codesandbox.io/s/yup-resolver-with-errors-array-pvph7?file=/src/App.js
And it still do the job. What you think about this @bluebill1049  @sngreg  ?

**Comment by sngreg** [comment]
@Vandell63 - this looks great to me! I like that we keep the same object type and just repurpose the types array with “all” the validation criteria. 

I am new to this repo, but I think you should make a PUll request with this code and see what @bluebill1049  thinks!

I appreciate all the time, intelligent discussion, and collaboration we all put towards this feature.

**Comment by Vandell63** [comment]
@sngreg  thx same feeling.
I can propose at the same time the `context` at the second argument which is not inject into resolver when user fill the object context into the resolver object ( and not in the yupResolver option ) -> https://github.com/react-hook-form/react-hook-form/issues/2222#issuecomment-658622204 sounds good to you @bluebill1049 with the code change ?

**Comment by bluebill1049** [comment]
yea totally! thanks for all the investigations. looking forward to your PRs, this is going to help some many developers.

**Comment by bluebill1049** [comment]
> Thanks guys. I think we need to keep the same object shape, otherwise, it's a breaking change not just the resolve but he core as well:
> ![image](https://user-images.githubusercontent.com/10513364/87547058-e33a0280-c6ed-11ea-8a3c-a2882b202c5a.png)

@Vandell63 if we can try to have the same structure is the best, then they are consistent and no breaking changes. 🙏

**Comment by sngreg** [comment]
@bluebill1049 i understand not changing the structure for breaking changes, I guess what would recommend we can do to keep the same structure. Right now in the types object the key has to be unique. This will be a problem with having 4 validation criteria with the key “match”.

So do we appended a number to the end of the key or do we keep the same object, but just add another item to the object called “errors” which is the list of all the errors like @Vandell63 created?

**Comment by bluebill1049** [comment]
yes, perhaps we can return a match object?

```
match: {
   xxx: 'xxx',
   yyy: 'yyy',
}
```

it's probably easier to `Type` as well.

**Comment by sngreg** [comment]
@bluebill1049  - I am struggling figuring out how we will want to key the `matches` object

Real Example:

```
{
  message: "Special"
  type: "matches"
  types: {
    required: "password is a required field"
    min: "password must be at least 8 characters"
    matches: {
      
    }
  }
}
```

So if we are going to have the message be the key and the stringified value, that can be a sentence. Not sure that would be a great key.

The only thing I can think of is something like

```
matches {
  message1: "Special Character needed" // Dynamic message
  message2: "Uppercase Character needed"
  message3: "Lowercase character needed"
...
}
```

Thoughts? I still think we should do something like this

```
{
  message: "Special"
  type: "matches"
  types: {
    required: "password is a required field"
    min: "password must be at least 8 characters"
    matches: "Special"
  }
  allErrors: [
    {
      message: 'Special',
      type: 'matches'
    },
    {
      ...
     }
  ]
}
```

**Comment by bluebill1049** [comment]
doesn't `matchees` return `type` and `message`?

**Comment by bluebill1049** [comment]
I don't think we will go with `allErrors`.

**Comment by sngreg** [comment]
So the first error is exposed at the top level:

```
{
  message: "Special"
  type: "matches"
....
```

Then the object has a `types` key which the current way uses the `type` as the key and the `message` as a value. The problem we are having is that `type` matches has multiple messages, so we can't use the `type` as the key.

What about something like 

```
{
  message: "Special"
  type: "matches"
  types: {
    required: "password is a required field"
    min: "password must be at least 8 characters"
    matches: [ // type
      'Special character needed', // message
      'Uppercase needed' // message
      'Lowercase needed' // message
      'Number needed'  // message
    ]
  }
}

**Comment by bluebill1049** [comment]
> So the first error is exposed at the top level:
> 
> ```
> {
>   message: "Special"
>   type: "matches"
> ....
> ```
> 
> Then the object has a `types` key which the current way uses the `type` as the key and the `message` as a value. The problem we are having is that `type` matches has multiple messages, so we can't use the `type` as the key.
> 
> What about something like
> 
> ```
> {
>   message: "Special"
>   type: "matches"
>   types: {
>     required: "password is a required field"
>     min: "password must be at least 8 characters"
>     matches: [ // type
>       'Special character needed', // message
>       'Uppercase needed' // message
>       'Lowercase needed' // message
>       'Number needed'  // message
>     ]
>   }
> }
> ```

Oh I see, sorry I am missing some content here (without careful read), you are trying to return multiple messages with a single type. perhaps we should have a new `messages` then.

**Comment by bluebill1049** [comment]
```
test: {
  type: 'match',
  messages: [xxx, yyy]
}
```

**Comment by sngreg** [comment]
Yes, I think we can just return the array of messages in the types object.

What is "test" in your example? Is that a new key to the object?

If we want to keep the object consistent I do like the idea of what I proposed above where the `types` key is an object that has the `type` as the key and an [] of messages

**Comment by bluebill1049** [comment]
```
{
  messsage: '',
  messages:  [ 
      'Special character needed', // message
      'Uppercase needed' // message
      'Lowercase needed' // message
      'Number needed'  // message
  ],
  type: "matches"
}
```

This is what i meant.

**Comment by sngreg** [comment]
II see what you mean, just to add more context, the top level of 

```
{
 // This is just the FIRST error for the field, so it could be any `type` (min, required, matches)  -- This should NOT change
  message: '',
  type: "matches"

  // this is a key value pair where type is the key and the value is the message (we should change value to array of message)
  types: {
  }
}
```

**Comment by bluebill1049** [comment]
```
{
  message: '' // single message
  messages: [] // mutilple message for single type
  type: '', // single type
  types: {} // multiple types for single error and message
}
```

**Comment by sngreg** [comment]
Okay, I like this, I just dont think we will be able to do 

`  messages: [] // multiple message for single type`

The reason being at the top level which you posted above, the `type` object is just the first error message so for a password in the schema:

CURRENT
```
{
  message: "password is a required field"
  type: "required"
  types: {
    required: "password is a required field"
    min: "password must be at least 8 characters"
    matches: "Special character needed" // only returns 1
  }
}
```

Your SUGGESTION:

```
{
  message: "password is a required field"
  messages: [
    'Special character needed', // Type = Match
    'Uppercase needed' // Type = Match
    'Lowercase needed' // Type = Match
    'Number needed'  // Type = Match
    'password is a required field' // Type = required
    'password must be at least 8 characters' // Type = min
  ]
  type: "required"
  types: {
    required: "password is a required field"
    min: "password must be at least 8 characters"
    matches: "Special character needed" // only returns 1
  }
}
```

Another SUGGESTION:

Make the messages: [] an object with message and type

```
{
  message: "password is a required field"
  messages: [
    {
      message: 'Special character needed'
      type: matches
    },
    {
      message: 'Uppercase needed'
      type: matches
    },
    {
      message: 'Lowercase needed'
      type: matches
    },
    {
      message: 'Number needed'
      type: matches
    },
    {
      message: 'password is a required field'
      type: required
    },
    {
      message: 'password must be at least 8 characters'
      type: min
    }
  ]
  type: "required"
  types: {
    required: "password is a required field"
    min: "password must be at least 8 characters"
    matches: "Special character needed" // only returns 1
  }
}
```

**Comment by bluebill1049** [comment]
> The reason being at the top level which you posted above, the `type` object is just the first error message so for a password in the schema:

can you explain above? I thought it's just matter of map the data.

**Comment by sngreg** [comment]
> The reason being at the top level which you posted above, the `type` object is just the first error message so for a password in the schema:

So how the object is currently structured:

```
{
  type: 'required'
  message: 'password is required'
}
```
This is just the first / top level error for this field  (say we dont have "abortEarly = false", it would only return this) When we have `abortEarly = false` it still returns the top validation error that failed (based on the yup schema object and the first criteria to fail in the chain"

```
export const passwordSchema = yup.object().shape({
  password: yup
    .string()
    .required()
    .min(8)
    .matches(RegExp("(.*[a-z].*)"), "Lowercase")
    .matches(RegExp("(.*[A-Z].*)"), "Uppercase")
    .matches(RegExp("(.*\\d.*)"), "Number")
    .matches(RegExp('[!@#$%^&*(),.?":{}|<>]'), "Special")
});
```
So if Password is blank, it fails on `.required()` and the `type` and `message` is just for that criteria

So if we have a `messages []` - there are still 5 other validations that fail, 4 being of type `match` and 1 being type `min`

Therefore if we did a messages array. (which I LOVE) it will just be a list of ALL messages that failed and we would NOT know the type.

Does that make sense?

**Comment by bluebill1049** [comment]
Yes make sense, the bit it confuses me is if you can have messages like below, why you can't strip those `type`?
```
messages: [
    {
      message: 'Special character needed'
      type: matches
    },
    {
      message: 'Uppercase needed'
      type: matches
    },
    {
      message: 'Lowercase needed'
      type: matches
    },
    {
      message: 'Number needed'
      type: matches
    },
    {
      message: 'password is a required field'
      type: required
    },
    {
      message: 'password must be at least 8 characters'
      type: min
    }
  ]
``

**Comment by sngreg** [comment]
We totally can strip the types (I think that is fine and we dont need them, at least I don't) 

```
{
  message: "password is a required field"
  messages: [
    'Special character needed', // Type = Match
    'Uppercase needed' // Type = Match
    'Lowercase needed' // Type = Match
    'Number needed'  // Type = Match
    'password is a required field' // Type = required
    'password must be at least 8 characters' // Type = min
  ]
  type: "required"
  types: {
    required: "password is a required field"
    min: "password must be at least 8 characters"
    matches: "Special character needed" // only returns 1
  }
}
```

The object above works for me, the only thing we. wouldn't be able to do is map the type for all the messages strings. I was just countering a point earlier for based on this comment from you:

>   messages: [] // multiple message for single type

messages [] will just me multiple messages for ANY type in the above schema? If we are good with that, I think we should change @Vandell63 code and get a PR up :)

**Comment by bluebill1049** [comment]
```
{
  message: "password is a required field"
  type: "required"
  types: {
    required: "password is a required field"
    min: "password must be at least 8 characters"
    matches:  [
    'Special character needed', // Type = Match
    'Uppercase needed' // Type = Match
    'Lowercase needed' // Type = Match
    'Number needed'  // Type = Match
    'password is a required field' // Type = required
    'password must be at least 8 characters' // Type = min
  ]
  }
}
```

what about this @sngreg? just think twice about this, `type` is important and you are right.

**Comment by bluebill1049** [comment]
I am just saying it out loud, i need to play with the code to verify by the way.

**Comment by sngreg** [comment]
I do like this and it would solve. my problem of why I raised the question. (Just for anyone following the thread, we. wouldn't have the last 2 messages in that `matches` array as those are for `min` and `required`

So we should have the `types` key

IF type has 1 message THEN  -- [type]: "message"
ELSE IF type has > 1 message THEN -- [type]: [ "message1", "message2"...]

I like this, one other thought is we could make all values in the `types` object be arrays

```
types: {
    required: [
      "password is a required field"
   ],
    min: [
      "password must be at least 8 characters"
    ],
    matches:  [
    'Special character needed', // Type = Match
    'Uppercase needed' // Type = Match
    'Lowercase needed' // Type = Match
    'Number needed'  // Type = Match
    'password is a required field' // Type = required
    'password must be at least 8 characters' // Type = min
  ]
```

**Comment by sngreg** [comment]
Thinking out loud, making each type an array probably doesn't make sense. I dont think there are many types that will have multiple validation criteria so maybe go with your plan. I just hate having inconsistent types array vs string depending on the amount of messages.

**Comment by bluebill1049** [comment]
let me think about this issue a bit more. thanks a lot for your input @sngreg

**Comment by sngreg** [comment]
Thanks @bluebill1049 looking forward to what you come up with :)

**Comment by bluebill1049** [comment]
Thanks @sngreg it's going to be one of those options that we discussed. Just try to pick one that makes most of the sense and developer-friendly.

**Comment by sngreg** [comment]
Perfect, I will code for that in my repo and make a custom resolver until we get a fix in :)

**Comment by bluebill1049** [comment]
Let's go with this  @sngreg @Vandell63. 👍 

``` ts
type Message = string;
type TypeName = string;

type ValidateResult = Message | boolean | undefined;

type FieldError = {
  "type": TypeName, // no chnage
  "message": Message, // no chnage
  "messages": Record<TypeName, ValidateResult[]> // new
  "types": Record<string, ValidateResult>, // no chnage
}
```

**Comment by bluebill1049** [comment]
i will create a PR at the core as well for this.

**Comment by sngreg** [comment]
Thanks @bluebill1049 i like this plan! Thanks for all the thought and making the PR! Excited to get this enhancement in this awesome repo!

**Comment by Vandell63** [comment]
Woaw guys 20 messages missing :) . Great let's do this. Do you want me some helps or modify the codesandbox or all goods  ?

**Comment by Vandell63** [comment]
@sngreg  @bluebill1049  I have update the codesandbox -> https://codesandbox.io/s/yup-resolver-with-errors-array-pvph7?file=/src/App.js
And it work as expected BUT the ui refresh only when one of types has been remove or added SO:
If you tested, `special` message still as soon as all special message are resolved.
You can find the `Yup errors` in the logs to see all yup errors updated correctly.
What you suggest ?

**Comment by sngreg** [comment]
@Vandell63  Thanks! This is functioning how I would expect it to function!

@bluebill1049 - Not to throw a wrench into our solution, but we might have an issue with types adding `messages`

```
const { errors } = useForm<T>();

// errors type = DeepMap<T, FieldError>

// Type that is from RHFs
export declare type FieldError = {
    type: string;
    ref?: Ref;
    types?: MultipleFieldErrors;
    message?: Message;
};
```

**Comment by Vandell63** [comment]
@sngreg  this preparation ? -> https://github.com/react-hook-form/react-hook-form/pull/2247

**Comment by sngreg** [comment]
Thanks @Vandell63  -  Bill's always one step ahead of me!

**Comment by Vandell63** [comment]
@sngreg  i think we have to wait for a decision and the PR too to be sync on . And take in mind that the ui do not refresh on new yup errors from the same types. It work when message was a Array<string>. So the current example refresh the ui if one of the key appear or disappear base on yup errors.
Wating here you final though and decision @bluebill1049  @kotarella1110  :)

**Comment by sngreg** [comment]
Thanks @Vandell63  - In my use case, I will need the UI to refresh to give live feedback on the password criteria. I agree, lets see what Bill and Kotarella1110 has to say in RFH and then work on our solution

**Comment by sngreg** [comment]
@bluebill1049 @Vandell63 - looks like the PR is merged in RHFs (thanks for doing that) - 

Bill - would you like us to submit a PR to this repo now with the final structure that we talked about using types and message arrays? I still think this resolver should return an array for every message in the types key (like we were going to do for messages)

**Comment by bluebill1049** [comment]
<img width="946" alt="Screen Shot 2020-07-17 at 9 21 27 pm" src="https://user-images.githubusercontent.com/10513364/87781150-7c465600-c873-11ea-9131-ffee264ecbc4.png">

let's follow this, unless if there is anything that we are missing.

**Comment by sngreg** [comment]
@Vandell63 okay that works, so basically, the type is the key and if there is only one message it is 

[type]: Message 

But if multiple messages it is 

[type]: Message[]

That works for me, I just like to be consistent as possible with value types but works for my scenario

**Comment by Vandell63** [comment]
@sngreg  I saw that the types are merge to rhf but for this repo nothing has change yet right ? Or am i missing something
@bluebill1049  @kotarella1110  thx for your time :)

**Comment by sngreg** [comment]
@Vandell63 based on looking at open / closed PRa nothing has changed. That being said not sure if bill or kota are working in it?

**Comment by kotarella1110** [comment]
@sngreg please create this PR 👍 
We will review the PR you created.

**Comment by sngreg** [comment]
@Vandell63 do you have a PR started, if not I can look into making one. (I don’t want to duplicate the efforts)

**Comment by bluebill1049** [comment]
looking forward for the PR. thanks 👍

**Comment by Vandell63** [comment]
@sngreg  sorry not yet, do want me to give a try ?

**Comment by sngreg** [comment]
@Vandell63 if you have time today sure. I looked at the code sandbox and I think we are almost there. I am using the latest code sandbox and was working as intended.

**Comment by Vandell63** [comment]
@sngreg  @bluebill1049  i let you video instead **of hundred of wording**.
https://www.loom.com/share/d561dd07ce9948e489d881d2bd62e1c5

I will start the pull request tomorrow if it sounds good to you ;).

**Comment by sngreg** [comment]
@Vandell63 thanks for making the video and the code! This looks great to me. Looking forward to the PR!

**Comment by Vandell63** [comment]
@bluebill1049  @sngreg  there we go -> https://github.com/react-hook-form/resolvers/pull/32

**Comment by Vandell63** [comment]
@sngreg  are you happy with the new release 0.1.0 ? If yes we should maybe close this issue ?

**Comment by sngreg** [comment]
@Vandell63  Yes! Everything works great! Thanks @Vandell63 / @bluebill1049 / @kotarella1110  for the quick work and the release. Closing this issue out.

**Comment by codemaster115** [comment]
I think it's because of https://github.com/react-hook-form/resolvers/commit/fe53179542b1fcda27df7427d61cca3c9965c2f9#diff-1c9dbc45c6880a5a6b5aef346c662825aa881277d91717d88cd8aae0cd35bcc4.
Looking forwards for your update.

**Comment by jorisre** [comment]
Hi @codemaster115 

Can you share a codesanbox with your problem please ?

**Comment by codemaster115** [comment]
Hi, Joris. Thanks for your quick reply.
https://codesandbox.io/s/react-hook-form-basic-forked-60bno?file=/src/index.js
React Hook Form - Basic (forked) - CodeSandbox
This is example with my problem.

Kind Regards
Jason

**Comment by jorisre** [comment]
Thanks for the codesandbox @codemaster115 
I've opened a new issue, I'll fix it soon

The issue: https://github.com/react-hook-form/resolvers/issues/155

**Comment by codemaster115** [comment]
Thank you, @jorisre
