### ISSUE TITLE
feat: support coercions for superstruct resolver

### ISSUE THREAD

**Issue by israelidanny** [react-hook-form/resolvers#267]
**Is your feature request related to a problem? Please describe.**
Sometimes the data needs to be manipulated (coerced) during validation. Superstruct supports this using coercions.

**Describe the solution you'd like**
Support coercions as a parameter or settings and use `create()` instead of `validate()`

**Describe alternatives you've considered**
It's possible to do this post-validation, but it's much more elegant to do this during.

**Additional context**
https://docs.superstructjs.org/api-reference/coercions

**Comment by bluebill1049** [comment]
can you build this with a custom resolver?

**Comment by dlindenkreuz** [comment]
Add `{ coerce: true }`. It will be passed to Superstruct's `validate`.

```typescript
useForm({
  resolver: superstructResolver(FooStruct, { coerce: true }),
})
```
