### ISSUE TITLE
Array values in Zod resolver need to be wrapped in `NestedValue`

### ISSUE THREAD

**Issue by TheBestMoshe** [react-hook-form/resolvers#272]
**Describe the bug**

**To Reproduce**

1. Go to [this Codesandbox](https://codesandbox.io/s/react-hook-form-zod-resolver-bug-demonstration-651hk?file=/src/App.tsx:1055-1212)
2. Scroll to line 43
3. See the type error `Property 'message' does not exist on type 'FieldError[]'`
4. Click `Submit` in the browser window without selecting any checkboxes. 
5. You will see the error message is properly rendered to the screen even though Typescript says there is no property `.message`

**Codesandbox link (Required)**
[https://codesandbox.io/s/react-hook-form-zod-resolver-bug-demonstration-651hk?file=/src/App.tsx](https://codesandbox.io/s/react-hook-form-zod-resolver-bug-demonstration-651hk?file=/src/App.tsx:1055-1212)

**Expected behavior**
`errors.yummyFruit` should be of type `FieldError` Instead it's type `FieldError[]`. The actual value in the object is a `FieldError`

**Screenshots**
<img width="1259" alt="Screen Shot 2021-11-01 at 8 52 43 PM" src="https://user-images.githubusercontent.com/34072688/139769574-df40d93f-62a5-4683-a842-093f808ee314.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 95.0.4638.54

**Additional context**
I found that someone [posted a similar issue in the /react-hook-form](https://github.com/react-hook-form/react-hook-form/issues/2922) repo. The solution given over there was to wrap the Array type with a [NestedValue](https://react-hook-form.com/ts#NestedValue).

**Comment by bluebill1049** [comment]
This is a limitation which is impossible for hook form infer the correct type based on group inputs or single input, hence NestedValue is required for such groups inputs.

**Comment by jonatassales** [comment]
@bluebill1049 I'm curious because you've added a implementation that works here:

https://codesandbox.io/s/infallible-panini-7duc6?file=/src/App.tsx

...But when you bump the `@hookform/resolvers` to the latest version it crashes.
