### ISSUE TITLE
New React hook form update seems to break this package (v7.20.0)

### ISSUE THREAD

**Issue by JClackett** [react-hook-form/resolvers#285]
**Describe the bug**

Using Next.js 12 and using the latest hook form packages

```
error - Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jclackett/Apps/TrendWatching/@trendwatching/node_modules/react-hook-form/dist/index.cjs.js from /Users/jclackett/Apps/TrendWatching/@trendwatching/node_modules/@hookform/resolvers/dist/resolvers.js not supported.
index.cjs.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.cjs.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/jclackett/Apps/TrendWatching/@trendwatching/node_modules/react-hook-form/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

**To Reproduce**
Update react hook form to latest release, use the latest @hookform/resolver version (v2.8.3)

**Codesandbox link (Required)**
I can't reproduce it on codesandbox as I can't get the basic nextjs example to work :(

**Desktop (please complete the following information):**

- OS: MacOs

**Comment by bluebill1049** [comment]
hey @JClackett thanks for reporting, we already have a ticket for nextjs 12 issue: https://github.com/react-hook-form/resolvers/issues/271 let's close this one and follow up there. i honestly don't know if this is an issue our bundle or nextjs as some works and some not.

**Comment by bluebill1049** [comment]
FYI, going to revert 7.20.0 type module update.
