### ISSUE TITLE
inject context into yup's context

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/resolvers#29]
inject context into yup's context would be a PR at the resolver if you interested.

https://github.com/react-hook-form/resolvers/blob/master/src/yup.ts#L54

_Originally posted by @bluebill1049 in https://github.com/react-hook-form/react-hook-form/issues/2222#issuecomment-658622653_

**Comment by Vandell63** [comment]
@bluebill1049  pull request -> https://github.com/react-hook-form/resolvers/pull/30

**Comment by bluebill1049** [comment]
nice!
