### ISSUE TITLE
Schema only validating .refine when object passes

### ISSUE THREAD

**Issue by ricardo-rp** [react-hook-form/resolvers#290]
**Describe the bug**
I have the following schema in my app, for a user signup form: 

```const schema = z
  .object({
    name: z.string().nonempty("Enter full name"),
    email: z.string().nonempty("enter email").email("enter valid email"),
    password: z
      .string()
      .nonempty("enter password")
      .min(6, "enter 6 chars or more"),
    confirmPassword: z.string(),
    cellphone: z
      .string()
      .regex(brCellphoneRegexp, "Digite um número de celular válido com DDD"),
    privacyTermsAccepted: z.literal(true, {
      invalid_type_error: "Você deve aceitar os termos de uso"
    })
  })
  .refine(({ password, confirmPassword }) => password === confirmPassword, {
    message: "Passwords must match",
    path: ["confirmPassword"]
  });
```

I am not getting the `confirmPassword` error correctly shown on-screen from the `refine` function. It seems the error for this field will only appear on screen if the whole form is already filled out (maybe it's checking `.refine` only after `.object` has passed?)

**To Reproduce**
1. Open the codesandbox
2. fill out the form from top to bottom, as you normally would
3. Do not correctly confirm your password. Insert a different password in the confirmation field.
4. Verify that validation message is not on screen.

[**Codesandbox link**](https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-2kl4w?file=/src/App.js:314-986)

I managed to narrow it down to the `privacyTermsAccepted` field in the schema. To verify this:
1. Comment out the `privacyTermsAccepted` field from the zod schema
2. Comment out the same field from the form
3. Fill out form as normally.
4. See error message woks correctly.

**Expected behavior**
Expected `confirmPassword` error message to appear on screen.

**Desktop (please complete the following information):**

- OS: Tested in manjaro linux and PopOs
- Browser: chrome
- Version: "^7.17.5",

I am unsure as to whether this is a bug with the zodResolver, zod itself, or improper usage of one of the tools. Any support is greatly appreciated.

**Comment by bluebill1049** [comment]
my understanding is it depends on when `.refine` is getting executed, it may not associate with any inputs, hence there are no errors showing on the UI. you may have to use `trigger` API for such usage.

**Comment by ricardo-rp** [comment]
@bluebill1049 I managed to narrow it down a bit further. The `confirmPassword` error will be correctly set in `formState` after the checkbox is touched.
If the checkbox is not touched, the error does not reach formState correctly.

I actually managed to solve it by replacing .literal with .boolean and using refine. Here's a [fork](https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-b1vwx?file=/src/App.js) with the issue fixed.

Still, I'd like to know if this was a bug or improper usage.

**Comment by bluebill1049** [comment]
![Screen Shot 2021-11-26 at 12 42 25 pm](https://user-images.githubusercontent.com/10513364/143514327-62a8577e-b155-48ec-9f02-da857f4b7a65.png)

> Schema validation focus on the field level for error reporting. Parent level error look is only limited to the direct parent level that is applicable for components such as group checkboxes.

https://react-hook-form.com/api/useform

because react hook form focuses on field level validation for re-render errors object, we evaluate errors from schema against field names, so we don't constantly flush re-render your component. so in order for react hook form to update errors object, it need to aware the association with the field.

**Comment by ricardo-rp** [comment]
@bluebill1049 If I understand correctly, this suggests what I'm doing wrong is to use `.refine` on the whole form schema, but I managed to work around the issue by altering the `privacyTermsAccepted` checkbox. (see [codesandbox](https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-b1vwx?file=/src/App.js)). Does this mean I got lucky, and the way I'm validating my form is still potentially problematic?

What would be the recommended, field-level way of creating a password confirmation input?

Also, thank you very much for your replies.

**Comment by bluebill1049** [comment]
Here is follow below: (hopefully make more sense)

user action -> field level value update -> schema errors (form level) -> resolver match field name (field level) -> render formState errors

If you need formLevel/groupLevel errors, I think it's safer to do a `trigger` on that specific error path, so react hook form can draw the lines together and flush the render with associated fields.

**Comment by mcmillion** [comment]
FWIW, I just ran into this issue. Both `refine` and `superRefine` never get called. `trigger` doesn't seem to do anything to fix the problem.

**Comment by kieran-osgood** [comment]
Not quite the same as @mcmillion but the superRefine does definitely get called whenever onChange is called - what I noticed is given a superRefine that looks like this (this is a dynamic list of pills, which toggle true or false if selected) e.g.
```
const Schema = z.record(z.boolean()).superRefine((formState, ctx) => {
  const selectedCoreValues = Object.values(formState)?.filter(Boolean)?.length;
  console.log('superrefine');
  const lowerBound = 5;
  if (selectedCoreValues < lowerBound) {
    ctx.addIssue({
      code: z.ZodIssueCode.too_small,
      minimum: 5,
      type: 'array',
      inclusive: false,
      message: `You must select at least ${lowerBound} core values`,
      path: ['coreValues'],
    });
  }
});
```

Every `onChange` I see the log of 'superrefine' - and it correctly adjusts the `form.formState.isValid` so my submit button is correctly enabling/disabling when they've selected 5 items, however the `form.formState.errors` doesn't populate the errors from the superRefine, UNLESS I call `form.handleSubmit` (I turned off the disabled status on the submit button and noticed this)
