### ISSUE TITLE
Type NestedValue + yupResolver fails type checking after v1.3.7

### ISSUE THREAD

**Issue by jonatassales** [react-hook-form/resolvers#297]
**Describe the bug**
When I try to type `useForm` with property that is an array of strings, like:

```javascript
import * as yup from 'yup'
import { NestedValue } from 'react-hook-form'

interface ApplicationCreationFormValidation {
  scopes: NestedValue<string[]>
}

const schema = yup
  .object({
    scopes: yup.array().of(yup.string()).required('You must select at least one scope')
  })
  .required()

const form = useForm<ApplicationCreationFormValidation>({
    defaultValues: { scopes: [] },
    mode: 'onTouched',
    resolver: yupResolver(schema)
  })
```
I get de following type error:

<img width="1013" alt="Screen Shot 2021-11-30 at 11 07 59" src="https://user-images.githubusercontent.com/6073626/144062604-b92c4918-4688-43e2-9a26-378f5ae2226b.png">

**To Reproduce**
To reproduce you can go to the codesandbox that @bluebill1049 posted on an issue related to it:

If you bump the version to the latest it crashes.

**Codesandbox link (Required)**
https://codesandbox.io/s/infallible-panini-7duc6?file=/src/App.tsx

**Expected behavior**
it shouldn't have any type error

**Desktop (please complete the following information):**

- OS: macOS Big Sur
- Browser Chrome
- Version 95.0.4638.69 (Official Build) (arm64)

**Additional context**
I've noticed that stopped working after v1.3.7. In my case, if I downgrade the version to 1.3.7, it works.

**Comment by jorisre** [comment]
Starting at version 2 of resolvers, you've to use the v7 version of react-hook-form. 
More info here: https://github.com/react-hook-form/resolvers/releases/tag/v2.0.0

**Comment by jorisre** [comment]
![Screen Shot 2021-11-30 at 4 47 03 PM](https://user-images.githubusercontent.com/7545547/144082097-ca49aa98-e460-4196-8d45-e3a4b0290ad3.png)

Your codesandbox uses react-hook-form v6.
You can use the latest version of yup as well, @types/yup isn't required anymore.
You've to import the resolver like that: `import { yupResolver } from '@hookform/resolvers/yup';`

**Comment by jonatassales** [comment]
This codesandbox was posted by @bluebill1049 actually, I just updated all deps to the latest version and it crashed.

I ended up solving it by doing a casting, which I think it isn't the best solution:

```javascript
import * as yup from 'yup'
import { NestedValue } from 'react-hook-form'
import { useForm, Resolver } from 'react-hook-form'

interface ApplicationCreationFormValidation {
  scopes: NestedValue<string[]>
}

const schema = yup
  .object({
    scopes: yup.array().of(yup.string()).required('You must select at least one scope')
  })
  .required()

const form = useForm<ApplicationCreationFormValidation>({
    defaultValues: { scopes: [] },
    mode: 'onTouched',
    resolver: yupResolver(schema) as Resolver<ApplicationCreationFormValidation>
  })
```

I think `useForm` should infer the resolver type by its generic. Maybe this is something you guys can look at. Thanks for the help @jorisre

**Comment by jonatassales** [comment]
Sorry, the code snippet isn't the same as the codesandbox. I may have caused confusion

**Comment by bluebill1049** [comment]
closing as this is version related problem.

**Comment by ifightcrime** [comment]
@bluebill1049 hmm this doesn't seem like a version issue? I'm getting the same thing on `react-hook-form@7.27.1` with `@hookform/resolvers@2.8.8`.

```
...
          Types of property 'address' are incompatible.
            Type '{ matching_place_name?: string | undefined; id: string; place_name: string; geometry: { type?: string | undefined; coordinates: [number, number]; }; }' is not assignable to type 'NestedValue<{ matching_place_name?: string | undefined; id: string; place_name: string; geometry: { type?: string | undefined; coordinates: [number, number]; }; }>'.
              Property '[$NestedValue]' is missing in type '{ matching_place_name?: string | undefined; id: string; place_name: string; geometry: { type?: string | undefined; coordinates: [number, number]; }; }' but required in type '{ [$NestedValue]: never; }'.
```

I'm using Zod. My workaround is likely going to be the same as @jonatassales, but not ideal.

**Comment by ifightcrime** [comment]
Traced down react-hook-form/react-hook-form#7888 and it's fixed in v8! So looks like this was technically a version issue after all. 😜
