### ISSUE TITLE
Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by drydenwilliams** [react-hook-form/resolvers#298]
**Describe the bug**

When my form renders I get an `Cannot read properties of undefined (reading 'reduce')` error and I can't seem to figure out the issue.

**To Reproduce**

1. Visit the [Sandbox](https://codesandbox.io/s/muddy-voice-q1ilg?file=/src/NewSiteForm.tsx)
2. Open in full-screen mode or [click here](https://q1ilg.csb.app/)
3. And see the error popup

**Expected behavior**
It should load the form up just fine and dandy

**Screenshots**

<img width="957" alt="Screenshot 2021-12-02 at 16 53 50" src="https://user-images.githubusercontent.com/4403089/144467094-cff8a51e-99f0-4c50-8071-df05415bc3da.png">

<img width="814" alt="Screenshot 2021-12-02 at 16 49 18" src="https://user-images.githubusercontent.com/4403089/144466450-e57ec155-b69f-4cf1-bcb4-d10b1f135a9f.png">

**Desktop (please complete the following information):**

- Device: [MacBook Air M1]
- Browser [Chrome]
- Version [Version 96.0.4664.55]

**Comment by bluebill1049** [comment]
do not spam issue.

**Comment by drydenwilliams** [comment]
Please can you reopen this, I didn't intend to spam and can't find the other ticket. @bluebill1049

**Comment by jorisre** [comment]
@drydenwilliams  https://github.com/react-hook-form/resolvers/issues/299
