### ISSUE TITLE
Error: Unexpected import statement in CJS module. using @hookform/resolvers 2.8.4 and Next.js 12.0.7

### ISSUE THREAD

**Issue by ElektrikSpark** [react-hook-form/resolvers#301]
**Describe the bug**
Error: Unexpected import statement in CJS module.

**To Reproduce**

1. Next.js (tested 12.0.4 and 12.0.7)
2. install @hookform/resolvers 2.8.4
3. import { yupResolver } from "@hookform/resolvers/yup"

**Expected behavior**
No error with import

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome

**Comment by ElektrikSpark** [comment]
I tested v1.3.0 because of this thread [](https://github.com/react-hook-form/resolvers/issues/105) and it worked.

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/resolvers/issues/271
