### ISSUE TITLE
AJV resolver

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/resolvers#309]
**Is your feature request related to a problem? Please describe.**
Build a new AJV resolver for JSON schema

**Describe the solution you'd like**
Having a dedicated AJV resolver

**Describe alternatives you've considered**
Build custom resolver

**Additional context**
We did have an AJV resolver PR (attempted) but failed, wondering if anyone would like to pick it up and give it another try.

https://github.com/react-hook-form/resolvers/pull/59/files

cc @jorisre

**Comment by ShivamJoker** [comment]
I'll have a look, see if I can do anything to fix.

**Comment by bluebill1049** [comment]
that would be awesome!

**Comment by ShivamJoker** [comment]
@bluebill1049 The tests seems to be passing is there any particular issue which i need to fix ?

**Comment by bluebill1049** [comment]
send us the PR please 👯  @ShivamJoker

**Comment by ShivamJoker** [comment]
Okay after merging from master it has now some typescript issues. I am trying to fix those will send PR if done

**Comment by ShivamJoker** [comment]
![image](https://user-images.githubusercontent.com/23727670/148744082-2239dae3-ec3a-4e48-bca0-9190b746e49b.png)

There are so many errors 😭

**Comment by bluebill1049** [comment]
I love the 💩  emoji, would you like to send in PR anyhow? we can take a look at it.

**Comment by ShivamJoker** [comment]
There are many things which has been changed since this implementation of ajv. Hope you guys can figure something out.

**Comment by cgarrovillo** [comment]
dont close it bot!

**Comment by AndrewOttavianoAbb** [comment]
I noticed #317 is still in draft mode and seems to be out of date/abandoned. Are people still interested in adding a ajv resolver?

**Comment by bluebill1049** [comment]
whoever is interested, feel free to pick it up and help/contribute https://github.com/react-hook-form/resolvers/pull/318
