### ISSUE TITLE
Add context on error

### ISSUE THREAD

**Issue by squiaios** [react-hook-form/resolvers#316]
Hello,

I am facing a small problem. I do not retrieve certain information in the error object.

https://github.com/react-hook-form/resolvers/blob/6ee8990708e798bbfc308d07bc5d595d3e69981a/joi/src/joi.ts#L15

Is it possible to return context too please ?

In some case, context is useful to get informations (like `limit` when you specify a minimum limit)

**Comment by bluebill1049** [comment]
not at this stage.
