### ISSUE TITLE
Yup resolver silently ignores error that are not ValidationError

### ISSUE THREAD

**Issue by zero734kr** [react-hook-form/resolvers#320]
**Describe the bug**
For example, when a TypeError (``TypeError: You cannot `concat()` schema's of different types: string and number``) is thrown by the schema validator (validator of the schema itself), the yup resolver silently ignores the error because the `error.field` described in [this line of code](https://github.com/react-hook-form/resolvers/blob/6ee8990708e798bbfc308d07bc5d595d3e69981a/yup/src/yup.ts#L14) is missing, falling back to a blank array.

**To Reproduce**

1. Create a simple object schema like below and use it in the input element:
```js
import React from "react";
import ReactDOM from "react-dom";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";

import "./styles.css";

const SignupSchema = yup.object().shape({
  name: yup.string().required(),
  value: yup.string().when("name", {
    is: "test",
    then: yup.number().required()
    // TypeError: You cannot `concat()` schema's of different types: string and number
    // is thrown in this case but there isn't any warning about that.
    // As the error is silently ignored, when the user clicks the submit button
    // nothing happens instead of alerting the stringified json data as described in line 27 of this sandbox.
  })
});

function App() {
  const { register, handleSubmit, errors } = useForm({
    resolver: yupResolver(SignupSchema)
  });

  const onSubmit = (data) => {
    alert(JSON.stringify(data));
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <div>
        <label>Name</label>
        <input type="text" name="name" ref={register} />
        {errors.name && <p>{errors.name.message}</p>}
      </div>
      <div>
        <label>Value</label>
        <input type="text" name="value" ref={register} />
        {errors.value && <p>{errors.value.message}</p>}
      </div>
      <input type="submit" />
    </form>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```
2. Write 'test' in the first input element
3. Write any text in the second input element
4. Submit the form by clicking the button, but nothing happens.

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

[My fork of yup resolver template](https://codesandbox.io/s/react-hook-form-validationschema-v6-forked-g4kdl?file=/src/index.js)

- [Yup resolver](https://codesandbox.io/s/react-hook-form-validationschema-v6-2l77g) Template
- [Zod resolver](https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-ko5ll) Template
- [Joi resolver](https://codesandbox.io/s/react-hook-form-joiresolver-v6-yejqe) Template
- [Superstruct resolver](https://codesandbox.io/s/react-hook-form-v6-superstructresolver-ed67i) Template
- [Vest resolver](https://codesandbox.io/s/vest-k6gbd) Template
- [Custom resolver](https://codesandbox.io/s/react-hook-form-customresoliver-v6-h4ti6) Template

**Expected behavior**

Error ``TypeError: You cannot `concat()` schemes of different types: string and number`` thrown.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bluebill1049** [comment]
We don't validate your schema. This should be taken care of at your schema level check, resolver only focuses on `ValidationError`.

**Comment by zero734kr** [comment]
I meant yup's schema validator, not @hookform/resolvers. Sorry if it was confusing.

**Comment by jorisre** [comment]
In your case, Yup fails but the thrown error does not contain the path of the field. So we can't attach the error to a react-hook-form field. Do you see what I mean?

**Comment by zero734kr** [comment]
> In your case, Yup fails but the thrown error does not contain the path of the field. So we can't attach the error to a react-hook-form field. Do you see what I mean?

Yes I understand.
But I think the situation is like a bug, because it omits the thrown error and I was debugging for hours to find the cause.
So, instead of attaching the error to some react-hook-form field, how about throwing it anyway to some error handler like next.js catches in their debugger? In this case I can at least know there is an error and I need to solve that.

**Comment by bluebill1049** [comment]
Maybe that's something we can consider. What's your thoughts @jorisre?

**Comment by jorisre** [comment]
Yep, sounds good to me. I'll open a PR. Thanks for the issue.
