### ISSUE TITLE
issue: "Illegal constructor" error when using the classValidatorResolver with a file input

### ISSUE THREAD

**Issue by williamdespard** [react-hook-form/resolvers#321]
### Version Number

7.15.4

### Codesandbox/Expo snack

https://codesandbox.io/s/flamboyant-breeze-trm2p?file=/src/App.tsx

### Steps to reproduce

1. Create a simple form with a file input e.g.

`<input type="file" {...register('test')} />`

2. Create a class for the validation schema e.g. 

```
class ValidationSchema {
  test: any;
}
```

3. Give the validation class to the useForm hook e.g.

useForm< ValidationSchema >({
  resolver: classValidatorResolver(ValidationSchema),
});

4. Submit the form after selecting a .jpg file. You will see a "Illegal constructor" error

### Expected behaviour

We shouldn't get an error.

### What browsers are you seeing the problem on?

Chrome, Safari

### Relevant log output

```shell
Unhandled Runtime Error
TypeError: Illegal constructor
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
I am not sure if this issue is related to hook form or `classValidatorResolver` simply doesn't support file type object.

**Comment by williamdespard** [comment]
> I am not sure if this issue is related to hook form or `classValidatorResolver` simply doesn't support file type object.

We're kind of tied into using class-validator because we're using it with NestJs and want to share our validation with the frontend. Is there any way of excluding the file input from the validation schema with react hook form, so we can still validate our other form fields?

**Comment by bluebill1049** [comment]
you can try to build a custom resolver and just manually omit the file input.

**Comment by williamdespard** [comment]
> you can try to build a custom resolver and just manually omit the file input.

Do you have any documentation or pointers on how I would go about doing that?

**Comment by bluebill1049** [comment]
in the doc: https://react-hook-form.com/api/useform

```tsx
import * as React from "react";
import { useForm } from "react-hook-form";
import * as Joi from "joi";

const validationSchema = Joi.object({
  username: Joi.string()
    .alphanum()
    .min(3)
    .max(30)
    .required()
});

const App = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    context: "context",
    resolver: async (data, context) => {
      const { error, value: values } = validationSchema.validate(data, {
        abortEarly: false,
      });

      if (!error) return { values: values, errors: {} };

      return {
        values: {},
        errors: error.details.reduce(
          (previous, currentError) => ({
            ...previous,
            [currentError.path[0]]: currentError,
          }),
          {},
        ),
      };
    },
  });

  const onSubmit = data => {
    console.log(data)
  };

  return (
    <div className="App">
      <h1>resolver</h1>
      
      <form onSubmit={handleSubmit(onSubmit)}>
        <label>Username</label>
        <input {...register("username")} />
        {errors.username && <p>errors.username.message</p>}
        <input type="submit" />
      </form>
    </div>
  );
};
```

**Comment by williamdespard** [comment]
That's very helpful. I've got this working in a rudimentary way. I will post the finished code later to help others. @bluebill1049  I just want to say what a fantastic job you are doing with this library. Thank you on behalf of the react community 👏

**Comment by bluebill1049** [comment]
You are welcome. Thanks In advance for sharing solution as well!

**Comment by williamdespard** [comment]
My working custom validation resolver code is below. @bluebill1049 I'm not doing anything with regards to removing the file field from the validation (it just doesn't have any validation rules). So, this seems like this is in fact a small issue with your `classValidatorResolver`.

```
const validationResolver = async <Data extends { [k: string]: unknown }>(
  data: Data,
  ValidationSchema: new (...args: any[]): Record<keyof Data, any>
) => {
  const validationSchema = new ValidationSchema();

  Object.assign(validationSchema, data);

  return validate(validationSchema).then((validationErrors) => {
    const errors: Record<string, { key: string; type: 'validation' } | never> =
      {};

    if (validationErrors.length === 0) {
      console.log('validation succeed', data);
      return { values: data, errors: {} };
    }

    validationErrors.forEach(
      (validationError) =>
        (errors[validationError.property] = {
          key: Object.keys(
            validationError.constraints as Record<string, string>
          )[0],
          type: 'validation',
        })
    );

    console.log('validation failed', errors);
    return { values: {}, errors };
  });
};
```

**Comment by bluebill1049** [comment]
hey @williamdespard would you have time to look into this issue and potentially send us a PR on the fix https://github.com/react-hook-form/resolvers/blob/master/class-validator/src/class-validator.ts

**Comment by jorisre** [comment]
@bluebill1049 you're thinking for exclude file validation of this resolver right ?

**Comment by jorisre** [comment]
It works with the @williamdespard 's custom resolver because he is using `Object.assign`, we can't use it in our case. It's not compatible with nested data.

I've found a possible solution, I'm a beginner with `class-validator`, you may adapt the code below:
```ts
export class ValidationSchema {
  @Type(() => Object)
  @Transform(({ obj }: TransformFnParams) => {
    return obj.test;
  })
  test: File | null = null;
}
```

👉🏻 [https://codesandbox.io/s/restless-wood-mw9mz](https://codesandbox.io/s/restless-wood-mw9mz)

**Comment by williamdespard** [comment]
> hey @williamdespard would you have time to look into this issue and potentially send us a PR on the fix https://github.com/react-hook-form/resolvers/blob/master/class-validator/src/class-validator.ts

I'm currently on a deadline with a project so I'm afraid I can't at the moment. But potentially in a few weeks if it's helpful

**Comment by williamdespard** [comment]
> It works with the @williamdespard 's custom resolver because he is using `Object.assign`, we can't use it in our case. It's not compatible with nested data.
> 
> 
> 
> I've found a possible solution, I'm a beginner with `class-validator`, you may adapt the code below:
> 
> ```ts
> 
> export class ValidationSchema {
> 
>   @Type(() => Object)
> 
>   @Transform(({ obj }: TransformFnParams) => {
> 
>     return obj.test;
> 
>   })
> 
>   test: File | null = null;
> 
> }
> 
> ```
> 
> 
> 
> 👉🏻 [https://codesandbox.io/s/restless-wood-mw9mz](https://codesandbox.io/s/restless-wood-mw9mz) 
> 
> 

Thanks for this but it appears your solution doesn't work in the sandbox provided I get the error "Not enough arguments"

**Comment by ZhaoTzuHsien** [comment]
Any fix about that?
