### ISSUE TITLE
Yup resolver problem with test function

### ISSUE THREAD

**Issue by davidesigner** [react-hook-form/resolvers#331]
**Describe the bug**
When we use yup schema validation with the `test` function, the react-hook-form errors object does not return the name of the failed test as key.

```js
  const SignupSchema = yup
    .object()
    .shape({
      firstName: yup.string().required("required")
    })
    .test('test', "test error message", (val) => {
      return val.firstName === "test";
    });

  const { register handleSubmit, formState: { errors } } = useForm({
    resolver: yupResolver(SignupSchema)
  });

  console.log(errors);
```

Console log results (as you can see, the key is an empty string):

```
{
    "": {
        "message": "test error message",
        "type": "test"
    }
}
```

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-validationschema-v7-2ik00

**Expected behavior**

Errors object must be returned with the name of the failed test as key:

```
{
    "test": {
        "message": "test error message",
        "type": "test"
    }
}
```

**Comment by davidesigner** [comment]
Thanks for you fast reply @jorisre!

So, we cannot have a form level validation management?

**Comment by jorisre** [comment]
Currently no, there is a RFC for your needs https://github.com/react-hook-form/react-hook-form/discussions/6472

**Comment by davidesigner** [comment]
Thanks for your replies. I understand that this is an expected behavior of react-hook-form so I close the issue here.
