### ISSUE TITLE
tsconfig changes required to use resolvers

### ISSUE THREAD

**Issue by spbriggs** [react-hook-form/resolvers#34]
I'm migrating from v5 to v6 with resolvers. I'm getting Typescript errors when I try to build my project which required changing my tsconfig.json

```
xxx/node_modules/@hookform/resolvers/dist/superstruct.d.ts
(2,8): Module '"xxxx/node_modules/superstruct/lib/index"' has no default export.
```
and

```
xxx/node_modules/@hookform/resolvers/dist/superstruct.d.ts
(3,94): Generic type 'Struct<T, S>' requires between 1 and 2 type arguments.
```

( xxx is truncated path to my project folder)

For the first one I had to add this to my tsconfig.json

`    "allowSyntheticDefaultImports": true`

and for the second I had to edit node_modules/@hookform/resolvers/dist/superstruct.d.ts to put a 

`// @ts-ignore`

between lines 2 and 3

**Comment by bluebill1049** [comment]
are you using superstruct or yup?

**Comment by spbriggs** [comment]
Hi. I'm using Yup. Although as per #20 I've had to install superstruct too.

**Comment by bluebill1049** [comment]
ok let's focus on that issue 👍

**Comment by spbriggs** [comment]
Hi @bluebill1049. Apologies for re-opening this issue but just wanted to add that I've done some more digging and the second problem (regarding Struct) is actually due to https://github.com/react-hook-form/resolvers/issues/16#issuecomment-652531948 

Setting superstruct version to ~0.8.4 in my package.json fixes that issue.

**Comment by bluebill1049** [comment]
oh! so if we fix superstruct we can resolve this problem?

**Comment by spbriggs** [comment]
I'm not at all familiar with superstruct but that seems a reasonable assumption

**Comment by bluebill1049** [comment]
ok thanks, i will take a look this weekend
