### ISSUE TITLE
Since 2.8.6: Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'default' in undefined

### ISSUE THREAD

**Issue by RikkiMasters** [react-hook-form/resolvers#343]
During validation, the error below is shown.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/11843864/152338021-1f0ad9f1-c01f-479f-a56e-c442bf7b737b.png">

This is only in 2.8.6+

I've narrowed it down to a piece of my Yup schema, where it's using '.when' against an element in the parent.

Example: 

```
export const AbcSchema = yup.object().shape({
    field1: yup.string().required(),

    obj2: yup.object({
        obj2Field: yup.string().max(255).when('field1', (field1) => {
            if (field1 === 'value') return yup.string().required()
        }),
    }).nullable()
}
```

yup: 0.32.11
hookform/resolvers: 2.8.6

**Comment by jorisre** [comment]
Thank you for reporting the issue, I'll fix it tonight

**Comment by bluebill1049** [comment]
@RikkiMasters can you reproduce that in a codesandbox?

**Comment by RikkiMasters** [comment]
@bluebill1049 https://codesandbox.io/s/affectionate-tess-esnvt

Just click submit

**Comment by bluebill1049** [comment]
I think it's related to your schema `Schema.validate({})` https://codesandbox.io/s/affectionate-tess-esnvt-forked-4q9hd?file=/src/App.js

**Comment by RikkiMasters** [comment]
@bluebill1049 what did you change? Your sandbox doesn't seem to work for me

**Comment by RikkiMasters** [comment]
@bluebill1049 When using 2.8.5, clicking submit works fine https://codesandbox.io/s/affectionate-tess-esnvt-forked-vwwzq?file=/src/App.js

It fails when using 2.8.6+. Any ideas what could be causing it?

**Comment by bluebill1049** [comment]
we no longer shallow `errors` from schema/
