### ISSUE TITLE
Yup InferType doesn't work

### ISSUE THREAD

**Issue by 72gm** [react-hook-form/resolvers#347]
**Describe the bug**
When using Yup InferType to infer the type from the schema it throws an error in Typescript "Argument of type 'string' is not assignable to parameter of type 'never'.ts(2345)" when trying to register the input

![image](https://user-images.githubusercontent.com/12847881/153595332-801e283b-0060-4a4e-aa24-de9071a23b35.png)

What is this extra "x" property it is generating on the type?

![image](https://user-images.githubusercontent.com/12847881/153596493-cd8d8503-30dd-4161-b3a3-9f887573169a.png)

If I manually create my own type then it works fine

**To Reproduce**

```
export const TestSchema = Yup.object().shape({
  firstName: Yup.string().required("First Name is required"),
});

export type TestAppellant = Yup.InferType<typeof TestSchema>;
```

```
const resolver = {
  resolver: yupResolver(TestSchema),
};

function App() {
  const { register } = useForm<TestAppellant>(resolver);

  return (
    <>
      <div className="card m-3">
        <input type="text" {...register("firstName")} />
      </div>
    </>
  );
}

export default App;
```

**Codesandbox link (Required)**

https://codesandbox.io/s/kpsde

**Expected behavior**
Should not throw this error

**Screenshots**
as above

**Desktop (please complete the following information):**
Chrome, Windows

**Comment by bluebill1049** [comment]
> What is this extra "x" property it is generating on the type?

That's not coming from hook form, I think this is probably a Yup question.

**Comment by 72gm** [comment]
If I upgrade to the latest beta then it now works 

yarn add yup@1.0.0-beta.2

the actual last official release of Yup is 2016????? what's that all about!?!?

**Comment by bluebill1049** [comment]
no idea and not within the scope of this package.

**Comment by kaminskypavel** [comment]
@bluebill1049 is correct, I had the same issue. it looks like `yup.InferType` if only working for ^1.0.0
