### ISSUE TITLE
IE11 crashing with v0.1.0 and react-hook-form v6.08

### ISSUE THREAD

**Issue by rvision** [react-hook-form/resolvers#35]
It reports syntax error on this line:

`const parseErrorSchema = (error, validateAllFieldCriteria) => ...`

which is the code of the resolvers. I assume this needs some transpiling since IE doesn't know about const keyword?

**Comment by rvision** [comment]
Tried with 0.0.3 version, same problem.

When I comment-out resolver imports and code, it works fine.

Bloody IE

**Comment by rvision** [comment]
Any news about this issue?

**Comment by bluebill1049** [comment]
hey @rvision i haven't got chance to work on this one...

**Comment by bluebill1049** [comment]
hey @kotarella1110 any chance you could bring ie11 build over to resolver? 🙏 many thanks.
