### ISSUE TITLE
errors object typing issue with zod

### ISSUE THREAD

**Issue by whengely** [react-hook-form/resolvers#352]
**Describe the bug**
At some point in the last versions of the following, it's impossible to get to properties on the error objects for union typed forms.

zod: 3.11.6
typescript: 4.5.5
react hook form: 7.27.0
@hookform/resolvers: 2.8.8

**To Reproduce**
Example here:  https://github.com/whengely/zod-hook-form

1. npm install
2. npm start
Will display an error.  I've tried to manually narrow the error object and it still does not work.  An example of both types is in the schema.ts file showing the zod generated typing is correct.

**Expected behavior**
Recent versions I could access the values for each field

**Desktop (please complete the following information):**

- OS: Windows 10 running in WSL2 with vim, also verified it happens directly in Windows 10 with vscode
- Browser Chrome

**Comment by bluebill1049** [comment]
provide a codesandbox and steps to reproduce. https://github.com/react-hook-form/react-hook-form/issues/2848
