### ISSUE TITLE
Upgrade from 2.8.4 to 2.8.5 breaks nextJS static rendering

### ISSUE THREAD

**Issue by just-mitch** [react-hook-form/resolvers#356]
**Describe the bug**
When I upgrade from 2.8.4 to 2.8.5, most of my pages which were previously treated as static by nextJS build become Server Side Rendered pages.

I use the yup resolver.

Built on 2.8.4
![Screen Shot 2022-03-02 at 11 05 10 AM](https://user-images.githubusercontent.com/68168980/156400036-ce0b2435-e702-4839-bbe9-66de2a1448e5.png)

Built on 2.8.5 (no other changes whatsoever)
![Screen Shot 2022-03-02 at 11 05 59 AM](https://user-images.githubusercontent.com/68168980/156400209-288a014e-7369-4fd2-b4f9-b9b797c71c4f.png)

**To Reproduce**
Probably create a nextJS project with a simple page and form with the the yup resolver, and run next build to see if it renders statically (which it should).

**Comment by jorisre** [comment]
Can you provide a repo with your issue please ?

**Comment by just-mitch** [comment]
Sorry @jorisre but my repo is closed source.

**Comment by jorisre** [comment]
Can you create a reproductible example ?

**Comment by just-mitch** [comment]
Problem solved. It was caused by importing 
`import { yupResolver } from '@hookform/resolvers/yup/dist/yup';`
instead of
`import { yupResolver } from '@hookform/resolvers/yup';

seems related to https://github.com/react-hook-form/resolvers/issues/337
