### ISSUE TITLE
computedTypesResolver does not work with nested fields

### ISSUE THREAD

**Issue by wereHamster** [react-hook-form/resolvers#367]
**Describe the bug**

I have a schema like so:

```js
const schema = Schema({
  top: string.min(100),

  nested: Schema({
    value: string.min(100),
  }),
})
```

Errors in the top-level fields are reported correctly, while errors in nested fields are lost.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-computed-types-nested-fields-validation-error-bug-9uuuuq?file=/src/index.jsx
2. Run
3. See in the console how the error on the 'top' field is reported but not on the nested field.

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-computed-types-nested-fields-validation-error-bug-9uuuuq?file=/src/index.jsx

**Additional context**

Not sure what the expected shape of `FieldErrors` should be, if it should be a nested object or flat where keys are dot-separated field paths. If the later then fixing computedTypesResolver can be as easy as changing parseErrorSchema like so:

```js
const parseErrorSchema = (computedTypesError: ValidationError): FieldErrors => {
  const parsedErrors: FieldErrors = {};

  for (const { path, error } of computedTypesError.errors || []) {
    parsedErrors[path.join(".")] = {
      type: error.name,
      message: error.message,
    };
  }

  return parsedErrors;
};
```

**Comment by bluebill1049** [comment]
would you like to send a PR to fix this?

> Not sure what the expected shape of FieldErrors should be, if it should be a nested object or flat where keys are dot-separated field paths. 

should be nseted object path with dot notation.

**Comment by wereHamster** [comment]
> should be nseted object path with dot notation.

So which one of the following?

```js
{
  ['top']: { type, message },
  ['nested.value']: { type, message },
}
```


```js
{
  ['top']: { type, message },
  ['nested']: {
    ['value']: { type, message },
  },
}
```

…or are both supported?

**Comment by bluebill1049** [comment]
```
{
  ['top']: { type, message },
  ['nested']: {
    ['value']: { type, message },
  },
}
```

is the correct one.

**Comment by wereHamster** [comment]
Right. So react-hook-form validation can only represent errors in leaf nodes, correct? You can't have an error «somewhere in inside the 'nested' field»…

**Comment by wereHamster** [comment]
Btw the `parseErrorSchema` function I posted in the issue works for me, so I'm confused as to whether react-hook-fork supports both but prefers people to use the nested object notation or whether my code only works due to a bug or something like that.

**Comment by bluebill1049** [comment]
The way errors get parsed is pretty much like get/set method. 

`test.test.test`

to become

`{test: {test: test{}}}`

**Comment by bluebill1049** [comment]
any update on this issue? or is there anything we can need to patch for resolver?
