### ISSUE TITLE
Using .test with Yup causes erroneous validation

### ISSUE THREAD

**Issue by gCardinal** [react-hook-form/resolvers#37]
I have the following (simplified for this issue) schema:

```
export const schema = yup
    .object()
    .shape({
        useTimePerTurn: yup.boolean(),
        useTimePerGame: yup.boolean(),
    })
    .test('either-timers', 'You must use at least one timer type.', (value) => {
        const { useTimePerTurn, useTimePerGame } = value
        return useTimePerGame || useTimePerTurn
    })
```

With this schema, validation of a form won't work, the form will always be considered valid. I could isolate the issue to this line: https://github.com/react-hook-form/resolvers/blob/master/src/yup.ts#L11. I'm new to both Yup and react-hook-form, but my understanding is that a validation error from a test in yup will not have a path, hence the `parseErrorSchema()` method will return an empty object, breaking the rest of the form validation process.

I threw together a small code sandbox to demonstrate the issue: https://codesandbox.io/s/elegant-brattain-3jp5j?file=/src/App.tsx

And here's a screenshot of the validation error from Yup, notice how `path` is empty since the error was due to a test failing rather than validation constraints: 
![image](https://user-images.githubusercontent.com/1518536/89295084-70f27900-d62e-11ea-9452-7c179ace2c0e.png)

**Comment by bluebill1049** [comment]
`path` is required to assign to an actual `error`.

**Comment by gCardinal** [comment]
In other words, react-hook-form does not support [yup's .test](https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema) method?

**Comment by JeromeDeLeon** [comment]
You could use the [addMethod](https://github.com/jquense/yup#yupaddmethodschematype-schema-name-string-method--schema-void) and put the `test` method inside.

**Comment by JeromeDeLeon** [comment]
Also, side note, instead of using `object().shape({ ... })` you could do this, `object({ ... })` based on [this](https://bitbucket.org/growsuper/tina-admin-middleware-koa/pull-requests/102).

**Comment by bluebill1049** [comment]
Thanks @JeromeDeLeon's clarification.

**Comment by JeromeDeLeon** [comment]
No problem. I think I had legacy code (lol) before that uses addMethod on custom date validation with react hook form and yup but I already deleted it , but I still think it's still possible though.

**Comment by gCardinal** [comment]
> You could use the [addMethod](https://github.com/jquense/yup#yupaddmethodschematype-schema-name-string-method--schema-void) and put the `test` method inside.

Thanks, I'll try the `addMethod` workaround though I still find it weird this library isn't supporting all of yup's features.
