### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by dkulakov1** [react-hook-form/resolvers#38]
Have the same problem as here [react-hook-form/issues/773](https://github.com/react-hook-form/react-hook-form/issues/773)

Are you planning to provide something like **'react-hook-form/dist/index.ie11'** but for **@hookform/resolvers**?

**Comment by bluebill1049** [comment]
yes: https://github.com/react-hook-form/resolvers/issues/38

**Comment by dkulakov1** [comment]
@bluebill1049 
Is it already implemented?
