### ISSUE TITLE
Nested yup schema validation

### ISSUE THREAD

**Issue by iamacook** [react-hook-form/resolvers#41]
I'm currently migrating to react-hook-form and the current yup resolver does recognise yup's [when](https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema) in nested schemas.

I've created an example [here](https://codesandbox.io/s/react-hook-form-validationschema-v6-forked-lvyqm?file=/src/index.js). You should be able to submit the form because the condition has been met, but the resolver doesn't recognise it?

Love the work that you're doing! Thanks in advance for your help!

**Comment by bluebill1049** [comment]
we focus single input validation at all, for dependency validation, you need to use `tirgger`

**Comment by iamacook** [comment]
Thank you for getting back to me so quickly. I apologise for the late reply.

The initial validation was not the issue. Without passing the context to yup, it cannot retrieve the values of fields outside of the embedded schema.

I have since migrated from yup to joi, since you do not need to embed schemas inside schemas if you're data structure is made up of embedded objects.

**Comment by bluebill1049** [comment]
thanks, what's the remaining issue here?

**Comment by iamacook** [comment]
In the schema (taken from the example):

```const schema = yup.object({
  firstName: yup.string().required(),
  test: yup.object({
    location: yup.string().when("firstName", {
      is: "Aaron",
      then: yup.string(),
      otherwise: yup.string().min(10)
    })
  })
});
```

The field 'test.location' in the schema cannot access the value of 'firstName' and returns undefined. So, it isn't possible to use when("xyz", { is: **this condition**... } in embedded yup schemas.

**Comment by bluebill1049** [comment]
I just succesfully submit the form.
<img width="1184" alt="Screen Shot 2020-08-17 at 5 54 42 pm" src="https://user-images.githubusercontent.com/10513364/90371731-bd1fcd80-e0b2-11ea-87df-cecbe5b17816.png">

**Comment by iamacook** [comment]
There should not be a character limit when the first field is 'Aaron'.

```javascript
location: yup.string().when("firstName", {
    is: "Aaron",
    then: yup.string(),
    otherwise: yup.string().min(10)
})
```

![image](https://user-images.githubusercontent.com/20442784/90376839-5cbf6a80-e077-11ea-8538-13d9e1a3ff07.png)

**Comment by bluebill1049** [comment]
![Uploading Screen Shot 2020-08-17 at 7.00.07 pm.png…]()
This is what yup returned.

**Comment by iamacook** [comment]
Maybe I'm confused, and I'm sorry if I am, but it shouldn't be returning that error because the field value is 'Aaron'? There is no character limit when that condition is met.

**Comment by bluebill1049** [comment]
there is no right or wrong here :) we just try to make it work, for RHF we just follow what's yup's returning.

**Comment by iamacook** [comment]
Ok, well the only way I could get it to work was by passing a continuously updated context to yup and that completely goes against the reason for my initial migration (reducing renders). I instead switched to Joi because you don't have to embed schema objects if your data structure has multi-level object(s).

Thank you for looking into this nonetheless. I'm really happy with the performance increase I've got after migrating from Formik!
