### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by dylanhotfire** [react-hook-form/resolvers#42]
This package does not work with IE11. The react-hook-form [latest release](https://github.com/react-hook-form/react-hook-form/pull/2542) looks like they're making efforts to support IE11 until it's unsupported, are we able to release a transpiled version of this package as well?

**Comment by angelolev** [comment]
having an error with yupResolver, I guess it is related with IE11 compatibility. Hope rhf team could improve this

**Comment by bluebill1049** [comment]
can you guys please test out this beta version with IE11? 0.0.7-beta.5?
