### ISSUE TITLE
[ajv] keep showing error when try to validate number

### ISSUE THREAD

**Issue by hypong** [react-hook-form/resolvers#428]
I am using ajv to validate my form and it keep showing error ("must be number") when I try to validate a number field
Is it a bug or did I config it wrongly? 

Here is my config
```
fieldName: {
    type: "number"
}
```
https://codesandbox.io/s/react-hook-form-ajvresolver-forked-81mnf0

Any help will be appreciated

**Comment by bluebill1049** [comment]
the native input text is a string, you want to parse the input value before sending to AJV `valueAsNumber`
