### ISSUE TITLE
Infer types from zod schema

### ISSUE THREAD

**Issue by victormamede** [react-hook-form/resolvers#429]
**Is your feature request related to a problem? Please describe.**
Zod automatically infers the typescript type from schema, so I declare my FieldValues like this:
```typescript
type FieldTypes = z.infer<typeof schema>
```
and then:
```typescript
const {...} = useForm<FieldTypes>({
  resolver: zodResolver(schema),
});
```
But I feel like the useForm hook should be abre to infer the type, since the useForm's resolver uses the generic TFieldValues `Resolver<TFieldValues, TContext>`

**Describe the solution you'd like**
The zodResolver should automatically infer TFieldValues given a zod schema

**Describe alternatives you've considered**
Using `useForm<z.infer<typeof schema>>` but I think this is ugly

**Comment by bluebill1049** [comment]
resolver is a generic function to resolve validation schema results, unless this can be applied to all schema, we probably not going to make except or tight integration with any schema lib, however, you probably build your own custom resolver to achieve that instead. https://codesandbox.io/s/react-hook-form-customresoliver-v7-8mpqw

**Comment by punkpeye** [comment]
@victormamede Did you figure out how to make this work with Zod?
