### ISSUE TITLE
Yup resolver problem with test function

### ISSUE THREAD

**Issue by pom421** [react-hook-form/resolvers#43]
Hello, 

It seems there is a problem with the `yupResolver`, when there is a schema with [`test` function](https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema).

This a CodeSandbox to reproduce the problem: https://codesandbox.io/s/yup-resolver-problem-with-yup-test-function-16r4d?file=/src/App.js

The form example has 3 inputs. The age is required, only here to illustrate that individual field can throw, as expected, an error.
But the `test` function, which checks if email or name are present, does not throw a ValidationError.

The `onSubmit` method shows that there is no error and that the data is an empty object. 😢

**Comment by bluebill1049** [comment]
because `.test` doesn't return `type` from `yup` from my early inspection.

Take a look at this Codesandbox: https://codesandbox.io/s/pedantic-wright-2zp5v?file=/src/App.js

**Comment by bluebill1049** [comment]
similar question here: https://github.com/react-hook-form/react-hook-form/discussions/2576

**Comment by pom421** [comment]
What is type, actually? If it is a name of a particular field, indeed we can't give it since test is built to check multiple fields, so this is a general validation problem.

**Comment by bluebill1049** [comment]
> What is type, actually? If it is a name of a particular field, indeed we can't give it since test is built to check multiple fields, so this is a general validation problem.

then how would RHF know which errors to be inserted?

you probably can help me the following error as well then: 

https://codesandbox.io/s/pedantic-wright-2zp5v?file=/src/App.js

if you run above CSB, you will see the error: 
<img width="324" alt="Screen Shot 2020-08-13 at 10 00 47 pm" src="https://user-images.githubusercontent.com/10513364/90132080-7ed39700-ddb0-11ea-9f1d-d22987317103.png">

**Comment by pom421** [comment]
I suspect that this error happens when RHF tries to populate the errors object and to find where to put the detail. 

But I am surprised that it doesn't work neither if we use "file1" instead of "type" in your code sandbox, as first argument of `test` function.

I am not an expert in Yup, but since the `test` function has a name in first argument, this name could be used has a property in the errors object. This way, the developer coud display this error wherever he wants in React.

But in my initial problem (https://codesandbox.io/s/yup-resolver-problem-with-yup-test-function-16r4d?file=/src/App.js), I want to emphasize that *no Validation Error* is thrown! At the end, the validation passes and an empty object is submitted to the onSubmit. Problems are maybe related but they are different to me.

**Comment by bluebill1049** [comment]
can you debug the `schema.validate(values)` and see what's sort errors its' returning?

**Comment by pom421** [comment]
For some reason, this is due to the context param in the `yupResolver` function. 

https://codesandbox.io/s/yup-resolver-problem-with-yup-test-function-16r4d?file=/src/App.js:451-462

Try it with or without null for the second parameter, and with null, it returns an error object with a key undefined (this key sould be the first parameter of the yup `test` function, in my case globalError). Without this second parameter, there is no error and it returns an empty object for the data, so no clue to guess there was an error.

For information, I also tried with the custom yup resolver as it is described on the site, this time the Validation error is thrown as expected.

https://codesandbox.io/s/yup-resolver-problem-with-yup-test-function-with-custom-yup-resolver-5ibx0?file=/src/App.js

**Comment by bluebill1049** [comment]
so is that an issue with `Yup`? or our usage is incorrect? if that's us, happy to see a PR if you know the fix.

**Comment by pom421** [comment]
I will be glad to help,  but unfortunately, I dont fully understand the `yupResolver` function. For example, how the [context parameter](https://github.com/react-hook-form/resolvers/blob/a4ea13750e82fa3829a982f729c4a33d3c0851ea/src/yup.ts#L49) is retrieved? 

Is this https://react-hook-form.com/advanced-usage#CustomHookwithResolver is the only documentation for writing custom resolver?

**Comment by bluebill1049** [comment]
it's getting invoked by `useForm`, so you saying the issue is due to `context`?

**Comment by bluebill1049** [comment]
curious why context is causing this issue with `Yup`?

**Comment by bluebill1049** [comment]
what if you just invoke `schema.validate(values)`?

**Comment by pom421** [comment]
> what if you just invoke `schema.validate(values)`?

Yes, in this case the Validation Error is thrown as expected. See https://codesandbox.io/s/yup-resolver-problem-with-yup-test-function-with-custom-yup-resolver-5ibx0?file=/src/App.js

This is why I suspect that yupResolver has a bug.

**Comment by bluebill1049** [comment]
![Screen Shot 2020-08-14 at 8 08 04 pm](https://user-images.githubusercontent.com/10513364/90238820-e1d53480-de69-11ea-9cd3-e6d1b6b08d2c.png)

the key is `undefined` tho 🤔

**Comment by pom421** [comment]
> ![Screen Shot 2020-08-14 at 8 08 04 pm](https://user-images.githubusercontent.com/10513364/90238820-e1d53480-de69-11ea-9cd3-e6d1b6b08d2c.png)
> 
> the key is `undefined` tho 🤔

Yes, this is because of  [currentError.path] which returns undefined.

**Comment by bluebill1049** [comment]
that's the issue then. which field this error should be assigned then?

**Comment by pom421** [comment]
```js
[currentError.path || currentError.type || "validation"]: {
    type: currentError.type ?? "validation",
    message: currentError.message
}
```

With something like this, you will always have a key to refer to.

**Comment by bluebill1049** [comment]
what's "validation"? we can't just make up a `type`.

**Comment by bluebill1049** [comment]
is there any way we can return type from `yup.test`?

**Comment by bluebill1049** [comment]
could you create an issue/question there and reference this problem?

**Comment by pom421** [comment]
I my example, the error will be globalError, the first parameter of `test` yup function. So I can "subscribe" to this error in my JSX.

**Comment by pom421** [comment]
> what's "validation"? we can't just make up a `type`.

I have copied/pasted the line above, which mentions the string "validation" as a fallback value for "type" property.

**Comment by bluebill1049** [comment]
is it that an issue with yup, return the key as `undefined`? we can fix it, but it just feels strange return `undefined` as key? don't you think so?

**Comment by pom421** [comment]
It's not that. The undefined is due to the custom resolver and how it rebuilds an error object.

But Yup has sended this: 
```
{
   "name":"ValidationError",
   "value":{
      "name":"",
      "email":""
   },
   "errors":[
      "Email or name are required"
   ],
   "inner":[
      {
         "name":"ValidationError",
         "value":{
            "name":"",
            "email":""
         },
         "type":"globalError",
         "errors":[
            "Email or name are required"
         ],
         "inner":[

         ],
         "message":"Email or name are required",
         "params":{
            "path":"this",
            "value":{
               "name":"",
               "email":""
            },
            "originalValue":{
               "name":"",
               "email":""
            }
         }
      }
   ],
   "message":"Email or name are required"
}
```

I suspect that  "path":"this", is not well evaluated and returns undefined.

**Comment by bluebill1049** [comment]
I will take a deep look at it in the next following days, if u have time please jump in before I do 🙏

**Comment by pom421** [comment]
Thanks Bill! And thanks by the way for sharing us RHF, I really like it! 🎩

I will post an issue and reference this thread.

**Comment by bluebill1049** [comment]
I will sort this out in the next couple days 👍 all good ❤️

**Comment by bluebill1049** [comment]
hey @pmaier983, would you be interested to give a crack on this one?

**Comment by pmaier983** [comment]
So the quick fix for now is to return true (or false 🤷) if the validation passes, and to throw and Error if the validation fails. This will create an error with name 'undefined'... not ideal, but is a good enough patch until I figure out whats going on.

```javascript
const schema = yup
  .object({
    name: yup.string(),
    email: yup.string()
  })
  .test("globalError", "Email and name are required", function (value) {
    if (!_.isEmpty(value.name) && !_.isEmpty(value.email)) {
      return true;
    }
    throw Error("This Broke");
  });
```

**Comment by RNKushwaha022** [comment]
Yup's validation doesn't work as expected even for `required` for file types. Wasted so much time on this to work but nothing worked. Finally removed the file validation from Yup and handled on server side. Still Looking for the solution.

**Comment by bluebill1049** [comment]
> Yup's validation doesn't work as expected even for `required` for file types when using with resolver. Wasted so much time on this to work but nothing worked. Finally removed the file validation from Yup and handled on server side. Still Looking for the solution.

can you share a codesandbox before anyone can help?
