### ISSUE TITLE
AjvResolver cannot handle $schema or $id keys

### ISSUE THREAD

**Issue by vanhumbeecka** [react-hook-form/resolvers#438]
**Describe the bug**
When using the `AjvResolver`, it throws errors when the json-schema has a `$schema` key.
Removing those keys from the schema is the current workaround to get it working.

**To Reproduce**

The example in the `README.md` file does _not_ contain a `$schema` key.
Add it to this example, and watch it 🔥 

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker:
https://codesandbox.io/s/custom-hook-with-resolver-v7-forked-pbh05l?file=/src/App.js

**Expected behavior**
The `$schema` key (as well as `$id`) are official keys according to the json-schema spec.
The resolver should not fail if these keys are present.

**Screenshots**
![Screenshot 2022-07-27 at 11 06 58](https://user-images.githubusercontent.com/4650078/181208615-0f868134-7405-4107-8f59-56e934bb3a57.png)

**Desktop (please complete the following information):**

- OS: MacOS Monterey
- Browser: Firefox
- Version 102

**Comment by bluebill1049** [comment]
Currently not supported, please send a feature request instead and we will monitor how many users would like to support this.
