### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by ArtBIT** [react-hook-form/resolvers#44]
In my project, and even with the very basic typescript boilerplate (i.e. https://github.com/jsynowiec/node-typescript-boilerplate), including @hookform/resolvers into the project breaks the build.

```
> node-typescript-boilerplate@0.0.0 build /code/nodejs/node-typescript-boilerplate
> tsc -p tsconfig.release.json

node_modules/@hookform/resolvers/dist/joi.d.ts:2:17 - error TS2307: Cannot find module '@hapi/joi' or its corresponding type declarations.

2 import Joi from '@hapi/joi';
                  ~~~~~~~~~~~

node_modules/@hookform/resolvers/dist/superstruct.d.ts:2:25 - error TS2307: Cannot find module 'superstruct' or its corresponding type declarations.

2 import Superstruct from 'superstruct';
                          ~~~~~~~~~~~~~

node_modules/@hookform/resolvers/dist/yup.d.ts:2:17 - error TS2307: Cannot find module 'yup' or its corresponding type declarations.

2 import Yup from 'yup';
```

**Comment by ArtBIT** [comment]
Are all devDependencies in package.json truly dev deps?

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/resolvers/issues/20

we are looking for solutions, yes they r dev dependency if you check the package.json.

**Comment by ArtBIT** [comment]
That's what I am saying, shouldn't they be listed as dependencies (not devDependencies) since those packages are imported at runtime, from the dist folder?

**Comment by bluebill1049** [comment]
if they are dependencies, then the bundle size would be tripled right? we need to solve the problem not importing other libs.

**Comment by ArtBIT** [comment]
Since you only seem to need to import type definitions, maybe you could use https://github.com/DefinitelyTyped/DefinitelyTyped ?
@types/joi
@types/yup
@types/superstruct

**Comment by bluebill1049** [comment]
we could try that, i will build a beta version today for you.

**Comment by wolfhoundjesse** [comment]
You can add `skipLibCheck` to your tsconfig for now.
https://github.com/react-hook-form/resolvers/issues/20#issuecomment-695814737

**Comment by jorisre** [comment]
> You can add `skipLibCheck` to your tsconfig for now.
> https://github.com/react-hook-form/resolvers/issues/20#issuecomment-695814737

Or just install the lastest @hookform/resolvers version :)

**Comment by wolfhoundjesse** [comment]
> Or just install the latest version of @hookform/resolvers :)

Oh, when was it fixed? I was having this issue last week.

**Comment by jorisre** [comment]
> > Or just install the latest version of @hookform/resolvers :)
> 
> Oh, when was it fixed? I was having this issue last week.

Since ~19 days ago
https://github.com/react-hook-form/resolvers/releases
