### ISSUE TITLE
Yup errors are swallowed

### ISSUE THREAD

**Issue by marcospassos** [react-hook-form/resolvers#441]
**Describe the bug**
When a field has multiple errors, just the one higher in the hierarchy is reported, despite setting `criteriaMode: 'all'` and `earlyAbort: false`.

**To Reproduce**

1. Open the [sandbox](https://codesandbox.io/s/modest-butterfly-7noyn0?file=/src/App.tsx) 
2. Click on Submit
3. Open the console
4. Notice there is a single error for the items field: "items field must have at least 2 items"
5. Now, uncomment line 45
6. Reload the page
7. See it now reports errors on items that should have been reported along with the minimum number of items requirement

**Codesandbox link (Required)**
https://codesandbox.io/s/modest-butterfly-7noyn0?file=/src/App.tsx

**Expected behavior**
All errors.

**Comment by bluebill1049** [comment]
hook form reconcile errors based on the field name, if you want a group level, you can consider to use trigger('group')

**Comment by marcospassos** [comment]
I've tried that. It doesn't work either:
https://codesandbox.io/s/modest-butterfly-7noyn0?file=/src/App.tsx

**Comment by bluebill1049** [comment]
<img width="978" alt="Screen Shot 2022-08-11 at 8 50 44 am" src="https://user-images.githubusercontent.com/10513364/184036021-4b7a09ec-2f55-40b3-a90d-d9ccc55c6d62.png">

then follow the doc try to debug why it's not trigger the error

```
resolver: async (data, context, options) => {
  // you can debug your validation schema here
  console.log('formData', data)
  console.log('validation result', await anyResolver(schema)(data, context, options))
  return anyResolver(schema)(data, context, options)
},
```

**Comment by marcospassos** [comment]
I can confirm it's an issue related to the Yup resolver:
![image](https://user-images.githubusercontent.com/943036/184037465-9eac38c9-842e-4eab-8df2-92a76d9d49de.png)

Yup correctly report the errors:
https://codesandbox.io/s/yup-forked-0xsspo?file=/src/index.js

![image](https://user-images.githubusercontent.com/943036/184038493-6ec7cbc2-92c8-4ab3-832d-49f1b0e853ff.png)

**Comment by marcospassos** [comment]
I've updated the [code sandbox ](https://codesandbox.io/s/modest-butterfly-7noyn0?file=/src/App.tsx) to make the issue more explicit:
![image](https://user-images.githubusercontent.com/943036/184039059-eff4ef46-d5df-42c1-b389-46773b0fcd1d.png)

**Comment by bluebill1049** [comment]
It doesn't look like the errors object has associated with the field name, going back to the original comment hook form will require errors to be associated with fields.

**Comment by marcospassos** [comment]
Even associating a field name it [doesn't work](https://codesandbox.io/s/modest-butterfly-7noyn0?file=/src/App.tsx:1245-1246):
![image](https://user-images.githubusercontent.com/943036/184039560-62e1da55-7465-4ae0-853e-c629effedaf9.png)

**Comment by bluebill1049** [comment]
I meant the schema, does the schema errors return the field associate path to that field array? Please refer to the source code which i posted above.

**Comment by marcospassos** [comment]
Yes:
![image](https://user-images.githubusercontent.com/943036/184040249-2937fb99-61ca-44e0-b5ae-0d7ed617bcda.png)

Is it because Yup uses square bracket notation? I don't think so, since the errors are correctly reported when no errors above exist.

**Comment by marcospassos** [comment]
That's what [this function](https://github.com/react-hook-form/resolvers/blob/master/yup/src/yup.ts#L14-L39) returns:

![image](https://user-images.githubusercontent.com/943036/184040782-aeac2c7a-4246-4cba-92f5-2822d9255532.png)

All errors are there.

**Comment by marcospassos** [comment]
Ok, I found the problem. The [set](https://github.com/react-hook-form/react-hook-form/blob/730fde6e43b0beb05e60b27d783b5b10a5723640/src/utils/set.ts#L7) method is overriding the item error since it's reported later.

This is the value of [`fieldErrors`](https://github.com/react-hook-form/resolvers/blob/99703e696576ff740edaf91f3cbaa47c84a17654/src/toNestError.ts#L16) at each of the three [iterations](https://github.com/react-hook-form/resolvers/blob/99703e696576ff740edaf91f3cbaa47c84a17654/src/toNestError.ts#L17):
![image](https://user-images.githubusercontent.com/943036/184042497-cd35fe41-6398-4eb3-a2ed-38f04580ef6a.png)

Could you please reopen the issue?
