### ISSUE TITLE
issue: Consistency of global names in UMD modules is expected

### ISSUE THREAD

**Issue by mexvod** [react-hook-form/resolvers#444]
### Version Number

7.34.2

### Codesandbox/Expo snack

https://codesandbox.io/s/determined-black-t75fjv?file=/index.html

### Steps to reproduce

1) If you are trying to build an application through UMD modules that can work directly from the browser, then there will be an error: "r is undefined"

The point is that modules https://unpkg.com/@hookform/resolvers@2.9.7/dist/resolvers.umd.js and https://unpkg.com/@hookform/resolvers@2.9.7/joi/dist/joi.umd.js depend on the namespace reactHookForm 

If you look at the built modules, you can see the dependency on e.reactHookForm

Now if you change the global name of ReactHookForm to reactHookForm in module https://unpkg.com/react-hook-form@7.34.2/dist/index.umd.js everything will work.

### Expected behaviour

Consistency of global names in UMD modules is expected

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jorisre** [comment]
Fixed with https://github.com/react-hook-form/resolvers/pull/449
