### ISSUE TITLE
Infinite type in simple zod resolver

### ISSUE THREAD

**Issue by ChromeGG** [react-hook-form/resolvers#451]
**Describe the bug**
Simple form with Zod resolver is throwing `Type instantiation is excessively deep and possibly infinite.` error

dependencies viersions:

```json
"@hookform/resolvers": "2.9.8",
"react-hook-form": "7.35.0",
"typescript": "4.8.3",
"zod": "3.19.1"
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Clone this repo: https://github.com/ChromeGG/familiada
2. Run `pnpm i`
3. Open `CreateGameForm.tsx` file
4. Uncomment lines 20-23
5. See an error

**Codesandbox link (Required)**
I tried to reproduce this error in CSB but the versions of dependencies were quite old. After the upgrade, it throws many different errors. Probably the templates should be upgraded.

- [Zod resolver](https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-ko5ll) Template

**Expected behaviour**
No TS error.

**Screenshots**
![image](https://user-images.githubusercontent.com/39050595/190875052-1aec74b5-070a-4ba8-810e-5bbf0c67538c.png)

If it's my fault, sorry for the trouble. Thank you for your help!

**Comment by bluebill1049** [comment]
please follow the issue template and reproduce it in a codesandbox and please don't dump the entire project.

**Comment by ChromeGG** [comment]
I tried to reproduce it on codesandbox, stackblitz and on local with clean `pnpm create next-app --ts`, but failed in each case. So something is specific for this environment. No idea what. I have to figure it out myself. Sorry for your trouble. You can close the issue :)

**Comment by tannerbaum** [comment]
@ChromeGG Did you ever figure out what it was for you?

**Comment by jahilliard** [comment]
Any figure this out? Seems like an error when there is depth > 1.

**Comment by njacob1001** [comment]
same issue here

**Comment by jorisre** [comment]
@njacob1001 Please open a new issue.

**Comment by chourabieure** [comment]
same issue here
