### ISSUE TITLE
[SUPERSTRUCT] Coercion is not working

### ISSUE THREAD

**Issue by qlaffont** [react-hook-form/resolvers#453]
**Describe the bug**
I try to use coercion to validate my form, but it tells me that my value is not a number.

**To Reproduce**

1. Create a simple form with one field
2. Type a number 
3. See error

```
const schema = object({
  value: coerce(number(), string(), (value) => parseFloat(value)),
});

 const {
    register,
    handleSubmit,
    control,
    watch,
    formState: { isValid, errors },
  } = useForm<Infer<typeof schema>>({ resolver: superstructResolver(schema), mode: 'all' });

console.log(errors);
```

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker. 

https://codesandbox.io/s/react-hook-form-v6-superstructresolver-forked-00zgkx?file=/src/App.js

*I used the template, but it seems that with recent update codesandbox is not working*

**Expected behavior**
Tell that there is no error and form is valid

**Comment by bluebill1049** [comment]
native input will always produce a string, you can set `valueAsNumber`: true or pass at your schema level to turn string to a number.

**Comment by qlaffont** [comment]
This is what I tried if you check the code @bluebill1049

**Comment by bluebill1049** [comment]
your codesandbox is broken: 
![Screen Shot 2022-10-06 at 5 59 35 pm](https://user-images.githubusercontent.com/10513364/194235430-a7f1ba8b-c1dd-4584-b226-d31f62fd77f5.png)

There is no magic from what hook form is supplied to your scheme: 

you can use the following code to debug the issue

```tsx
resolver: async (data, context, options) => {
  // you can debug your validation schema here
  console.log('formData', data)
  console.log('validation result', await anyResolver(schema)(data, context, options))
  return anyResolver(schema)(data, context, options)
},```

**Comment by mitas1** [comment]
@qlaffont try:
```ts
superstructResolver(schema, { coerce: true })
```
