### ISSUE TITLE
[New Resolver] Implement @sinclair/typebox resolver

### ISSUE THREAD

**Issue by qlaffont** [react-hook-form/resolvers#454]
**Describe the solution you'd like**
It will be nice to implement `@sinclair/typebox` resolver. This type validation is used on fastify (node framework). It will be nice to implement it to have validation system identical between back and front. 

https://github.com/sinclairzx81/typebox#compiler

**Comment by ziyak97** [comment]
Is the implementation of this feature currently under consideration for inclusion in this library? Are contributions being accepted to facilitate its availability?

**Comment by jorisre** [comment]
Heya 👋🏻 I just open a [PR #526](https://github.com/react-hook-form/resolvers/pull/526) for TypeBox resolver.
Feel free to review ✌🏻
