### ISSUE TITLE
Zod resolver is crashing while validation Dayjs values

### ISSUE THREAD

**Issue by JosueGalRe** [react-hook-form/resolvers#458]
**Describe the bug**
Hi! I'm having some issues while trying to validate Dayjs values with Zod. 
The resolver is crashing while trying to validate a value (TypeError: Cannot read properties of undefined (reading 'length')), the error doesn't occurs if the zod schema value is set to z.any(). However, this occurs in the zodResolver (shown in the screenshots below)

**To Reproduce**

1. Click on the "Test" button.
2. Open dev tools

**Codesandbox link (Required)**
https://codesandbox.io/p/sandbox/thirsty-rain-zfmuwr // Vite
https://codesandbox.io/s/funny-poincare-l5nctl // CRA

**Expected behavior**
The validation "The Coach field is required" should be shown on screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/6238927/198147194-3fdc42ed-c647-4950-9391-80d72ea66faa.png)
![image](https://user-images.githubusercontent.com/6238927/198147363-e40f889c-50c2-457e-87c2-ad153661ac59.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Vivaldi/Chromium
- Version: 5.5.2805.38/106

**Comment by jorisre** [comment]
Thank for reporting the issue. We don't recommend to pass complex object like dayjs, moment etc.. into react-hook-form

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api/useform

> It's recommend to avoid including custom object which contains prototype methods as the defaultValues, such as moment, luxon and etc.

**Comment by JosueGalRe** [comment]
Makes completely sense, didn't read that rule before. Thanks for the clarification and the quick response!

**Comment by peter-goodfill** [comment]
I have encountered this issue and I am curious, why is this. I triggered this error by using simple object like:
```
{
  countryCallCode: string;
  nationalNumber: string;
}
```

What is the best practice to avoid this error. 

First idea I got is to just serialize this to string and then parse it when I need it. But it is not very elegant and feels hacky.

Thanks for help!
