### ISSUE TITLE
Type '{}' provides no match for the signature '(): Object'.

### ISSUE THREAD

**Issue by GoncharenkoIgor** [react-hook-form/resolvers#461]
**Describe the bug**
I've created simple form using useForm hook, passing an object with yupResolver(baseSchema) as resolver property. But I get an error which I can't understand and fix. Here it is.
`TS2322: Type '<TFieldValues extends FieldValues, TContext>(values: TFieldValues, context: TContext | undefined, options: ResolverOptions<TFieldValues>) => Promise<...>' is not assignable to type 'Resolver<FormDataType, object>'.   Types of parameters 'options' and 'options' are incompatible.     Type 'ResolverOptions<FormDataType>' is not assignable to type 'ResolverOptions<{ programs: { id: string; name: string; duration: string; overview: { toJS: {}; getAllowUndo: {}; getCurrentContent: {}; getUndoStack: {}; getRedoStack: {}; getSelection: {}; getDecorator: {}; isInCompositionMode: {}; ... 102 more ...; findLastKey: {}; }; sessionPlan: { ...; }; }[]; }>'.       Type '{ id: string; name: string; duration: string; overview: { toJS: {}; getAllowUndo: {}; getCurrentContent: {}; getUndoStack: {}; getRedoStack: {}; getSelection: {}; getDecorator: {}; isInCompositionMode: {}; ... 102 more ...; findLastKey: {}; }; sessionPlan: { ...; }; }[]' is not assignable to type 'PersonalProgram[]'.         Type '{ id: string; name: string; duration: string; overview: { toJS: {}; getAllowUndo: {}; getCurrentContent: {}; getUndoStack: {}; getRedoStack: {}; getSelection: {}; getDecorator: {}; isInCompositionMode: {}; ... 102 more ...; findLastKey: {}; }; sessionPlan: { ...; }; }' is not assignable to type 'PersonalProgram'.           The types of 'overview.toJS' are incompatible between these types.             Type '{}' is not assignable to type '() => Object'.               Type '{}' provides no match for the signature '(): Object'.`

**To Reproduce**

1. Create some schema
2. Pass it to yupResolver as resolver property inside props object in useForm hook

**Codesandbox link (Required)**
Here's a sandbox, but for some reason there's no this error.

- [Codesandbox](https://codesandbox.io/s/react-hook-form-resolver-forked-74xc8f?file=/src/App.tsx:1173-1174)

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/49438802/199729505-f27fe4c2-4e2f-4abd-9db0-08e54ce44d98.png)

**Desktop (please complete the following information):**

- OS: macOS Monterey Version 12.6

**Comment by bluebill1049** [comment]
<img width="687" alt="Screenshot 2022-11-04 at 7 57 35 am" src="https://user-images.githubusercontent.com/10513364/199832627-539ba263-ffbd-47c0-99be-6a9234825052.png">

please provide a reproducible codesandbox.

**Comment by GoncharenkoIgor** [comment]
@bluebill1049 here it is, managed to reproduce an error
https://codesandbox.io/s/react-hook-form-resolver-forked-l6lwqr?file=/src/App.tsx

**Comment by bluebill1049** [comment]
Tested with the latest version is working as expected: https://codesandbox.io/s/react-hook-form-resolver-forked-b7o2o5?file=/src/App.tsx

![Screenshot 2022-11-07 at 6 05 02 pm](https://user-images.githubusercontent.com/10513364/200245867-797ded51-a834-4a73-a99e-a91de42b2fb6.png)
