### ISSUE TITLE
[ajv] Transform data before validation

### ISSUE THREAD

**Issue by elton-okawa** [react-hook-form/resolvers#471]
**Is your feature request related to a problem? Please describe.**
I have a dynamically generated form based on a JSON Schema and I’m facing problems when we have `optional` fields with validations, as every registered input has its own key on the form values, they are validated and fails even though visually they are empty.

[CodeSandbox example](https://codesandbox.io/s/react-hook-form-optional-fields-w1bo3k?file=/src/index.js)
In this example, we have an optional field `description` which, if defined, needs to have a minimum length of 5 characters.
From the user perspective, an optional field can be left empty but it doesn’t work here because the `description` field exist on the submitted values and consequently it’s validated.
Another example might happen with phone number or email, they might be optional but if they are provided, they must follow a pattern.

**Describe the solution you'd like**

Allow the `ajvResolver` receive an function to transform the form values before validation.
I like this solution because:
- there is no magic happening behind the scenes (the user will define the function)
- we can use the same function before submitting the data

For example:
```jsx
function transform(values) {
  // clone and modify form values before validation, like removing empty fields
  return modifiedValues;
}

const { handleSubmit }= useForm({
  resolver: ajvResolver(schema, transform)
});

<form onSubmit={handleSubmit((data) => console.log(transform(data))}>
  ...
</form>
```

**Describe alternatives you've considered**

I have considered the following options:

1. Button to hide and show the optional field
    - I could leverage the unregister on unmount feature as unregistered fields can be removed from the form values
    - It works but I think the UX would become a bit worse as every optional fields would need to click a button to be filled
2. Custom controller to register and unregister field based on input value
    - register if `input !== ''` and unregister otherwise
    - It also works but with some concerns
        - unregistering a field made the entire form re-render (not sure if it’s the expected behavior or I’m doing something wrong)
        - I felt that I was going further on a fragile solution (not the expected way to use the library)

**Additional context**

Kind of related to [react-hook-form #9278](https://github.com/react-hook-form/react-hook-form/issues/9278) but for `ajv` validations
For now I customized the official resolver like the solution I’ve described, I thought that I might be useful to someone else and I could receive feedback about the way that I’m solving the problem.

I’m also willing to open up a PR if it seems a good solution 🤓

**Comment by jorisre** [comment]
@elton-okawa Do you find a way to manage this?

**Comment by elton-okawa** [comment]
@jorisre I basically implemented my suggested solution, I'm planning to open up a PR with some usage documentation this week.
