### ISSUE TITLE
Validator transformation not reflected on the input

### ISSUE THREAD

**Issue by ToddAlvord** [react-hook-form/resolvers#476]
**Describe the bug**
Validator transformations/modifications aren't reflected in the input field

**To Reproduce**

1. Create a validator that also transforms its input ex `Joi.string().required().trim(true).replace(/ +/g, " ")`
2. Go to codesandbox below. Enter a string that has multiple spaces along with text.
3. Submit the form
4. The alert shows the correctly trimmed and replaced value, but the form field still shows the original input.

**Codesandbox link**
[Codesandbox](https://codesandbox.io/s/react-hook-form-joiresolver-v6-forked-5b4h3k?file=/src/index.js)

**Expected behavior**
Since the value that is validated against has changed, I would expect the input field to show the new trimmed value.

**Desktop (please complete the following information):**

- OS: Mac OS 13.0.1
- Browser: Brave
- Version: Latest

I'd be willing to work on a PR myself if someone could provide an overview of the steps I'd need to take.

**Comment by bluebill1049** [comment]
Schema validation is one-way data validation, it doesn't go back and change input.

**Comment by ToddAlvord** [comment]
But in Joi it isn't one way validation, the input != output

**Comment by bluebill1049** [comment]
Then it's a limitation then, hook form only sends data and validates against the schema.
