### ISSUE TITLE
ZodResolver with zod discriminated union does not allow setting a 'defaultValues' of type inferred from the discriminated union

### ISSUE THREAD

**Issue by jz-dot-meng** [react-hook-form/resolvers#486]
**Describe the bug**
When using a zodResolver with a discriminated union, it seemingly resolves to the first discriminated union type and does not allow for a defaultValue to be set as a variable of the type inferred from the discriminated union

**To Reproduce**

1. Create a zod discriminated union
2. In the React Component, create a useForm taking the discriminated union as the resolver using zodResolver
3. Pass as a prop into the React Component a variable of the type inferred from the discriminated union
4. Attempt to set the prop as a defaultValue

**Codesandbox link (Required)**
- [Zod resolver with discriminated union](https://codesandbox.io/s/zodresolver-issue-0zk37k?file=/src/App.tsx) 

**Expected behavior**
The defaultValue should be able to accept a variable of the type inferred from the discriminated union - it works when explicitly defining the defaultValue using an object following any of the union types, but not a variable that could be any of the union types

**Screenshots**
<img width="687" alt="image" src="https://user-images.githubusercontent.com/78452670/210539415-213d1661-5999-4101-9ba1-30e59d0bf0df.png">

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Chrome
- Version Chromium: 108.0.5359.128

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by bluebill1049** [comment]
sorry for the incorrect tagging, I miss the CSB link. I think this is a limitation that we have brought up a few times. This is relevant issue: https://github.com/react-hook-form/react-hook-form/issues/8815

**Comment by jz-dot-meng** [comment]
thanks for the reply, I'll look into a workaround!
