### ISSUE TITLE
Validate callback not invoked when using zodResolver

### ISSUE THREAD

**Issue by kendall-wahnschaffe** [react-hook-form/resolvers#491]
**Describe the bug**
When using zodResolver, the validate function isn't invoked

In the below example, one only need comment out the resolver and the validate function is called and logs correctly.

**To Reproduce**
```javascript
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";

const schema = z.string();

export default function App() {
  const { register, handleSubmit } = useForm({
    mode: "onChange",
    resolver: zodResolver(schema)
  });
  const onSubmit = (data) => console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input
        {...register("example", {
          validate: (val) => {
            console.log("validate function");
            return true;
          }
        })}
      />

      <input type="submit" />
    </form>
  );
}
```

**Codesandbox link (Required)**
https://codesandbox.io/s/clever-johnson-l79x4m

**Expected behavior**
Should invoke the validate function

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome
- Version: 108.0.5359.124

**Comment by bluebill1049** [comment]
> A resolver can not be used with the built-in validators

https://react-hook-form.com/api/useform

please refer to the doc and keep your validation source of truth in either resolver or build-in validators.

**Comment by kendall-wahnschaffe** [comment]
You are totally right I missed that thank you! 

For anyone that sees this in the future, what I ended up needing to do was using [Zod's `refine`](https://github.com/colinhacks/zod#refine) method to put the validation logic there.
