### ISSUE TITLE
Zod Resolvers doesn't respect 'mode' option

### ISSUE THREAD

**Issue by ollie-bud** [react-hook-form/resolvers#499]
**Describe the bug**
The Zod resolver doesn't seem to respect the `mode` option. It only revalidates on submit.

**To Reproduce**

1. Submit form - Error is shown
3. Update field so age above "10" - Error is still shown
5. Hit submit - Error is cleared
7. Add an invalid value - '3'
8. Error is not shown
9. Submit form - error is shown

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-b2u7xw?file=/src/App.js

**Expected behavior**
The 'mode' flag should cause the form to continually keep testing against the zod schema

**Additional context**
Thank you so much for the amazing work! Sorry if this has already been posted, I couldn't see another

**Comment by bluebill1049** [comment]
![Screenshot 2023-02-01 at 11 59 49 am](https://user-images.githubusercontent.com/10513364/215919185-41c243b7-9ef3-4af5-bdf8-e2a77e73909b.png)

plz fix your csb first

**Comment by ollie-bud** [comment]
Heya! 👋  It seems all seems okay my end 🤔 

That's definitely my code on the left, but not sure what url/page you've got on the right

Added a video https://user-images.githubusercontent.com/119597653/216021911-e4202c68-a6c5-4c65-b7af-8e22aa10d41f.mov (using (https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-b2u7xw?file=/src/App.js)

Thank you so much for getting back to me so fast! Supper happy to create another sandbox, but not sure why the first wasn't working for you

**Comment by bluebill1049** [comment]
It's working now, could you use all the latest versions in that CSB? Those versions you had it's quite old and outdated.

**Comment by ollie-bud** [comment]
Hopefully the third times the charm 🤞 Incredibly sorry for the time waste my side. Updated all the packages. 

https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-b2u7xw?file=/src/App.js

**Comment by bluebill1049** [comment]
No worries @ollie-bud thanks for being so polite 🙏 

could you try to run this debug code? see if you can figure out the issue

https://react-hook-form.com/api/useform

```tsx
resolver: async (data, context, options) => {
  // you can debug your validation schema here
  console.log('formData', data)
  console.log('validation result', await anyResolver(schema)(data, context, options))
  return anyResolver(schema)(data, context, options)
},
```

![Screenshot 2023-02-02 at 10 11 18 am](https://user-images.githubusercontent.com/10513364/216187652-67dedfe1-4b27-46e5-bacf-76b84e7e7fb2.png)

also notice the error doesn't have a key name

`{"":{"message":"Age is not above 10","type":"custom"}}` 

which made it impossible for react hook form to be associated with any input field, so most likely the issue is related to your schema.

**Comment by ollie-bud** [comment]
That debugging script was _really_ helpful - thank you! Here's what I've learned:

You were absolutely correct about the `""` from zod being a problem. Adding a path (which is the same as a value in the form) works completely as expected 🎉 Literally flawless 🎉🎉🎉

```tsx
const schema = z
  .object({ age: z.string() })
  .partial()
  .refine(({ age }) => age > 10, {
    // 👇 
    path: ["age"],
    // ☝️ 
    message: "Age is not above 10"
  });
```

However, adding a path that's _not_ present in the form - or omitting it completely has the same "only works on submit" error. What's odd is that each keypress _does_ trigger the resolver as expected, and the resolver _errors_ as expected - but it looks like that doesn't get reported to the `errors` property.

I _was_ planning on using Zod for multi-component validation ("Please check two or more options" style problems) - but I don't think this is quite the right approach for that.

I kinda wanted to have errors at _form_ level, rather than input level.

Thank you so much for your incredible help and patience.

**Comment by bluebill1049** [comment]
If you want all the errors to keep flushing down, then perhaps you want to use a trigger at the form level, or perhaps react hook form is not what you correct choice. A fully controlled form such as Formik will always return all the errors and re-render on each keystroke, hence you will always have the latest error state and everything else.

**Comment by jorisre** [comment]
Seems to be solved
