### ISSUE TITLE
`zodResolver` doesn't propagate type change within `.transform()`

### ISSUE THREAD

**Issue by frontendlane** [react-hook-form/resolvers#500]
**Describe the bug**
I wish to transform a form value from string to number during `.transform()` but I get a TypeScript error.

**[Codesandbox link](https://codesandbox.io/s/zodresolver-doesnt-propagate-type-change-within-transform-lgxzxb?file=%2Fsrc%2FApp.tsx)**

<img width="521" alt="image" src="https://user-images.githubusercontent.com/43588352/216074608-97e72a91-c128-438c-abff-84b1af0e9ae8.png">

**Expected behavior**
I expect `handleSubmit` to expect the transformed type, not the type specified in `defaultValues`.

**Comment by bluebill1049** [comment]
you can subscribe to this issue: https://github.com/react-hook-form/react-hook-form/issues/9600
