### ISSUE TITLE
Yup v1 support

### ISSUE THREAD

**Issue by Systerr** [react-hook-form/resolvers#508]
Hi. For now react-hook-form/resolvers supports yup v0.32
But recently yup v1 was released.  

It contain breaking changes https://github.com/jquense/yup/issues/1906

Will be good to have support of yup v1 too

**Comment by bluebill1049** [comment]
I don't think those breaking changes affect us. Could you try it out and let us know?

**Comment by AlexanderBadak** [comment]
I tried and ran into an issue regarding ObjectSchema type matching.

type Resolver extends only Yup.AnyObjectSchema butI think  it should be Yup.ObjectSchema or at least both.

**Comment by jbpenrath** [comment]
It appears that types are broken.

```
node_modules/@hookform/resolvers/yup/dist/types.d.ts:3:23 - error TS2307: Cannot find module 'yup/lib/Lazy' or its corresponding type declarations.

3 import type Lazy from 'yup/lib/Lazy';
                        ~~~~~~~~~~~~~~

node_modules/@hookform/resolvers/yup/dist/types.d.ts:4:78 - error TS2344: Type 'T["validate"]' does not satisfy the constraint '(...args: any) => any'.

4 declare type Options<T extends Yup.AnyObjectSchema | Lazy<any>> = Parameters<T['validate']>[1];
                                                                               ~~~~~~~~~~~~~

node_modules/@hookform/resolvers/yup/dist/types.d.ts:4:78 - error TS2536: Type '"validate"' cannot be used to index type 'T'.

4 declare type Options<T extends Yup.AnyObjectSchema | Lazy<any>> = Parameters<T['validate']>[1];
                                                                               ~~~~~~~~~~~~~


Found 3 errors in the same file, starting at: node_modules/@hookform/resolvers/yup/dist/types.d.ts:3
```

**Comment by eucciferri** [comment]
Hi!

I also have a problem with yup v1 and yupResolver

![image](https://user-images.githubusercontent.com/38674416/222295196-71dc1985-b753-4ec1-96e2-6adc1e04dba5.png)

**Comment by Svish** [comment]
Upgrading to `yup@1` not possible for us either until this gets fixed.

For a transition period, maybe add a separate resolver for this new version and mark the old one as deprecated somehow?

**Comment by slashwhatever** [comment]
Definitely breaking changes. 

There's no longer an exported `SchemaOf` and trying to just change that to `ObjectSchema` as you would with v1 yup, generates even more TS errors

**Comment by Svish** [comment]
Any estimate on when this change could be released?

(I suppose it should be a major change, as it's a breaking change for `yup` 🤔)

**Comment by ethanhoroschak** [comment]
> It appears that types are broken.
> 
> ```
> node_modules/@hookform/resolvers/yup/dist/types.d.ts:3:23 - error TS2307: Cannot find module 'yup/lib/Lazy' or its corresponding type declarations.
> 
> 3 import type Lazy from 'yup/lib/Lazy';
>                         ~~~~~~~~~~~~~~
> 
> node_modules/@hookform/resolvers/yup/dist/types.d.ts:4:78 - error TS2344: Type 'T["validate"]' does not satisfy the constraint '(...args: any) => any'.
> 
> 4 declare type Options<T extends Yup.AnyObjectSchema | Lazy<any>> = Parameters<T['validate']>[1];
>                                                                                ~~~~~~~~~~~~~
> 
> node_modules/@hookform/resolvers/yup/dist/types.d.ts:4:78 - error TS2536: Type '"validate"' cannot be used to index type 'T'.
> 
> 4 declare type Options<T extends Yup.AnyObjectSchema | Lazy<any>> = Parameters<T['validate']>[1];
>                                                                                ~~~~~~~~~~~~~
> 
> 
> Found 3 errors in the same file, starting at: node_modules/@hookform/resolvers/yup/dist/types.d.ts:3
> ```

Was there a fix to the `import type Lazy from 'yup/lib/Lazy';` issue? I see it is no longer exported by Yup v1

**Comment by jorisre** [comment]
@ethanhoroschak Please open a new issue if it's yup resolver related. It seems to be related to Yup itself

**Comment by ethanhoroschak** [comment]
@jorisre My mistake! Found the open issue for Yup if anyone else stumbles on this thread for the same search query: https://github.com/jquense/yup/issues/1954
