### ISSUE TITLE
yupResolver fails to validate an uncontrolled field that depends on a controlled field value.

### ISSUE THREAD

**Issue by rsplithof** [react-hook-form/resolvers#52]
Hi!

I hope you can help me solve the problem i'm facing. 

I am trying to add validation rules to an uncontrolled field, based on the value of a controlled select (in my case a `react-select`). 
When the value of the select changes to a particular value (in this case 'yes'), the other field needs get the `required` validation rule added.

Sandbox example: https://codesandbox.io/s/react-hook-form-yup-validation-crhzk

**How to reproduce**
- Switch the 'controlled' select to the value 'Yes'
- Hit the 'submit' button.

**What i expected**
- The 'Uncontrolled' field should be required.
- An error message should be displayed in the console.

**What happens**
- The value of the select is never filled here (https://codesandbox.io/s/react-hook-form-yup-validation-crhzk?file=/src/schema.js:349-394)
- But when typing 'yes' in the 'Other field' (another uncontrolled field) and hit the submit button it works as expected.

Could you tell me what i'm doing wrong?

**Comment by bluebill1049** [comment]
perhaps you want to use `trigger` for external depend field?

**Comment by rsplithof** [comment]
Could you provide me an example how it should be implemented? I tried to add `trigger('unControlled')` in the `onChange` method of the `Controller` but the `onChange' is never triggered when changing the select value 🤷‍♂️ . Example:
https://codesandbox.io/s/react-hook-form-yup-validation-crhzk?file=/src/App.js:893-930

**Comment by rsplithof** [comment]
Never mind, thanks for your time :v:. 

I've managed to fix it by defining the `controlled` yup field as an object 😅. Because `react-select` returns an object as value.
**before**
controlled: yup.string().required(),

**after**
  controlled: yup.object().shape({
    value: yup.string().required(),
    label: yup.string().required(),
  }),
