### ISSUE TITLE
Typing error with yupResolver v3 and yup v1

### ISSUE THREAD

**Issue by eucciferri** [react-hook-form/resolvers#535]
Hello team!

I have the following type error when I'm trying to use yupResolver v3 and yup v1.

```
import * as yup from 'yup';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';

const formSchema = yup.object({
  name: yup.string().required(),
});
type FormData = yup.InferType<typeof formSchema>;

export const Test = () => {
  const methods = useForm<FormData>({ resolver: yupResolver(formSchema) });

  return (
    <div>
      <h2>Test</h2>
    </div>
  );
};
```

![image](https://user-images.githubusercontent.com/38674416/229658916-fdeb1c05-10a6-4ff1-8c7d-2ff7f3d5afea.png)

![image](https://user-images.githubusercontent.com/38674416/229658943-20579947-5895-4c1e-ac28-86ceb7a481ec.png)

**Comment by jorisre** [comment]
Can you provide a codesandbox with the issue please?

**Comment by eucciferri** [comment]
Hello @jorisre! I've just realized that there was a problem between my turborepo and the apps on it
