### ISSUE TITLE
ZodResolver schema types are not assignable

### ISSUE THREAD

**Issue by gino** [react-hook-form/resolvers#540]
Hi there,

I am trying to use the `zodResolver` in combination with my Zod schema, but unfortunately it is giving me type errors:

<img width="1081" alt="CleanShot 2023-04-09 at 12 26 01@2x" src="https://user-images.githubusercontent.com/23482089/230767504-09dba268-9fde-4b27-afc0-2dfbaf2ff9d1.png">

```json
"zod": "^3.21.4",
"react-hook-form": "^7.43.9",
"@hookform/resolvers": "^3.0.1",
"typescript": "^5.0.4",
```

I am not quite sure why this is happening. Maybe I am using versions that are incompatible.

Hope someone is able to help me out, I'd appreciate it, thanks!

**Comment by gino** [comment]
This was an issue with mismatching zod versions with other workspaces in a pnpm monorepo.

**Comment by azimari-toure-ikbal** [comment]
> This was an issue with mismatching zod versions with other workspaces in a pnpm monorepo.

I'm sorry to bring this up again, but how did you solve it? I myself have a project with pnpm and I got this strange error. Rn my project is using zod 3.22.2
