### ISSUE TITLE
Yup root object checks are not forwarded to root

### ISSUE THREAD

**Issue by BANOnotIT** [react-hook-form/resolvers#541]
**Describe the bug**
Yup checks on root schema object are interpreted as `errors[""]` instead of `errors.root`

**To Reproduce**

1. Go to https://codesandbox.io/s/suspicious-solomon-90yn1g?file=/src/App.tsx
2. Enter: First name: `May`, Second name: `Day`
3. Click on enter
4. Go to console, see log: `{ secondName: ..., "": ... }`

**Expected behavior**
Error messages on root object should be on root error.

**Comment by bluebill1049** [comment]
hook form is field level by default, you can try `trigger` API if the errors at root does appear.

**Comment by BANOnotIT** [comment]
But there's no `""` in types. Only `root`: https://github.com/react-hook-form/react-hook-form/blob/master/src/types/errors.ts#L48-L54

I don't really get how I should handle these root object checks if documentation and types of library states there's no `""` field but there's `root` field.

**Comment by jorisre** [comment]
@BANOnotIT , as mentioned by @bluebill1049 , what you are experiencing is typical behavior for field level validation. The issue is that your validation for _"when"_ is not linked to a specific field or path, resulting in the error message `{"": "error"}`.

To resolve this, you need to provide a Yup error with a specified path. A solution to this issue can be found in the example provided, where `ctx.createError` is used to define the error path.

```ts
.when("$validate", {
    is: true,
    then: (schema) =>
      schema.test("test-id", "test-description", (value, ctx) => {
        return (
          value?.firstName === "John" ||
          ctx.createError({ path: "your-field-path", message: "your custom error message" })
        );
      })
  })
```

**Comment by BANOnotIT** [comment]
So I should create a special "dummy" field in my hook form fields interface to pass error there?

**Comment by BANOnotIT** [comment]
@jorisre where can I find documentation on how `formState.errors.root` work?

**Comment by michaelschufi** [comment]
I have a similar issue with zod. With zod I can also define the path. If I choose a path like `["startIsBeforeEnd"]`, then `formState.errors` is `{errors: {startIsBeforeEnd: {...}}}`. But if I choose `["root", "startIsBeforeEnd"]`, it's not forwarded to the `formState.errors` is just empty.

Of course, I can use something like `["form", "startIsBeforeEnd"]`. But I don't want to type a mock input field just to fix the typing. This will create confusion for different developers. Additionally, react-hook-form already has something for that, the `root` key in `formState.errors`. The `setError` documentation says that `root.myOwnError` can be used for form-level errors.

So, why can't we just forward the errors to `formState.errors.root`?
