### ISSUE TITLE
Zod array length validation issues with `useFieldArray`

### ISSUE THREAD

**Issue by vimtor** [react-hook-form/resolvers#566]
**Describe the bug**

Zod array length validation does not trigger when using the `append` method from `useFieldArray`.

**To Reproduce**

1. Use `zod` and `@hookform/resolvers` for validation.
2. Create a field using `useFieldArray`.
3. Add the `zod` schema for this field and set a minimum length for the array length AND a validation for the objects in the array.
4. Submit the empty form to trigger the errors in the form since this field is empty. You see the proper validation error.
5. Add a new field to the array
6. The error still persists

**Codesandbox link (Required)**

https://codesandbox.io/s/react-hook-form-array-length-error-zod-b92w1t

**Expected behavior**

I should be able to validate the array length and its contents using 

**Screenshots**

https://github.com/react-hook-form/react-hook-form/assets/36263538/949d8419-bc07-42a8-8b81-4973dbe9ea0e

**Desktop (please complete the following information):**

- OS: macOS 13.3.1
- Browser Chrome
- Version 113.0.5672.126

**Comment by Kirdock** [comment]
Also came to this error. The missing update is not the only thing that is wrong here.
The field array errors should be put into a "root" object.
With the current implementation of `zodResolver`, it always sets `message` and `type` for the field array and if this happens, all the other errors of its items are gone.

**Comment by jorisre** [comment]
You need to manually invoke the `trigger` method when adding to the field array. Validation doesn't occur automatically when a new field is registered.

https://codesandbox.io/s/react-hook-form-array-length-error-zod-forked-zjx7g7?file=/src/App.tsx

**Comment by vimtor** [comment]
Hi @jorisre!

I'm not trying to be mean, and I am super grateful that you and others developed `react-hook-form`. It's such a great library.

However, I think that the fact that the `trigger` is not invoked automatically when adding to a field array is in fact the issue. It seems to me that invoking the `trigger` manually is a workaround.

Thank you.
