### ISSUE TITLE
Type 'ResolverOptions<FormValues>' is not assignable to type 'ResolverOptions<{..............}>'

### ISSUE THREAD

**Issue by bezuglyyvlad** [react-hook-form/resolvers#574]
**Describe the bug**
TS2322: Type 'Resolver<{ ......... }, any>' is not assignable to type 'Resolver<FormValues, any>'.   Types of parameters 'options' and 'options' are incompatible.     Type 'ResolverOptions<FormValues>' is not assignable to type 'ResolverOptions<{ ......... }>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.       Type '{ ............. }' is not assignable to type 'FormValues'.

**To Reproduce**

1. Update to 3.1.1 version
2. See error in react-hook-form useForm<FormValues>({resolver: ....... })

CSB
https://codesandbox.io/s/react-hook-form-typescript-forked-3c7fy9?file=/src/index.tsx

**Comment by bezuglyyvlad** [comment]
> Could you provide some more detail with a reproducible CSB? thanks

added CSB

**Comment by henrikvolmer** [comment]
> > Could you provide some more detail with a reproducible CSB? thanks
> 
> added CSB

You cast your `useForm` to the wrong type.

https://codesandbox.io/s/react-hook-form-typescript-forked-34kq9w?file=/src/index.tsx

**Comment by bezuglyyvlad** [comment]
> > > Could you provide some more detail with a reproducible CSB? thanks
> > 
> > 
> > added CSB
> 
> You cast your `useForm` to the wrong type.
> 
> https://codesandbox.io/s/react-hook-form-typescript-forked-34kq9w?file=/src/index.tsx

**Comment by henrikvolmer** [comment]
> > > > Could you provide some more detail with a reproducible CSB? thanks
> > > 
> > > 
> > > added CSB
> > 
> > 
> > You cast your `useForm` to the wrong type.
> > https://codesandbox.io/s/react-hook-form-typescript-forked-34kq9w?file=/src/index.tsx
> 
> Why, if I don't have to write schema for every form field? The form field cannot be undefined in my case

Then your schema fields should be required:

https://codesandbox.io/s/react-hook-form-typescript-forked-xj8fhw?file=/src/index.tsx

**Comment by mtr1990** [comment]
3.1.0 is OK

3.1.1 many issue

<img width="2270" alt="Screenshot 2023-06-14 at 14 53 00" src="https://github.com/react-hook-form/resolvers/assets/13531993/622eace0-c0a4-43b5-b0fd-bee1f31e00ae">

**Comment by jorisre** [comment]
Types are inferred from the Yup schema so remove `<FormValuesProps>` from `useForm`

**Comment by mtr1990** [comment]
@jorisre 

When I remove `<FormValuesProps> ` from `useForm`
<img width="2189" alt="Screenshot 2023-06-14 at 15 15 28" src="https://github.com/react-hook-form/resolvers/assets/13531993/cafaa307-921f-4102-821e-fcf3c9c3df37">

it says data type error in `<FormProvider methods={methods} onSubmit={handleSubmit(onSubmit)}>`

When I remove `FormValuesProps` from `data:FormValuesProps`
<img width="2196" alt="Screenshot 2023-06-14 at 15 15 46" src="https://github.com/react-hook-form/resolvers/assets/13531993/7a86ec82-05b2-4c75-9f35-74eedef6af62">

it says data type error in  
```
 const onSubmit = useCallback(
    async (data) => {
```

**Comment by jorisre** [comment]
Here is the updated release note, sorry for the mistake, it should be at least a minor version instead of a patch

https://github.com/react-hook-form/resolvers/releases/tag/v3.1.1

**Comment by jorisre** [comment]
@mtr1990 Can you provide a CodeSandbox with your issue? You probably don't need `useCallback`

**Comment by mtr1990** [comment]
No longer gives error when removing `useCallback `

```
  const onSubmit = handleSubmit(async (data) => {
    try {
      await new Promise((resolve) => setTimeout(resolve, 500));
      reset();
      onClose();
      console.info('DATA', data);
    } catch (error) {
      console.error(error);
    }
  });
```

Just confirm function `handleSubmit` will not work in `useCallback`. I will eliminate the time thinking about this.

Thanks for your help :D

**Comment by mtr1990** [comment]
This is the problem. Old code can be kept, but tighter constraints are needed.


```
  const defaultValues = {
    rating: null,
    review: '',
    name: '',
    email: '',
  };
```

3.1.0 `rating: Yup.mixed().required('Rating is required'),`
3.1.1 `rating: Yup.number().required('Rating is required').nullable()`

<img width="2157" alt="Screenshot 2023-06-14 at 15 46 36" src="https://github.com/react-hook-form/resolvers/assets/13531993/4f3c1b53-31db-4640-a378-d8f3e2c419f0">

**Comment by mtr1990** [comment]
Hi,

I think this is a different problem with types. When data depends on `schema`.

My case has 4 fields:
- title
- description
- content
- metaTitle


But I just want to validate for 2 fields `title`, `description`

The remaining 2 fields are `content`,`metaTitle` does not recognize the type

You can check here:
https://codesandbox.io/s/keen-snyder-pv63pq?file=/src/logic.tsx

**Comment by henrikvolmer** [comment]
Then just add the fields without any validator:

https://codesandbox.io/s/morning-glitter-ypdjnn?file=/src/logic.tsx

**Comment by mtr1990** [comment]
Hi, 

Yes I know but is this a must?

```
const NewBlogSchema = Yup.object().shape({
  title: Yup.string().required("Title is required"),
  description: Yup.string().required("Description is required"),
  content: Yup.string(), => Required here
  metaTitle: Yup.string() => Required here
});
```

if the case is createDate: `Date | string | number | null`

and 

if the case is file: `File | string | null`

How will we define it?

**Comment by henrikvolmer** [comment]
This is not really recommendable, but if that is, what you want, then do it like this:

https://codesandbox.io/s/morning-glitter-ypdjnn?file=/src/logic.tsx

**Comment by mtr1990** [comment]
Update:

```
  content: Yup.mixed<File | string>()
    .nullable()
    .required("content is required"),
```

<img width="947" alt="Screenshot 2023-06-14 at 20 57 14" src="https://github.com/react-hook-form/resolvers/assets/13531993/e4bade15-22f2-4c4d-8cba-5d0f21c16287">

=> Can catch errors. But type error

```
  content: Yup.mixed<File | string>()
    .required("content is required")
     .nullable(),
```

<img width="930" alt="Screenshot 2023-06-14 at 20 57 03" src="https://github.com/react-hook-form/resolvers/assets/13531993/63a688d1-caaf-4e42-b869-3c7519973da8">


=> Can not catch errors. 

https://codesandbox.io/s/rough-bash-sj3f6x?file=/src/logic.tsx
