### ISSUE TITLE
@hookform/resolvers doesn't work with IE11

### ISSUE THREAD

**Issue by jcolakk** [react-hook-form/resolvers#61]
Hi, although there is a transpiled module, it still doesn't work with IE11. 

Resolver imported from the transpiled module:
`import { yupResolver } from '@hookform/resolvers/dist/index.ie11';`

Error:
> /node_modules/@hookform/resolvers/dist/index.ie11.js:1
import { transformToNestObject, appendErrors } from 'react-hook-form';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)

Tried in `Next.js` project.

**Comment by jorisre** [comment]
Hi @jcolakk 👋🏻 
The [next version _(currently as release candidate)_](https://github.com/react-hook-form/resolvers/releases/tag/v1.0.0-rc.2) fix severals issues and should work with IE11 by importing yup resolver as the following: 
```ts
import { yupResolver } from '@hookform/resolvers/dist/ie11/yup';
```

Let me know if issue persist

**Comment by jcolakk** [comment]
I just tried the deployed example above in VirtualBox IE11, and it still doesn't work. But different error this time:
![image](https://user-images.githubusercontent.com/42477419/94245277-4cbe6480-ff1a-11ea-8cb1-022d39bcd041.png)

Sorry for image, cant copy from IE11 for some reason.

And I also tried the release candidate in my app, unfortunately also doesnt work.

**Comment by jorisre** [comment]
@jcolakk Don't know why but deployed example was wrong _(the example use yup instead of joi)_.
You can test it again at https://csb-dms1i.vercel.app/
I've juste tested on IE11 and it works :)

**Comment by jcolakk** [comment]
You're right, it indeed works. I'll try again in our app, maybe I missed something. Thanks for the help! :)

**Comment by jcolakk** [comment]
Just tested again, and it works 🎉  Thanks once again!

**Comment by jorisre** [comment]
Perfect ! @hookform/revolvers V1 should be released soon 🚀
