### ISSUE TITLE
Zod resolver: numbers, dates

### ISSUE THREAD

**Issue by meoyawn** [react-hook-form/resolvers#62]
Zod resolver refuses to accept valid `input[type=number]` and `input[type=date]`

```ts
import React from "react";
import { useForm } from "react-hook-form";
import * as z from 'zod';
import { zodResolver } from "@hookform/resolvers/zod";

const schema = z.object({
  num: z.number(),
  date: z.date(),
})

export default function Foo(): JSX.Element {
  const { register, handleSubmit, errors } = useForm({ resolver: zodResolver(schema) })

  const onSubmit = handleSubmit((values) => {
    console.log(values)
  })

  const numErr = errors.num?.message
  const dateErr = errors.date?.message

  return (
    <form onSubmit={onSubmit}>
      <input name="num" type="number" inputMode="decimal" ref={register} />

      {numErr && <p style={{ color: "red" }}>{numErr}</p>}

      <input name="date" type="date" ref={register} />

      {dateErr && <p style={{ color: "red" }}>{dateErr}</p>}

      <button type="submit">Submit</button>
    </form>
  )
}
```

while Yup resolver works perfectly

Might try to fix this myself when I find time

**Comment by bluebill1049** [comment]
That's because by default input return "string" type unless read as `valueAsNumber`

**Comment by meoyawn** [comment]
@bluebill1049 thanks, can you please also point out why it works with the Yup resolver?

**Comment by meoyawn** [comment]
aha, so this can be fixed by patching `zodResolver`?

**Comment by bluebill1049** [comment]
if you want to validate as a number, your component/controller should supply number: https://codesandbox.io/s/ecstatic-waterfall-yfsqe. I think zudRolver is correct.

**Comment by johnnypea** [comment]
You can try a new Zod feature "Transformations " https://github.com/vriad/zod/issues/100 in v2 Beta ;). It works perfectly.

**Comment by meoyawn** [comment]
@johnnypea it works! thanks much

**Comment by itiszac** [comment]
reopen

**Comment by jorisre** [comment]
> reopen

Please open a new issue

**Comment by thobhanifreddy** [comment]
With zod v3, we can use [`preprocess` ](https://zod.dev/?id=preprocess)

Example:

```
z.preprocess(
    (args) => (args === '' ? undefined : args),
    z.coerce
      .number({ invalid_type_error: 'Price must be a number' })
      .positive('Price must be positive')
      .optional()
  ),
```

**Comment by cupid20103** [comment]
How about this?
date: z.date({
    invalid_type_error: "Invalid date type",
  }),

**Comment by droidada** [comment]
Having the same issue with z.date

**Comment by darynmitchell** [comment]
> With zod v3, we can use [`preprocess` ](https://zod.dev/?id=preprocess)
> 
> [Good Example]

@thobhanifreddy’s example was helpful to me, so in case this is helpful to anyone,  
a reusable form:
```js
// Useful to avoid confusing error message when validating input that is empty,
// e.g. "Expected number, received string”, but what you really want is “Required”
function emptyStringAsUndefined(zodStuff: ZodTypeAny) {
  return z.preprocess(
    (arg) => (arg == '' ? undefined : arg),
    zodStuff,
  );
}

const numericInputSchema = emptyStringAsUndefined(z.number());
```
