### ISSUE TITLE
[valibot 🤖]: Cannot conditionally require a field without freezing web page

### ISSUE THREAD

**Issue by demarchenac** [react-hook-form/resolvers#628]
# Describe the bug
As the title states, I'm just trying to conditionally require a field via the `object() pipeline` with `valibot`. I just so happens that the web page freezes when doing so.

# To Reproduce
It's easy to reproduce since I have a working example on [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-z8ytsk?file=src%2FApp.tsx).

Basically, the way to trigger this bug is to modify the `Required Input` whenever any of the other three inputs doesn't have a value, if I were to fill those three up, modifying the `Required Input` doesn't freeze the web view.

# Expected behavior
I should be able to conditionally require a field within a form depending on other fields.

# Desktop (please complete the following information):
- OS: Win 11
- Browser Chrome
- Version 116.0.5845.141 (64-bit)

# Additional context
I've also added up to a [related issue within the valibot repo](https://github.com/fabian-hiller/valibot/issues/5)

**Comment by irg1008** [comment]
Happens to me as well, makes object checks like sibling field equality impossible

**Comment by demarchenac** [comment]
Well, it ain't impossible, we need to create custom pipeline methods as shown in the following valibot issues:
- [#5](https://github.com/fabian-hiller/valibot/issues/5)
- [#145](https://github.com/fabian-hiller/valibot/issues/145)

But it's really weird that the `custom` pipeline method breakes the application when being used on `object` schemas

**Comment by jorisre** [comment]
@demarchenac, has your issue been resolved?

**Comment by demarchenac** [comment]
@jorisre I managed to find a work-around avoiding the usage of custom, also this seems to be fixed on further releases
