### ISSUE TITLE
Failed to parse source map + IE11

### ISSUE THREAD

**Issue by c0d3x** [react-hook-form/resolvers#64]
Running latest version 1.0.0 I get these complications:

Failed to parse source map .../node_modules/@hookform/resolvers/src/yup.ts'
file: Error: ENOENT: no such file or directory, open '.../react-app/node_modules/@hookform/resolvers/src/yup.ts'

Also can you provide example of how using it with IE11 in documentation?
Should it be like this?
```JS
import { yupResolver } from '@hookform/resolvers/dist/ie11/yup';
```

When using it with IE11 I get this:
![image](https://user-images.githubusercontent.com/661911/95059552-5190ce80-06f9-11eb-9c85-a1869acd5d82.png)

**Comment by bluebill1049** [comment]
🙈 IE 11 FML! probably leave as low priority for this 🙏

**Comment by jorisre** [comment]
I'll look into this issue 🕵🏻‍♂️

@c0d3x You can find a little example at **Browser Supports**  section in [FAQs page](https://react-hook-form.com/faqs)

**Comment by jorisre** [comment]
@c0d3x Can you tell me how you get that error ? thanks

**Comment by c0d3x** [comment]
> @c0d3x Can you tell me how you get that error ? thanks

The map error I get when running the application.

The IE11 bug I get when opening the app, it crashes the entire app and refers to the HTMLElement.
When I uncomment the resolver import and reference in useForm(), then the app works fine.

**Comment by c0d3x** [comment]
Any update on this?

**Comment by jorisre** [comment]
@c0d3x 👋🏻  !

I'm Working on it :)

**Comment by jorisre** [comment]
Hi @c0d3x !

Here a working example with @hookform/resolvers ie11
https://github.com/jorisre/hookform-resolvers-ie11-example

To make it works, be to sure:
- to follow these instructions https://create-react-app.dev/docs/supported-browsers-features/#supported-browsers
- to have ie11 in your browserlist config

**Comment by bluebill1049** [comment]
Thanks, heaps for looking into this @jorisre

**Comment by c0d3x** [comment]
Thanks for your example code, your code did run in IE11 vm image!
But still I dont see the difference from my code and yours, besides that I am using TypeScript files and code.

Did you test it with TypeScript?

**Comment by c0d3x** [comment]
We are not transpiling any external libs, so the IE11 version needs to be compatible to work in IE11.
The RHF form works fine, the hookform however does not.
Using latest RHF and hookform, still complains of this line of code:
![image](https://user-images.githubusercontent.com/661911/95977868-afb86280-0e19-11eb-91de-0cee87a79209.png)

**Comment by jorisre** [comment]
@c0d3x Can you provide a full reproduction example please (config etc..) ? Thanks

**Comment by c0d3x** [comment]
@jorisre Yes, I will try to reproduce the error setting up a TS project.
Will get back to you soon 👍🏼

**Comment by c0d3x** [comment]
Do you know why it is looking for yup*.*ts** when there is only a yup**.js** file in the node_modules path it's referencing?

Ref this:
WARNING in ./node_modules/@hookform/resolvers/dist/ie11/yup.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/myproject/react-app/node_modules/@hookform/resolvers/src/yup.ts' file: Error: ENOENT: no such file or directory, open '/myproject/react-app/node_modules/@hookform/resolvers/src/yup.ts'

**Comment by c0d3x** [comment]
@jorisre 
So I think we found the bug now, the problem is that it uses the wrong file when referencing the ie11 path.
Because when inspecting code it uses an arrow function instead of regular function:
```JS
var isHTMLElement = (value) => value instanceof HTMLElement;
```
When following the path of the source:
![image](https://user-images.githubusercontent.com/661911/96115295-0344b200-0ee7-11eb-8df6-8c166de97b51.png)

I get this, so I guess it has some interference of some sort with the non IE11 version.
![image](https://user-images.githubusercontent.com/661911/96115195-dabcb800-0ee6-11eb-8ac6-181324019293.png)

**Comment by c0d3x** [comment]
@bluebill1049 Probably better to have it in an IE11 folder like hookform got?

**Comment by c0d3x** [comment]
the map source file is referencing arrow functions too: index.ie11.development.js.map

**Comment by c0d3x** [comment]
![image](https://user-images.githubusercontent.com/661911/96148379-80345380-0f08-11eb-919c-f0a21c52c919.png)
Looks like it might be because of this import that the hookform is doing, relying on this ESM non IE11 lib.

**Comment by jorisre** [comment]
@c0d3x Thanks for additional informations. Can you provide a reproduction example please ?

**Comment by c0d3x** [comment]
I dont have the option to reproduce our webpack environment because it is stored in alot of npm libs, all I know is that we dont transpile node_modules libs.

However I can show you where the issue happens, so in this file on line 71 there is a conflict.
`./node_modules/@hookform/resolvers/dist/ie11/yup.js 71:24-50`
Problem is that the required react-hook-form is not IE11 version so the build will use the index.esm.js version of RHF.

If I replace the code in index.esm.js with index.ie11.development.js in RHF, and build.
The form works in IE11.

I dont know if you have some information regarding how webpack config needs to be in order for this to work or if this is a bug?

**Comment by jrolfs** [comment]
Sadly having to scramble to support IE11 for a client and I'm running into this as well. I'm seeing the same thing as @c0d3x (the `ie11` bundle imports `react-hook-form` instead of `react-hook-form/dist/index.ie11`).

At first glance I suspect this https://github.com/react-hook-form/resolvers/pull/48 wasn't properly ported over into the new entry point build. I'll be continuing on this tomorrow and will pull this repo down and hack at the Rollup config/build a bit to see if I can't get a PR up.

**Comment by jrolfs** [comment]
@c0d3x quick thought: you may be able to workaround this by pinning to **v0.1.1** and following the directions in this PR: https://github.com/react-hook-form/resolvers/pull/48.

**Comment by jorisre** [comment]
Okay so I have a solution which might work.
I'll open a pull request and @bluebill1049 will make a test release for you :)

**Comment by jrolfs** [comment]
Ah, that's great news @jorisre — I really wanted to help out but time constraints have me moving forward with https://github.com/ds300/patch-package for the moment. I will readily test any RC's though 😄!

**Comment by c0d3x** [comment]
@jorisre How are we doing with the RC, have you made the test release?
Let me know if you want me to test it.

**Comment by jorisre** [comment]
> @jorisre How are we doing with the RC, have you made the test release?
> Let me know if you want me to test it.

@bluebill1049 will make a RC once I've solved this issue :)

**Comment by jorisre** [comment]
@c0d3x @jrolfs here is a beta version `@hookform/resolvers@1.0.1-beta.1`

**Comment by c0d3x** [comment]
This version works in my IE11 setup.

**Comment by c0d3x** [comment]
But I get this now, since typings are not there.
Error:(25, 64) TS2347: Untyped function calls may not accept type arguments.

**Comment by jorisre** [comment]
Hi @c0d3x 
Can you provide more details please ? or a codesandbox ? Thanks

**Comment by c0d3x** [comment]
Well there are not referenced any types for yup config in your version, dont think you need a codesandbox for that.
`Error:(5, 29) TS2307: Cannot find module '@hookform/resolvers/dist/ie11/yup' or its corresponding type declarations.`
![image](https://user-images.githubusercontent.com/661911/97189628-1a1bbc00-17a5-11eb-9938-3e4439d0bda7.png)

**Comment by jorisre** [comment]
Yes that's "normal", types are generated separetly. Same problem for `react-hook-form/dist/index.ie11`.

You should do the following thing _(not tested):_

```ts
// hookform-resolvers.d.ts
declare module '@hookform/resolvers/dist/ie11/yup' {
    export * from '@hookform/resolvers';
}
```

[_(example)_](https://github.com/react-hook-form/react-hook-form/issues/56#issuecomment-538160265)

**Comment by c0d3x** [comment]
I have two applications, the other one I have is using this lib:
`import { useTypedController } from '@hookform/strictly-typed';`

It has same issue as with @hookform/resolvers, it imports the default rhf lib that is not IE11 compatible.

**Comment by jorisre** [comment]
> I have two applications, the other one I have is using this lib:
> `import { useTypedController } from '@hookform/strictly-typed';`
> 
> It has same issue as with @hookform/resolvers, it imports the default rhf lib that is not IE11 compatible.
> When I remove this:
> "@hookform/strictly-typed": "0.0.4",
> It works with the beta, so I guess the strictly-typed lib needs a bump also?

Okay, I'll look at it later

Does [this](https://github.com/react-hook-form/resolvers/issues/64#issuecomment-716614092) work ?

**Comment by c0d3x** [comment]
I tried adding it to override this in my type-overrides.d.ts file, but it did not work. Was that what you ment?
For RHF, it has a type file as a reference index.ie11.d.ts file in same path, so it finds that automatically.

**Comment by c0d3x** [comment]
We are soon hitting production 📦  any updates on when this patch will be available? 🏎️  😄

**Comment by bluebill1049** [comment]
Thanks very much for @jorisre 's contribution ❤️
