### ISSUE TITLE
Form not submitting when using drizzle-zod to create schemes to use in zodResolver

### ISSUE THREAD

**Issue by Eirfire** [react-hook-form/resolvers#642]
**Describe the bug**
When using `drizzle-zod` to generate schemas from database schemas and using them in the `useForm` resolvers the onSubmit won't fire at all for some reason, 

So for example:

```ts
export const userSchema = createInsertSchema(users);
```

and then using it in the `useForm`
```ts
const { handleSubmit, register, control, getValues } = useForm<User>({
    resolver: zodResolver(userSchema),
    defaultValues: async () => {
      const res = await fetch(`/api/users/`)
      const user = (await res.json()) as User;
      return user;
    },
  });

  const onSubmit: SubmitHandler<User> = async (data) => {
    console.log(data)

    await fetch('/api/users/updateUser', {
      method: "PUT",
      body: body: JSON.stringify(data),
    })
  };
```

in this example when you click the `Submit` from the form it doesn't work at all. 

however if you build your own schema using zod it works fine. 

For reference this was working about a about a week ago.

No errors show in the browser console or terminal, so i don't know what is up there

**To Reproduce**

1. create a schema using zod
2. create a zod schema using `drizzle-zod` and `createInsertSchema`
3. import that schema into a `useForm` resolver 
4. try submitting the form (should not work)

 **Codesandbox link (Required)**
very simple application that doesn't seem to submit: 
https://codesandbox.io/p/sandbox/react-hook-form-zod-resolver-not-working-9c7qn9

**Expected behavior**
I expected that validation would work out of the box as usual 

**Desktop (please complete the following information):**

- OS: Mac ventura 13.5.2, Windows 10, Windows 11
- Browser Chrome
- Version latest

**Additional context**

References:
- [drizzle-zod](https://orm.drizzle.team/docs/zod)
- [My app that i'm building](https://github.com/Eirfire/Meally)
  - [zodSchemas / db](https://github.com/Eirfire/Meally/tree/master/apps/meally/src/server/db)
  - [profile settings page](https://github.com/Eirfire/Meally/blob/75-first-release/apps/meally/src/app/(user)/%5Bprofile%5D/settings/profile/page.tsx) *just commented out the resolver for it to work*

**Comment by Ciscodefran** [comment]
how?
