### ISSUE TITLE
After installed new version resolvers  Can't resolve '@hookform/resolvers' 

### ISSUE THREAD

**Issue by andrconstruction** [react-hook-form/resolvers#66]
Can't resolve '@hookform/resolvers' 

![image](https://user-images.githubusercontent.com/7435330/95254802-1ee5f380-0829-11eb-8045-c56be5ff3063.png)

![image](https://user-images.githubusercontent.com/7435330/95254818-273e2e80-0829-11eb-895f-7e7bee7fbaa9.png)

**Comment by andrconstruction** [comment]
How to solve this problem&

**Comment by andrconstruction** [comment]
cache not updated

**Comment by mehmetnyarar** [comment]
@andrconstruction I'm having the same problem.

Did `yarn cache clean --force` but didn't help. How did you solve it?

**Comment by andrconstruction** [comment]
I can advise only remove all node modules andr reinstall again

**Comment by HriBB** [comment]
I am having the same problem. I am using `lerna` monorepo. I tried removing `yarn.lock` and `node_modules` in root and all subpackages and did a fresh install, no go. I tried `yarn cache clean --force`, no go.

![Screenshot from 2020-12-08 22-28-24](https://user-images.githubusercontent.com/4412324/101543645-cce65900-39a4-11eb-87fb-89518c9f03db.png)

**Comment by bluebill1049** [comment]
> I am having the same problem. I am using `lerna` monorepo. I tried removing `yarn.lock` and `node_modules` in root and all subpackages and did a fresh install, no go. I tried `yarn cache clean --force`, no go.
> 
> ![Screenshot from 2020-12-08 22-28-24](https://user-images.githubusercontent.com/4412324/101543645-cce65900-39a4-11eb-87fb-89518c9f03db.png)

which version are you using? can you reproduce this in a codesandbox for us?

**Comment by jorisre** [comment]
@bluebill1049  @HriBB Your problem is fixed by https://github.com/react-hook-form/resolvers/pull/89 but not released

**Comment by bluebill1049** [comment]
@jorisre release it now.
