### ISSUE TITLE
Support `@effect/schema`

### ISSUE THREAD

**Issue by licarth** [react-hook-form/resolvers#666]
**Is your feature request related to a problem? Please describe.**
[`@effect/schema`](https://github.com/Effect-TS/effect/blob/main/packages/schema/README.md#introduction) is [Effect](https://effect.website/)'s Schema library.

**Describe the solution you'd like**
We could write a resolver to support it.

**Describe alternatives you've considered**
N/A

**Additional context**
[@effect/schema API ref](https://effect-ts.github.io/effect/docs/schema)

**Comment by Firfi** [comment]
I have just started looking for an effect/schema resolver, and It's funny to see the issue created 5 days ago. Would you need a hand in writing the resolver @licarth ?

**Comment by jbmusso** [comment]
To anyone interested, there's an ongoing discussion about making an Effect schema resolver here (Effect Discord server): https://discord.com/channels/795981131316985866/1227988682917675110 with an example implementation.

**Comment by binaryartifex** [comment]
FrostyGhostMan here from the discussion referenced by @jbmusso. just about done doing a relative like-for-like of all the tests in the zod resolver against the effect one i pasted into the discussion. The ArrayFormatter is a real life saver for parsing the errors into something react-hook-form can use. ill publish this early next week, hopefully monday. So far its handled everything ive thrown at it. Havn't tested the native validation yet, i suspect the logic for that might need looking at. ill give a shoutout here when its published.

**Comment by binaryartifex** [comment]
pull request is awaiting review - https://github.com/react-hook-form/resolvers/pull/676

**Comment by jorisre** [comment]
Released in 3.4.0.
