### ISSUE TITLE
when type of input is radio，valueAsNumber dont work anymore

### ISSUE THREAD

**Issue by AyaReiOwO** [react-hook-form/resolvers#667]
![微信图片_20240321202104](https://github.com/react-hook-form/resolvers/assets/15058737/9182830a-f19e-4b30-b1be-28b02bb859c4)

**Comment by AyaReiOwO** [comment]
now i know radio cant output number，but what should i do if i want

**Comment by jorisre** [comment]
You can convert `batch_id` from string to number in your submit function using `parseInt`
