### ISSUE TITLE
`Joi` resolver crashes on `File` validation

### ISSUE THREAD

**Issue by romanstetsyk** [react-hook-form/resolvers#668]
**Describe the bug**
The validator crashed while trying to validate a File upload with an error `Cannot read properties of undefined (reading 'length')
`.
The schema like this works fine:
```
const file = Joi.object<File>().label("File");
```
But as soon as I try to add the fields to validate it crashes.
```
const file = Joi.object<File>({
  name: Joi.string().max(255).required(),
}).label("File");
```

**To Reproduce**

1. Go to the codesandbox below
2. Drag any file to the upload area
3. Click 'submit'

**Codesandbox link (Required)**

[https://codesandbox.io/p/sandbox/joi-error-hcktkx?file=%2Fsrc%2FApp.tsx%3A19%2C42](https://codesandbox.io/p/sandbox/joi-error-hcktkx?file=%2Fsrc%2FApp.tsx%3A19%2C42)

**Expected behavior**
Such an error should not appear.

**Screenshots**
<img width="755" alt="image" src="https://github.com/react-hook-form/resolvers/assets/25715951/dccb6e86-244c-44de-9b9e-1860f846e45c">

**Desktop (please complete the following information):**

- OS: macOS 
- Browser chrome
- Version 123

**Comment by hanibhat** [comment]
@romanstetsyk Did you find a solution for this?

**Comment by khaleb-dev** [comment]
@romanstetsyk Did you find a solution?

**Comment by romanstetsyk** [comment]
@hanibhat @khaleb-dev I ended up creating custom validators for file name, mimetype, and file size, e.g.:
```js
import type { CustomValidator } from 'joi';

const fileNameValidator = (minLength: number, maxLength: number): CustomValidator<File> => {
  return (value, helpers) => {
    const nameLength = value.name.trim().length;
    if (nameLength < minLength) {
      return helpers.error('filename.min');
    }
    if (nameLength > maxLength) {
      return helpers.error('filename.max');
    }
    return value;
  };
};
```
Usage:
```js
const fileSchema = Joi.object<File>()
  .instance(File)
  .custom(fileNameValidator(1, 200))
  .messages({
    'filename.min': 'name too short',
    'filename.max': 'name too long',
  });
```
