### ISSUE TITLE
When using `classValidatorResolver`, combining `@IsOptional()` with `@Length()` makes the field required

### ISSUE THREAD

**Issue by angelxmoreno** [react-hook-form/resolvers#669]
**Describe the bug**
When using `classValidatorResolver`, combining `@IsOptional()` with `@Length()` makes the field required

**To Reproduce**
[codesandbox.io](https://rb.gy/8yurn7)

**Expected behavior**
I expect `@IsOptional()` to mark the field as not required, though I feel like i am missing a setting of sorts

**Comment by angelxmoreno** [comment]
sorry for the long and ugly link 🤷

**Comment by jorisre** [comment]
Hi @angelxmoreno, @IsOptional appears to check if the `value === null` or `value === undefined`. However, an input returns an empty string. Consider using `@IsEmpty `
