### ISSUE TITLE
Question: How to dynamically add new Yup validation rule?

### ISSUE THREAD

**Issue by akmalhakimi1991** [react-hook-form/resolvers#67]
I'm currently using Yup to validate my form. However, I have a few inputs that is dynamically generated and the input name is also generated on runtime. Is there a way for me to add new validation rule via `register` or any other means? Thanks

**Comment by bluebill1049** [comment]
you will probably have to build your own `resolver` and combine with `context`.

**Comment by akmalhakimi1991** [comment]
Thanks for the quick response. I believed I am already using a custom `resolver` (based on this [sandbox](https://codesandbox.io/s/react-hook-form-validationschema-v6-2l77g?file=/src/index.js:492-503)). However, I couldn't find any pointers on how to use `context`. Do you have any sandbox with sample `context` usage?

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/resolver-context-sd2vj

**Comment by akmalhakimi1991** [comment]
Thanks!!

**Comment by ssuvorov** [comment]
@akmalhakimi1991 you probably also can build a custom rule in your schema with `yup.addMethod`. And this rule can check all values in a dynamic structure.

e.g.
```js
yup.addMethod(yup.object, 'extraRule', function (message = 'not valid') {
  return this.test('extra-rule', message, async function (value) {
    return true || this.createError({ message });
  });
});
```

**Comment by stephoune** [comment]
Hey @bluebill1049 ! 
I'm wondering how use your codesandbox without toggle button ? 
I want to adjust validationSchema by clicking directly on one of two buttons. The first button will need the first validationSchema. The second button will use the second validationSchema. 
How can i do this without use `setTimeout(callback, 0)` ? 
Here is codesandbox : https://codesandbox.io/s/resolver-context-forked-y034k

**Comment by bluebill1049** [comment]
> Hey @bluebill1049 !
> 
> I'm wondering how use your codesandbox without toggle button ?
> I want to adjust validationSchema by clicking directly on one of two buttons. The first button will need the first validationSchema. The second button will use the second validationSchema.
> How can i do this without use `setTimeout(callback, 0)` ?
> Here is codesandbox : https://codesandbox.io/s/resolver-context-forked-y034k
> 
> Thanks for your help !

hmmm, interesting... I would probably try to do it at `useEffect` level then, so it's on the next render and context will be updated. or you will have to consider to use `useRef`

**Comment by stephoune** [comment]
Thanks ! It works fine !
