### ISSUE TITLE
Zod resolver with typescript not working

### ISSUE THREAD

**Issue by tonyneel923** [react-hook-form/resolvers#69]
![image](https://user-images.githubusercontent.com/5866014/97358337-5d833280-1858-11eb-8c35-ae0c2c19527e.png)

My schema is as follows

```
const schema = z.object({
  flag: z.object({
    label: z.string(),
    value: z.string()
  }),
  reason: z.string()
})

type Flag = z.infer<typeof schema.shape.flag>
type AddFlag = z.infer<typeof schema>
```

**Comment by tonyneel923** [comment]
Am I missing something here? This happened when I tried to use yup as well.

**Comment by jorisre** [comment]
Hi @tonyneel923 

Which version of react-hook-form & resolvers do you use ?

**Comment by tonyneel923** [comment]
Hello @jorisre I am using the lastest for both. I solved my issue though it does not seem to be documented. 

```
const { register, handleSubmit, watch, errors } = useForm<AddFlag>({
    mode: 'onBlur',
    resolver: zodResolver(schema)
  } as Record<string, any>)
```

**Comment by jorisre** [comment]
@tonyneel923 casting is not a good solution.
Typescript should infer.
I can help you if you provide me a codesandbox reproduction :)

**Comment by tonyneel923** [comment]
Attempting to create one now, I cannot get any typescript errors at all though in a cra template app with types added to it though so I will need to figure that out first.

**Comment by tonyneel923** [comment]
I cannot reproduce it in codesandbox. I am not sure what is wrong with my local setup but I will close this issue. Thanks for the help.

**Comment by lukeramsden** [comment]
For anybody that comes across this in future, I was getting the same error. It was due to multiple versions of Zod being present in my module tree with yarn workspaces due to different version requirements - syncing the versions fixed the issue for me.
