### ISSUE TITLE
Form submission proceeds with empty formValue when validation fails using check (formerly custom) in Valibot

### ISSUE THREAD

**Issue by yamatohagi** [react-hook-form/resolvers#690]
**Describe the bug**
When using the check function in Valibot for validation, if validation fails with a case like {isNotify: true, NotifyEmail: ''}, the submit function gets triggered and formValue is lost. This results in submit {} being logged, and the expected behavior is not observed.

**To Reproduce**
1, Go to the form with Valibot validation.
2, Set isNotify to true and leave NotifyEmail as an empty string.
3, Submit the form.
4, Observe that the form is submitted with an empty formValue and the console logs submit {}.
<img width="647" alt="スクリーンショット 2024-06-07 20 18 20" src="https://github.com/react-hook-form/resolvers/assets/53859640/2029d984-0184-489e-bcd8-b0ab048f0cec">

**[My Codesandbox ](https://codesandbox.io/p/devbox/valibot-rhf-bug-forked-6xt8fl?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx4kg70i00063b6iytxxpfsj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx4kg70h00023b6io63lq7c8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx4kg70i00043b6itvve9w5f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx4kg70i00053b6in5xatlqm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx4kg70h00023b6io63lq7c8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx4kg70h00013b6is9qwn7qi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx4kg70h00023b6io63lq7c8%2522%252C%2522activeTabId%2522%253A%2522clx4kg70h00013b6is9qwn7qi%2522%257D%252C%2522clx4kg70i00053b6in5xatlqm%2522%253A%257B%2522id%2522%253A%2522clx4kg70i00053b6in5xatlqm%2522%252C%2522activeTabId%2522%253A%2522clx4kr4wh00e63b6i8o7q846n%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clx4kr4wh00e63b6i8o7q846n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clx4kg70i00043b6itvve9w5f%2522%253A%257B%2522id%2522%253A%2522clx4kg70i00043b6itvve9w5f%2522%252C%2522activeTabId%2522%253A%2522clx4kg70i00033b6iii82g710%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx4kg70i00033b6iii82g710%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clx4kg7bo000adaf837apenpq%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clx4kgg92007d3b6iiypv2g2i%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clx4kgg92007e3b6iq7qeufbf%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)**
Include a codesandbox will help us to investigate the issue quicker.

**Expected behavior**
The form should not submit when validation fails, and appropriate error messages should be displayed without losing formValue.

**Screenshots**
<img width="799" alt="スクリーンショット 2024-06-07 20 21 37" src="https://github.com/react-hook-form/resolvers/assets/53859640/7b0c3888-b9d3-43a7-9bc0-930d932f4363">

Normal time↓
<img width="768" alt="スクリーンショット 2024-06-07 20 26 03" src="https://github.com/react-hook-form/resolvers/assets/53859640/71832f9a-2f48-4910-93fb-7ece4f62846e">

**Desktop (please complete the following information):**
all

**Smartphone (please complete the following information):**
all

**Additional context**
I am willing to help fix this bug if guidance on the approach or the codebase is provided. Thank you for your assistance.

**Comment by yamatohagi** [comment]
//valibot.ts
<img width="616" alt="スクリーンショット 2024-06-07 21 04 02" src="https://github.com/react-hook-form/resolvers/assets/53859640/98e02a9e-a673-4723-9db4-7c0e1b8a15f1">


It might be because there is no path.
```
"NG"
{
    "typed": false,
    "success": false,
    "output": {
        "isCustomerRsvNotify": false,
        "customerRsvNotifyEmail": "la.luce.ymt0326+hoge@gmail.comww",
        "isCustomerCancelNotify": true,
        "customerCancelNotifyEmail": ""
    },
    "issues": [
        {
            "kind": "validation",
            "type": "check",
            "input": {
                "isCustomerRsvNotify": false,
                "customerRsvNotifyEmail": "la.luce.ymt0326+hoge@gmail.comww",
                "isCustomerCancelNotify": true,
                "customerCancelNotifyEmail": ""
            },
            "expected": null,
            "received": "Object",
            "message": "通知先メールアドレスを入力してください",
            "abortPipeEarly": true
        }
    ]
}

"OK"
{
    "typed": false,
    "success": false,
    "output": {
        "isCustomerRsvNotify": false,
        "customerRsvNotifyEmail": "la.luce.ymt032",
        "isCustomerCancelNotify": false,
        "customerCancelNotifyEmail": ""
    },
    "issues": [
        {
            "kind": "schema",
            "type": "union",
            "input": "la.luce.ymt032",
            "expected": "string | \"\"",
            "received": "\"la.luce.ymt032\"",
            "message": "Invalid type: Expected string | \"\" but received \"la.luce.ymt032\"",
            "path": [
                {
                    "type": "object",
                    "origin": "value",
                    "input": {
                        "isCustomerRsvNotify": false,
                        "customerRsvNotifyEmail": "la.luce.ymt032",
                        "isCustomerCancelNotify": false,
                        "customerCancelNotifyEmail": ""
                    },
                    "key": "customerRsvNotifyEmail",
                    "value": "la.luce.ymt032"
                }
            ],
            "issues": [
                {
                    "kind": "validation",
                    "type": "email",
                    "input": "la.luce.ymt032",
                    "expected": null,
                    "received": "\"la.luce.ymt032\"",
                    "message": "メールアドレスが正しくありません",
                    "requirement": {},
                    "abortPipeEarly": true
                },
                {
                    "kind": "schema",
                    "type": "literal",
                    "input": "la.luce.ymt032",
                    "expected": "\"\"",
                    "received": "\"la.luce.ymt032\"",
                    "message": "Invalid type: Expected \"\" but received \"la.luce.ymt032\"",
                    "abortPipeEarly": true
                }
            ],
            "abortPipeEarly": true
        }
    ]
}

**Comment by fabian-hiller** [comment]
This is because the React Hook Form resolver implementation ignores errors that are not related to a nested field (this is the case when `getDotPath(issue)` returns `null`). The resolver should add root or unknown errors to a global error message, but I'm not sure if this is supported by React Hook Form. I am happy to fix it, but I need some guidance or hints by the author of React Hook Form.

**Comment by yamatohagi** [comment]
https://github.com/fabian-hiller/valibot/issues/632
