### ISSUE TITLE
Publish individual npm packages for each resolver

### ISSUE THREAD

**Issue by sant3001** [react-hook-form/resolvers#698]
I believe this package would be really useful if it didn't include a lot of resolvers that one is never going to use.

So if you wanted to use for example just the `zod` resolver, you'd just add the `@hookform/resolvers/zod` package to your project and therefore the size of adding it would be insignificant.

**Comment by jorisre** [comment]
Hey, thanks for the feedback, but multiple packages would be a maintenance headache. Currently, it's tree-shaked, so you only get the resolvers you need and it does not affect your production build.

**Comment by sant3001** [comment]
Ok, got it. Thanks for the quick response @jorisre. 
As for maintenance, I'm not suggesting splitting this repo in multiple repos. I'm just suggesting that when you do the publish step, it deploys to multiple `npm` packages instead of just one.
