### ISSUE TITLE
Question: supporting json schema / ajv

### ISSUE THREAD

**Issue by joshyudeep** [react-hook-form/resolvers#7]
First off, thanks for all the work y'all put into this. 

Are you guys planning to add a resolver for json schema / ajv? 
https://json-schema.org/specification.html
https://github.com/ajv-validator/ajv

**Comment by bluebill1049** [comment]
That would be great, would you please to contribute a resolver for that? https://github.com/react-hook-form/react-hook-form-resolvers V6 will support different types of schema.

**Comment by QuentinDejean** [comment]
Hey guys! Great to see a PR open for that one!

Can we hope to see it merged anytime soon?

**Comment by TheDSCPL** [comment]
This would be awesome! I have a backend writter in Golang and all the JSON schemas are already defined. Being able to use the same JSON schema would be really good for making the code more concise and DRY. Also, the JSON schema is a [standard](http://json-schema.org/) (ajv is just an implementation for javascript) and it should have been one of the first validation methods.

**Comment by bluebill1049** [comment]
anyone would like to take over that PR and address some of the comments?

**Comment by TheDSCPL** [comment]
I'll read through the code and comments to see if I can help

**Comment by TheDSCPL** [comment]
I've finished writing the code. It working with synchronous schemas and also hides the fact that it uses ajv behind the scenes. I called the new resolver `jsonSchema` because that's the actual model it's following. Ajv is an implementation detail.

I'll create a PR.

**Comment by TheDSCPL** [comment]
I also added `@types/json-schema` as a dev dependency to add type safety to the schema input :grin:

**Comment by qlaffont** [comment]
Any update on this ? I didn't see it anymore on ReadMe since rework :/

**Comment by jorisre** [comment]
There is an opened PR https://github.com/react-hook-form/resolvers/pull/59 with some issues

**Comment by bluebill1049** [comment]
Sorry, we are not going to support ajv for now. i know this will make some users angry, but the module ajv old and hard to integrate as far as I can tell. if you need to get it working, please build a custom resolver at your app level.

**Comment by AntonOfTheWoods** [comment]
@bluebill1049 , do you have any further information on what you mean by "the module ajv old and hard to integrate"? ajv is a lot faster than most of the competitors, is still actively developed by lots of developers and has a lot of users, downloads and stars. I didn't look in detail at the code but if it is abstracted properly then I'm not sure I see why that would be a `wontfix`.

Or do you simply not want to support json schema at all?

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/resolvers/issues/309
