### ISSUE TITLE
Add additional properties to Zod resolver for i18n

### ISSUE THREAD

**Issue by HagenMorano** [react-hook-form/resolvers#70]
Currently, there is only `message` and `type` (= `code`) shown from each error that may occur, but for each error code there are additional fields (https://github.com/vriad/zod/blob/master/ERROR_HANDLING.md#zoderrorcode), which are getting filtered:

https://github.com/react-hook-form/resolvers/blob/36f7816798c05b8549a66a3178adf20f749b979a/src/zod.ts#L20-L21

If you want to add i18n to your project and use the `message` provided from the resolver, it is e.g. not possible to include the data types (without doing nasty things like `substring()` or similar).

**Example**

For an `invalid_type` error, the resolvers output is something like this
```
{
    message: 'Expected date, received string',
    type: 'invalid_type'
 }
```
but Zod is already able to generate
```
{
    code: 'invalid_type',
    expected: 'date',
    received: 'string',
    path: [Array],
    message: 'Expected date, received string' 
}
```
which would make i18n possible due to the `expected` and `received` fields.

Is there a reason why these additional fields are filtered?

**Comment by jorisre** [comment]
👋🏻  @HagenMorano !

No reason, I'll look into this

**Comment by bluebill1049** [comment]
Thanks ❤️ , @jorisre just mindful, the change needs to be across for entire resolvers, if not so easy, I would consider this as a feature request, which can action later on.

**Comment by macarie** [comment]
@jorisre, sorry for the tag, but I saw that you had closed this issue as "completed".

Has this been done? Because I can only see the filtered properties, it would be helpful to access the "raw" Zod error.

Is there any way I can help?

**Comment by AlexRequelme** [comment]
I think the same, it would be a very useful functionality if you could have all the ZodError fields

**Comment by mauricecruz** [comment]
Chiming in here because the resolution here seems unclear. Was any change made to make this possible?
