### ISSUE TITLE
ZodResolver error: "Expected number, received string"

### ISSUE THREAD

**Issue by lailo** [react-hook-form/resolvers#73]
The zodResolver example does not work as there is alway the following error.

```
{
  "age":{
    "message":"Expected number, received string",
    "type":"invalid_type"
  }
}
```

Here is a code sandbox to reproduce the error: 
https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-0p8rt?file=/src/App.js

Thanks for your reply/help.

**Comment by jorisre** [comment]
Hi @lailo , this is "normal". You can find an answer here https://github.com/react-hook-form/resolvers/issues/62.

You're right, the example does not work as expected, we have to update it :)

**Comment by lailo** [comment]
Thanks for the quick reply @jorisre. Based on the current documentation and code examples, I was expecting that the `zodResolver` would do the transform for me.

In case someone has the same question, I've updated the code sandbox to use  `zod@beta` v2 and it works now.
https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-0p8rt?file=/src/App.js

**Comment by jorisre** [comment]
@lailo If you won't to update to `zod@beta` v2 and don't need to transform the value in number, you can do the following:

```js
const schema = z.object({
  name: z.string(),
  age: z.string().refine((val) => !Number.isNaN(parseInt(val, 10)), {
    message: "Expected number, received a string"
  })
});
```

**Comment by bluebill1049** [comment]
thanks @jorisre it's awesome to have a zod export in this lib. 🙉

**Comment by adamwdennis** [comment]
After a bit of digging around, i've discovered that the following achieves what i was looking for:

```tsx
<input
  type="number"
  { ...register('myNumberField', { valueAsNumber: true } ) }  // <--- `valueAsNumber` is the solution here...
/>
```

**Comment by ryanhaticus** [comment]
Please see coercion: https://github.com/colinhacks/zod#coercion-for-primitives

**Comment by younes-alouani** [comment]
> After a bit of digging around, i've discovered that the following achieves what i was looking for:
> 
> ```tsx
> <input
>   type="number"
>   { ...register('myNumberField', { valueAsNumber: true } ) }  // <--- `valueAsNumber` is the solution here...
> />
> ```

It works but not if input is optional. When submit is done with empty input i get "Expected number, received nan"

**Comment by omgismartinez** [comment]
Coerce primitive values with Zod. [Full example](https://github.com/colinhacks/zod#coercion-for-primitives)

```typescript
const form = z.object({
    age: z
        .coerce    // SOLUTION
        .number(),
})
```

**Comment by joaquintalice** [comment]
Thank you @omgismartinez, that was the most clean solution for me.

**Comment by itpaulin** [comment]
Thanks @omgismartinez , this way was my solution.

**Comment by sample-tayo** [comment]
thanks @omgismartinez worked for me

**Comment by luiferg** [comment]
> Coerce primitive values with Zod. [Full example](https://github.com/colinhacks/zod#coercion-for-primitives)
> 
> ```ts
> const form = z.object({
>     age: z
>         .coerce    // SOLUTION
>         .number(),
> })
> ```

This worked perfect for me, many thanks @omgismartinez

**Comment by friyad** [comment]
> Coerce primitive values with Zod. [Full example](https://github.com/colinhacks/zod#coercion-for-primitives)
> 
> ```ts
> const form = z.object({
>     age: z
>         .coerce    // SOLUTION
>         .number(),
> })
> ```

You saved my time. Thanks!

**Comment by aksingh-codes-nona** [comment]
> After a bit of digging around, i've discovered that the following achieves what i was looking for:
> 
> ```tsx
> <input
>   type="number"
>   { ...register('myNumberField', { valueAsNumber: true } ) }  // <--- `valueAsNumber` is the solution here...
> />
> ```

Thanks @adamwdennis worked for me

**Comment by shahbaz4783** [comment]
> Coerce primitive values with Zod. [Full example](https://github.com/colinhacks/zod#coercion-for-primitives)
> 
> ```ts
> const form = z.object({
>     age: z
>         .coerce    // SOLUTION
>         .number(),
> })
> ```

thats working for me. thanks!

**Comment by ode96-dev** [comment]
> Coerce primitive values with Zod. [Full example](https://github.com/colinhacks/zod#coercion-for-primitives)
> 
> ```ts
> const form = z.object({
>     age: z
>         .coerce    // SOLUTION
>         .number(),
> })
> ```

works, perfectly!

**Comment by bornbrainy** [comment]
> Thanks @omgismartinez , this way was my solution.

Was your output still a string or number

**Comment by ode96-dev** [comment]
> > Thanks @omgismartinez , this way was my solution.
> 
> Was your output still a string or number 

So, my issue, exactly like yours, kept returning message":"Expected number, received string",
    "type":"invalid_type" on form submission.
With @omgismartinez solution,this was corrected. 
The output was a number.

**Comment by reiuyuu** [comment]
> @lailo If you won't update to `zod@beta` v2 and don't need to transform the value in number, you can do the following:
> 
> ```js
> const schema = z.object({
>   name: z.string(),
>   age: z.string().refine((val) => !Number.isNaN(parseInt(val, 10)), {
>     message: "Expected number, received a string"
>   })
> });
> ```


Input like "123aaa" bypasses validation due to parseInt ignoring non-numeric characters after a valid number.

**Comment by abdullokh-mukhammadjonov** [comment]
> Coerce primitive values with Zod. [Full example](https://github.com/colinhacks/zod#coercion-for-primitives)
> 
> ```ts
> const form = z.object({
>     age: z
>         .coerce    // SOLUTION
>         .number(),
> })
> ```

Solved the issue. Thanks

**Comment by 0xtz** [comment]
```ts
const schema = z.object({
  name: z.string(),
  age: z.number(),
});
```

**Comment by 0xtz** [comment]
> ```ts
> const schema = z.object({
>   name: z.string(),
>   age: z.number(),
> });
> ```

lol you already got the reply :joy:

**Comment by webdiego** [comment]
> ```ts
> z
>         .coerce    // SOLUTION
>         .number()
> ```

Easy and clean!

**Comment by hedaetul** [comment]
> Coerce primitive values with Zod. [Full example](https://github.com/colinhacks/zod#coercion-for-primitives)
> 
> ```ts
> const form = z.object({
>     age: z
>         .coerce    // SOLUTION
>         .number(),
> })
> ```

thanks bro. this helped me a lot...
