### ISSUE TITLE
Cannot pass a component to yupResolver schema error messages

### ISSUE THREAD

**Issue by jcolakk** [react-hook-form/resolvers#74]
**Describe the bug**
When passing a component as an error message. I get an error `Maximum callstack size exceeded` (more info about an error in codesandbox link below).

```
yupResolver(
      yup.object().shape({
        email: yup
          .string()
          .required(<span>Required</span>)
          .test(
            "matches",
            "Wrong email",
            (value) => value === "email@email.com"
          )
      })
    ),
```

**Codesandbox link**
https://codesandbox.io/s/silly-thunder-4y5dj?file=/src/App.js:294-561

**Additional context**
In the project, we have our own `Translation` components, which we would like to pass as an error message.

**Comment by jorisre** [comment]
Hi @jcolakk 👋🏻 

`.required()` is typed as the following:

```ts
export type TestOptionsMessage<Extra extends Record<string, any> = {}, R = any> =
    | string
    | ((params: Extra & Partial<TestMessageParams>) => R);
```

It takes an optional `string` / `function` as argument, that's why it doesn't work. 
You can try `.required(() => <span>Required</span>)` but I'm not sure this works.

**Comment by jcolakk** [comment]
Ahh, you're right, I missed that. It works when passing a function 👍 Thanks!

**Comment by bluebill1049** [comment]
Thank you @jorisre
