### ISSUE TITLE
TSC: Cannot find module '@hapi/joi'

### ISSUE THREAD

**Issue by kingarawana** [react-hook-form/resolvers#78]
There's an issue where the `joi` resolver is importing from `@hapi/joi` but `@hapi/joi` is a devDependency.

I'm thinking `@hapi/joi` needs to be moved to dependencies?

`../../node_modules/@hookform/resolvers/dist/joi.d.ts:2:17 - error TS2307: Cannot find module '@hapi/joi' or its corresponding type declarations.`

**Comment by bluebill1049** [comment]
can you share a CSB?

**Comment by kingarawana** [comment]
What's a CSB?

I basically get this error when I compile w/ typescript. If I set skipLibCheck = true, it passes.

node version: v12.18.3
tsc: 4.0.5

Here's the TS options:

{
  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "target": "es2018",
    "module": "CommonJs",
    "lib": ["es2018"],
    "jsx": "preserve",
    "outDir": "./dist",
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "baseUrl": "./src/",
    "allowSyntheticDefaultImports": true,
    "isolatedModules": false,
    "noErrorTruncation": true,
    "sourceMap": true,
}

**Comment by bluebill1049** [comment]
codesandbox?

**Comment by bluebill1049** [comment]
looks like it's been deprecated: https://github.com/react-hook-form/resolvers/issues/79 will release a new version soon.
