### ISSUE TITLE
bug ie11 export not working in 1.1.0

### ISSUE THREAD

**Issue by belgattitude** [react-hook-form/resolvers#84]
After upgrade to @hookform/resolvers, the ie11 export seems broken.

The import was working on prior version with:

## Code

```typescript
import { yupResolver } from '@hookform/resolvers/dist/ie11/yup';
```

## Now gives a 

```
ModuleNotFoundError: Module not found: Error: Can't resolve '@hookform/resolvers/dist/ie11/yup'
```

## Environement

NextJs 9.5.2, typescript 4.1.1, latest react-hook-form / resolver

## Content of the node_modules

![image](https://user-images.githubusercontent.com/259798/100591362-eda01600-32f5-11eb-85f9-a57422a9a28d.png)

**Comment by jorisre** [comment]
@belgattitude Thanks for reporting, I'll open a PR to fix it.

**Comment by jorisre** [comment]
@bluebill1049 Fixed in https://github.com/react-hook-form/resolvers/releases/tag/v1.1.1

**Comment by bluebill1049** [comment]
Thanks, @jorisre for the fix.
