### ISSUE TITLE
Type error in yup resolver

### ISSUE THREAD

**Issue by chemaxa** [react-hook-form/resolvers#86]
Hi everyone. Thank you for a great tool. 
I tried to use yup resolver with typescript. But i faced with typescript compilation error.

```sh
i ｢wdm｣: Compiled with warnings.
ERROR in D:/Repositories/form/node_modules/@hookform/resolvers/dist/yup.d.ts(3,86):
TS2707: Generic type 'ObjectSchema<TShape, TContext, TIn, TOut>' requires between 1 and 4 type arguments.

ERROR in D:/Repositories/form/node_modules/@hookform/resolvers/dist/yup.d.ts(3,109):
TS2694: Namespace '"D:/Repositories/form/node_modules/yup/lib/index"' has no exported member 'Lazy'.

ERROR in D:/Repositories/form/node_modules/@hookform/resolvers/dist/yup.d.ts(3,134):
TS2694: Namespace '"D:/Repositories/form/node_modules/yup/lib/index"' has no exported member 'ValidateOptions'.
```

My packages:
"yup": "^0.32.5"
"react-hook-form": "^6.12.2",  
"@hookform/resolvers": "^1.1.1",

I tried to use @types/yup but it doesnt help to me
"@types/yup": "^0.29.10",

Can anybody to help me? 
How i can to fix this issue?

**Comment by jorisre** [comment]
Hi @chemaxa 👋🏻 

Could you please provide a reproduction in a [codesandbox](https://codesandbox.io/) ? Thanks

**Comment by chemaxa** [comment]
Hi, i cant reproduce it on codesandbox. But i prepared repository with code sample.

https://github.com/chemaxa/hookresolvers-ts-bug

For reproduce just 

npm install 

npm run start:standalone

I used 
https://single-spa.js.org/docs/create-single-spa
For creating demo project with react, typescript settings.

Also i tried to set esModuleInterop to false, and this bug is out, but this is not applicable for my workflow. 

I dont understand how you used yup objectshema type, when this type is generic and required 1 or 4 params. 
https://github.com/jquense/yup/blob/01c69305424db349ff701fae7cdb31e569c38b6e/src/object.ts#L75

**Comment by chemaxa** [comment]
I reproduced it in codesandbox.

I just imported yup and tried use types as in yuor yup.d.ts file and got same error

https://codesandbox.io/s/yup-typescript-error-d1n3j?file=/src/index.ts

**Comment by chemaxa** [comment]
I think i understand what the reason of this bug, you are used  
i find that you are used 
"@types/yup": "^0.29.9", 
"yup": "^0.31.0", 
in your package.json

But in my package.json 
"yup": "^0.32.5"
 without this package yup types also works "@types/yup": "^0.29.10",

and seems like 32.5 version of yup changes their declarations, and redeclare Lazy, ObjectSchema and ValidateOptions 

https://github.com/jquense/yup/compare/v0.31.0...v0.32.5

and you need to update your dependencies

**Comment by jorisre** [comment]
Thanks for investigations. I'll update Yup

**Comment by jorisre** [comment]
@chemaxa 
Your issue should be fixed
Yup ^0.32.0 is now supported ! [1.3.0](https://github.com/react-hook-form/resolvers/releases/tag/v1.3.0)

**Comment by chemaxa** [comment]
> @chemaxa
> Your issue should be fixed
> Yup ^0.32.0 is now supported ! [1.3.0](https://github.com/react-hook-form/resolvers/releases/tag/v1.3.0)

Thank a lot!
