### ISSUE TITLE
Feature request: support synchronous validation

### ISSUE THREAD

**Issue by Smona** [react-hook-form/resolvers#88]
We are using yup along with react-hook-form, and almost all of our schemata support synchronous validation. Unfortunately, there's no way to use `schema.validateSync` instead of `schema.validate` through the resolver.

While the performance impact of this is negligible, inserting an event loop between form submission and `handleSubmit` being called adds an unnecessary layer of complexity to our tests.

It would be great if we could pass an option to validate the schema synchronously. Better yet, if the resolver attempted to validate synchronously and fell back on asynchronous validation if required.

**Comment by bluebill1049** [comment]
`resolver: async () => schema.validateSync(data)`

have you tried to build your own?

**Comment by Smona** [comment]
No, not yet. I could, but then I would have to copy-paste the source code for the error parser and other imports of the resolver. Which kind of defeats the purpose of the repo :sweat_smile:

**Comment by Smona** [comment]
I suppose I'm assuming that `useForm` would support a synchronous validation resolver. If that's not the case, I can see why this would be harder to implement.

**Comment by jorisre** [comment]
Hi @Smona 👋🏻

FIY Yup sync validation added in the [v2.0.0-beta.5](https://github.com/react-hook-form/resolvers/releases/tag/v2.0.0-beta.5)
You can try it by installing `yarn add @hookform/resolvers@v2.0.0-beta.5`

**Comment by GollyJer** [comment]
HI @jorisre 👋

Stumbled on this today looking for a synchronous solution. 
I have 
```
"@hookform/resolvers": "2.0.0-beta.5",
"react-hook-form": "^6.14.2",
```

And the following code.
```javascript 
const { control, errors, watch, formState } = useForm<FormInputs>({
    mode: 'onChange',
    reValidateMode: 'onChange',
    defaultValues,
    resolver: yupResolver(
      Yup.object().shape({
        syringeUnits: Yup.number().required().moreThan(0),
        syringeTickMarks: Yup.number().required().moreThan(0),
        powderMilligrams: Yup.number().required().moreThan(0),
        waterMilliliters: Yup.number().required().moreThan(0),
        desiredDoseAmount: Yup.number().required().moreThan(0),
      }),
      undefined,
      { mode: 'sync' }
    ),
  });

  const formValues = watch();
  console.log(formValues);
```

I'm still seeing formValues print the old and new value when typing in a field. 
Am I doing something wrong?

Thanks for the work on this! It's going to be super helpful.

**Comment by bluebill1049** [comment]
@GollyJer v6 will not return defaultValue from `watch`, unless supplied as default values 

`watch(undefined, defualtValues)` 

we are fixing this behaviour for V7, so defaultValue will be returned before render.

**Comment by GollyJer** [comment]
@bluebill1049 Good to know. Thanks!

**Comment by Smona** [comment]
@jorisre hey, awesome! Thanks for taking this on

**Comment by jorisre** [comment]
Closing, [V2 released](https://github.com/react-hook-form/resolvers/releases/tag/v2.0.0) 🎉
