### ISSUE TITLE
Cannot resolve symbol 'yupResolver' 

### ISSUE THREAD

**Issue by LuisFilipePedroso** [react-hook-form/resolvers#91]
Hey, I'm trying to import yupResolver in my project, where I'm using Typescript but I'm getting this error:
**Cannot resolve symbol 'yupResolver'** 
 
I'm importing yupResolver like this:
`import { yupResolver } from '@hookform/resolvers/yup';`

Is there something that I'm doing wrong?

Version of @hookform/resolvers: 1.1.2
Version of react-hook-form: 6.12.2
Version of Yup: 0.32.8

**Comment by jorisre** [comment]
👋🏻  @LuisFilipePedroso 

I think, it's related to https://github.com/react-hook-form/resolvers/issues/86. I've started working on it yesterday.


Could you confirm it's the same error ? Or provide a reproduction example in codesandbox please ?

**Comment by LuisFilipePedroso** [comment]
Hey @jorisre , I saw this issue but I guess that he was able to import yupResolver, in my case, I'm not being able to import, what is strange. 

You can check the code here:
https://github.com/LuisFilipePedroso/Youtube-React-Form

Form is here:
https://github.com/LuisFilipePedroso/Youtube-React-Form/blob/master/src/components/Form/index.tsx

To run, just install the dependencies and execute the commands:

npm run api 
npm run start

**Comment by jorisre** [comment]
Thanks ! I'll look at it later :)

**Comment by LuisFilipePedroso** [comment]
Thanks.

**Comment by jorisre** [comment]
This issue is related to #86. Yup versions are different that's why this error occur.

**Comment by jorisre** [comment]
@LuisFilipePedroso 
Your issue should be fixed
Yup ^0.32.0 is now supported ! [1.3.0](https://github.com/react-hook-form/resolvers/releases/tag/v1.3.0)
